### ISSUE TITLE
Best way to perform validation

### ISSUE THREAD

**Issue by Fuitad** [Fody/PropertyChanged#1007]
Good morning,

Just a quick question, which I hope is OK. What is the best way to perform a validation on a value being set? 

Let's say I had this in my code before using Fody/PropertyChanged:
```
private int quantity;
public bool CannotBeMoreThanOne = true;

public int Quantity
{
    get
    {
        return quantity;
    }
    set
    {
        if (CannotBeMoreThanOne)
            value = Math.Max(1, value);

        quantity = value;
        RaisePropertyChanged();
    }
}
```

With PropertyChanged, my code became this:
```
public bool CannotBeMoreThanOne = true;

public int Quantity { get; set; }
```
And I ended up losing the validation. I thought of doing this but I'm afraid I think I'm sending my code in an endless recursive loop:
```
public void OnQuantityChanged()
{
  if (CannotBeMoreThanOne)
  Quantity = Math.Max(1, Quantity);
}
```

Hopefully someone can point me right direction to validate my models using PropertyChanged. Thanks! ^^

**Comment by ltrzesniewski** [comment]
You can leave validation in the property, but remove the call to `RaisePropertyChanged`:

```csharp
private int quantity;
public bool CannotBeMoreThanOne = true;

public int Quantity
{
    get => quantity;
    set
    {
        if (CannotBeMoreThanOne)
            value = Math.Max(1, value);

        quantity = value;
    }
}
```

This will be compiled to the following:

```csharp
public int Quantity
{
  get => this.quantity;
  set
  {
    if (this.quantity == value)
      return;
    if (this.CannotBeMoreThanOne)
      value = Math.Max(1, value);
    this.quantity = value;
    this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Quantity);
  }
}
```

Note that PropertyChanged.Fody added the `if (this.quantity == value)` check. If that's ok for your case, then you're done. If that's a problem, you can add a `[DoNotCheckEquality]` attribute on the property.

There are [more attributes](https://github.com/Fody/PropertyChanged/wiki/Attributes) you can use to adjust the behavior to what you need.
