### ISSUE TITLE
Classes derived from ApplicationSettingsBase don't have their properties weaved.

### ISSUE THREAD

**Issue by distantcam** [Fody/PropertyChanged#105]
Here's a class

    public class MySettings : ApplicationSettingsBase
    {
        [UserScopedSetting]
        public string MyValue
        {
            get { return (string)this["MyValue"]; }
            set { this["MyValue"] = value; }
        }
    }

`ApplicationSettingsBase` implements `INotifyPropertyChanged` and has this method.

    protected virtual void OnPropertyChanged(object sender, PropertyChangedEventArgs e);

But when compiling I'm getting the following error.

> 1>MSBUILD : warning : Fody/PropertyChanged: 	Could not find EventInvoker method on type 'MySettings'. Possible names are 'OnPropertyChanged, SetProperty, NotifyOfPropertyChange, RaisePropertyChanged, NotifyPropertyChanged, NotifyChanged, raisePropertyChanged'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Please either correct 'EventInvokerNames' or implement your own EventInvoker on this class. No derived types will be processed. If you want to suppress this message place a [DoNotNotifyAttribute] on MySettings.

**Comment by systemsymbiosis** [comment]
I observe a very similar error when using a ViewModel class based on ReactiveUI (Version 6.1.0) ReactiveObject 

Warning	1	Fody/PropertyChanged: 	Could not find EventInvoker method on type 'ViewModel'. Possible names are 'raisePropertyChanged, OnPropertyChanged, SetProperty, NotifyOfPropertyChange, RaisePropertyChanged, NotifyPropertyChanged, NotifyChanged, raisePropertyChanged'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Please either correct 'EventInvokerNames' or implement your own EventInvoker on this class. No derived types will be processed. If you want to suppress this message place a [DoNotNotifyAttribute] on ViewModel.

I can work around the warning for the time being by using a base class. But I do not think I should have to do this since ReactiveObject already implements the EventInvoker?

```C#
    public class ReactiveBaseObject:ReactiveObject
    {
        public new event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null)
            {
                handler(this, e);
            }
        }

        public new event PropertyChangingEventHandler PropertyChanging;

        protected virtual void OnPropertyChanging(PropertyChangingEventArgs e)
        {
            PropertyChangingEventHandler handler = PropertyChanging;
            if (handler != null)
            {
                handler(this, e);
            }
        }
    }
```

**Comment by distantcam** [comment]
@systemsymbiosis This should be raised as a new issue. I noticed this just recently myself but in ReactiveUI v6+ they changed the name of the methods used to invoke the events. :/

**Comment by SimonCropp** [comment]
they are also using explicit methods :(

**Comment by distantcam** [comment]
Yeah ever since v4 I've had major problems with their API, and it just keeps getting worse.

**Comment by shiftkey** [comment]
@systemsymbiosis what version of the .NET framework are you targeting in that project? I think you're hitting [this code](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ReactiveObject.cs#L38-L46) which would explain why it's not able to resolve `RaisePropertyChanged` at least...

**Comment by SimonCropp** [comment]
@shiftkey yep that is the problem. Fody wont find explicitly named methods since the assumption is they are explicit to hide them from the API. If reactive has reasons for not wanting implementations to call the the RaisePropertyChanged explicitly then I dont think i should fight it. Will just document that reactive is no longer supported

**Comment by shiftkey** [comment]
cc @jlaanstra about whether hiding `RaisePropertyChanged` this is the ReactiveUI Zen Way (I'm neutral on this) and that this is The Right Way™ to generate the backing logic for ReactiveUI properties (`RaiseAndSetIfChanged` - the extension method - has been around for a couple of versions, but I don't see it in your list which might explain all the problems). 

```
public string Owner
{
    get { return owner; }
    set { this.RaiseAndSetIfChanged(ref owner, value); }
}
```

Reference: https://github.com/reactiveui/ReactiveUI/commit/1b2b98222b7259ab0dae82ca18a4a23c87020dea

**Comment by systemsymbiosis** [comment]
I am compiling against 4.5.1. I am not 100% sure of the implications of me using the base class I tried out as a workaround, maybe that will mess with ReactiveUI? I will likely have to implement all the properties as ReactiveUI specifies. But I have found Fody very useful and really like how it keeps the code tidy.

**Comment by SimonCropp** [comment]
@systemsymbiosis @shiftkey  ok so i just waded into the reactive code. I can see any reason why RaisePropertyChanged needs to be explicit. correct me if i am wrong.

using propertychanging and propertychanged via fody means 

```
public string Owner
{
    get { return owner; }
    set { this.RaiseAndSetIfChanged(ref owner, value); }
}
```
can become
```
public string Owner {get; set ;}
```

@systemsymbiosis  So suggest you raise an issue in the reactiveUI repo asking for the method to be a simple public method.

The other alternative is to inject your own base class
```
    public abstract class MyReactiveObject :ReactiveObject , INotifyPropertyChanged, IReactiveObject
    {
        public void RaisePropertyChanged(PropertyChangedEventArgs args)
        {
            ((IReactiveObject)this).RaisePropertyChanged(args);
        }
    }
```

**Comment by shiftkey** [comment]
>  I am not 100% sure of the implications of me using the base class I tried out as a workaround, maybe that will mess with ReactiveUI?

You should be fine. The main reason why RxUI has gone down this path of extension methods is to reduce the unnecessary INPC calls - that is, times when the value hasn't changed. 

By adding in your custom base class, you're avoiding that benefit - but Fody will inject the IL to take care of the "value hasn't changed" situations all the same...

**Comment by systemsymbiosis** [comment]
Thanks guys for the feedback. I'll test things out further to see if my program is still working properly. I'll raise an issue over on the ReactiveUI repo and see what they think. Cheers.

**Comment by jlaanstra** [comment]
Correct me if I am wrong but can't we just add the RaiseAndSetIfChanged method to the list of EventInvokerNames?

**Comment by SimonCropp** [comment]
@jlaanstra nope. `RaiseAndSetIfChanged` is an extension method

**Comment by jlaanstra** [comment]
Can you check for an implementation of IReactiveObject? In that case the extension method should always be there.

**Comment by SimonCropp** [comment]
After discussing with @paulcbetts i think i need to support this explicitly here

**Comment by systemsymbiosis** [comment]
Just came across a nice new addition on GitHub that addresses this issue with a Fody extension  https://github.com/kswoll/ReactiveUI.Fody

I think I will test it out as an alternative solution.

**Comment by SimonCropp** [comment]
ok closing this. people who want to use ReactiveUI can either use a base class (that calls the Reactive extensions in OnPropertyChanged) or use this https://github.com/kswoll/ReactiveUI.Fody
