### ISSUE TITLE
Nullable reference types is not available in C# 7.3 on dotnet-Standard 2.0

### ISSUE THREAD

**Issue by harryneufeld** [Fody/PropertyChanged#1051]
#### Describe the issue

When creating a classlibrary with **.NET-Standard 2.0** there is a compilation-error with weaving the OnPropertyChanged Event into a class that has not implemented the Event. 

The Compilation Error then says: 
"_Feature 'nullable reference types' is not available in C# 7.3. Please use language version 8.0 or greater._"

#### Minimal Repro

- Create a new .NET-Standard 2.0 Classlibrary-Project with Visual Studio 2022 Community (latest on 04.04.2024). 
 - Install The "PropertyChanged.Fody"-NuGet, the "Fody"-NuGet will automatically be installed as an transitive package. (Installing the "Fody" package manually does not change the behavior of this problem)
- Create a public partial Class with at least one public Property.
- Add a reference ``using PropertyChanged;``
- Firstly build the library to ensure, that the file "FodyWeavers.xml" is beeing created. Also ensure, that the Tag ``<PropertyChanged />`` is placed inside the ``<Weavers></Weavers>`` Tags
- Add an attribute in the line before the class declaration: ``[AddINotifyPropertyChangedInterface]``

Example:
```csharp
    [AddINotifyPropertyChangedInterface]
    public partial class Class1
    {
        public string Name { get; set; }
    }
```

If you look at the file the error refers to (PropertyChanged.g.cs), you can see the problem in the output file, where a nullable string is beeing created as parameter of the OnPropertyChanged method:
```csharp
    public event PropertyChangedEventHandler? PropertyChanged;
    protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
    }
    protected virtual void OnPropertyChanged(PropertyChangedEventArgs eventArgs)
    {
        PropertyChanged?.Invoke(this, eventArgs);
    }
```

**Comment by tom-englert** [comment]
But why would you want to use c# 7.3 ?

Either use an up-to-date c# version, or do not use the code generator feature.

**Comment by tom-englert** [comment]
This is all about default and recommended, practically it will work fine.

However if you want to stick with 7.3, you can't use the code generator feature.
