### ISSUE TITLE
Does it hurt to have AddINotifyPropertyChangedInterfaceAttribute Inherited = true

### ISSUE THREAD

**Issue by ehinolakingsley** [Fody/PropertyChanged#1083]
﻿using System;
using System.ComponentModel;

namespace PropertyChanged;

/// <summary>
/// Specifies that the class will be marked with <see cref="INotifyPropertyChanged"/>.
/// Note that all classes that implement <see cref="INotifyPropertyChanged"/> will have property notification
/// injected irrespective of the use of this attribute.
/// Raising an issue about "this attribute does not behave as expected" will result in a RTFM and the issue being closed.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Record, Inherited = true)]
public class AddINotifyPropertyChangedInterfaceAttribute : Attribute;

**Comment by SimonCropp** [comment]
how does that make sense? the attribute will cause the base class to have the code injected. inherited classes will then have those features

**Comment by ehinolakingsley** [comment]
Yes. This make life easy for those of us that inherit from base classes and also what notification change on them when those property value changes

**Comment by ehinolakingsley** [comment]
Maybe  a second attribute can be created for that use case and devs can decide which one to use

**Comment by SimonCropp** [comment]
can you share a code example?

**Comment by tom-englert** [comment]
I'd rather make this attribute deprecated, since v4 you should better use the code generator notation

**Comment by tom-englert** [comment]
@ehinolakingsley where did you get `AttributeTargets.Record` from?

**Comment by ehinolakingsley** [comment]
@tom-englert Sorry for adding AttributeTargets.Record. It does not exist.

**Comment by ehinolakingsley** [comment]
Here is a code snippet
![image](https://github.com/user-attachments/assets/f3da0b17-6f9d-4d81-9fdd-6e4f8fdf10ec)

![image](https://github.com/user-attachments/assets/1bb6381f-0295-4fc5-8b86-12ed0cb4d574)

In the first image, I am unable to reuse OnScreenDefaultToCheckOutStatus because the property change does not apply to it since its a base class. In the second image,
 I had to create a new property "_OnScreenDefaultToCheckOutStatus"  so the the Notification attribute with the applied. Due to this nature, if the Attribute also applies to inherited classes,  all I will have to do was just this

**Comment by ehinolakingsley** [comment]
> how does that make sense? the attribute will cause the base class to have the code injected. inherited classes will then have those features

I agree with you. Maybe it you can make it have a parameter with default to false and we can manually flip it to true for classes that needs it.

**Comment by tom-englert** [comment]
I think you misunderstood the meaning of `AttributeUsage.Inherited`. This has nothing to do with what you want to achieve. 

It will never be possible to weave code into a base class by attributing a child class.

**Comment by ehinolakingsley** [comment]
From the example I gave early, to have the parent class behave like the expected, I will have to add the attribute also to the base class. But what if the base class it not accessible.

**Comment by tom-englert** [comment]
> But what if the base class it not accessible.

In that case, as you say, it is not accessible, i.e. Fody cannot inject code there to make it implement INPC.

**Comment by ehinolakingsley** [comment]
I see. Make sense. Thanks for enlighten me. Guess I can close it out then
