### ISSUE TITLE
CS0067 when event PropertyChanged is not used

### ISSUE THREAD

**Issue by BrunoJuchli** [Fody/PropertyChanged#11]
Hi Simon
Let me first thank you for your great work, i really appreciate it.

Having a simple class like

```
class foo : INotifyPropertyChanged {
    public event PropertyChangedEventHandler PropertyChanged;

    public Bar { get; set; }
}
```

Results in a Compiler Warning CS0067 as of course, the property changed notification was not weaved in _yet_.
Usually we treat all Compiler Warnings as Errors, thus the build "fails".
I know of the following ways to circumvent the issue:
-Ignore CS0067 for the entire project, meaning that for all other events which are unused i loose the rule since i cannot disable it for "PropertyChanged" only
or
-Use pragma disable / enable just around public event PropertyChanged..., which has the risk of someone forgetting the enable and furthermore clutters the code.

Do you know of any better solution?

Alternative:
PostSharp 2.x has a solution to the problem, which is:
Opt-In PropertyChanged Notification weaving, by adding an attribute to the class. It will add the INotifyPropertyChanged interface (and implementation) to the class, plus of course the notifications.
Like this:

```
[NotifyPropertyChanged]
class foo {
    public Bar { get; set; }
]
```

would result in

```
class foo : INotifyPropertyChanged {
    public event PropertyChangedEventHandler PropertyChanged;

    public Bar 
      get {
        return this.bar;
      }
      set {
        if(value != this.bar) {
          this.bar = value;
          this.PropertyChanged(this, new PropertyChangedEventArgs("Bar"));
        }
      }
}
```

Would you consider a Pull-Request or is this feature out of the question?

Thank you.

**Comment by malcolmpw** [comment]
I'll need to add a pragma to ignore the PropertyChanged issue for CS0118.   How do i do this?
