### ISSUE TITLE
No code injected when user implements their own getter and/or setter

### ISSUE THREAD

**Issue by nphmuller** [Fody/PropertyChanged#112]
Happens in the latest version as of 12 jan 2015 (1.49.0).
Both in C# as in VB.NET in Visual Studio 2013 Ultimate Update 4

The snippet mentioned in README.md does not automatically inject the INotifyPropertyChanged interface until you uncomment the FullName property. It seems that when the user implements their own getter and setter, no code gets injected in the class at all.

Works:
```
[PropertyChanged.ImplementPropertyChanged]
public class Person 
{        
    public string GivenNames { get; set; }
    public string FamilyName { get; set; }

}
```

Doesn't work:
```
[PropertyChanged.ImplementPropertyChanged]
public class Person
{
    public string GivenNames { get; set; }
    public string FamilyName { get; set; }

    public string FullName
    {
        get
        {
            return string.Format("{0} {1}", GivenNames, FamilyName);
        }
    }
}
```

**Comment by distantcam** [comment]
I cannot reproduce this problem. Could you provide a project that has the issue?

**Comment by nphmuller** [comment]
I was just writing a detailed description how to reproduce the problem, but I suddenly can't reproduce it anymore either. The only thing that has changed on my side is that I've updated dotPeek, which I used to decompile the project and check if the injection worked properly.
So perhaps it was a bug in dotPeek?

If the "bug" occurs again I will update this issue!

Thanks!
