### ISSUE TITLE
FodyWeavers.xml not modified

### ISSUE THREAD

**Issue by distantcam** [Fody/PropertyChanged#113]
PropertyChanged didn't add itself to `fodyweavers.xml` but PropertyChanging did.

I suspect the magic line that made PropertyChanging work was https://github.com/Fody/PropertyChanging/blob/master/Nuget/install.ps1#L84

**Comment by distantcam** [comment]
Also, why not swap to using xdt files like costura does?

**Comment by distantcam** [comment]
I've now had this happen to me in VS2013 as well.

**Comment by SimonCropp** [comment]
OK send me a PR
