### ISSUE TITLE
Update IsChanged when INotifyPropertyChanged properties change

### ISSUE THREAD

**Issue by engenb** [Fody/PropertyChanged#114]
This project is going to dramatically simplify some projects I'm working on, so thanks for that!  The only requirement of mine this project doesn't fulfill is for models to be ```IsChanged``` when property types implementing ```INotifyPropertyChanged``` change.

It'd be great if there was a config option like ```DeepNotify = "true|false"``` to inject code which would listen to property types that implement ```INotifyPropertyChanged```.  I often have a need to consider a model or viewmodel as "changed/dirty" if anything in its object graph has changed.

For example, for types Parent and Child that both implement INotifyPropertyChanged:
```C#
public class Parent : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    public bool IsChanged { get; set; }

    public Child Child { get; set; }

    //...other properties etc.
}
public class Child : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    //...other properties etc.
}
```
would ideally become something like
```C#
public class Parent : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    //PropertyChanged.Fody works its normal magic with this prop
    public bool IsChanged { get; set; }

    private Child child;
    public Child Child
    {
        get { return child; }
        set
        {
            UnregisterDeepListener(child);

            //PropertyChanged.Fody does normal equality check, interceptor, etc.
            child = value;
                
            RegisterDeepListener(child);
        }
    }

    private void UnregisterDeepListener(INotifyPropertyChanged iNotify)
    {
        if (iNotify != null)
        {
            iNotify.PropertyChanged -= DeepPropertyChanged;
        }
    }

    private void RegisterDeepListener(INotifyPropertyChanged iNotify)
    {
        if (iNotify != null)
        {
            iNotify.PropertyChanged += DeepPropertyChanged;
        }
    }

    private void DeepPropertyChanged(object sender, PropertyChangedEventArgs propertyChangedEventArgs)
    {
        IsChanged = true;
    }
}
```
1. I've considered weaving this in with the BeforeAfter option, but I don't want to require that
2. Not sure if this would be better added to PropertyChanged.Fody, or if this calls for a DeepPropertyChanged.Fody project

Before I dive in, I thought I'd ask if this is an appropriate add to this project, or if it would be better suited as a weaver of its own.

Thanks

**Comment by SimonCropp** [comment]
I think this makes sense to be in a different project. PropertyChanged.Fody is about "helping you implement INotifyPropertyChanged" what you are proposing is "a feature that leveraged INotifyPropertyChanged".  So yeah i think it would be better as its own weaver

**Comment by SimonCropp** [comment]
ok closing this. let me know if you need help spiking a new project

**Comment by mbowles201** [comment]
So is there a new Fody for this?

**Comment by SimonCropp** [comment]
@mbowles201 nope. it is outside the scope of this project
