### ISSUE TITLE
Disable implicit implementations of properties on types implementing INPC

### ISSUE THREAD

**Issue by hakonhc** [Fody/PropertyChanged#116]
Hi,
we're seeing that existing types we have that has INPC implemented automatically gets the properties generated even though we don't have the [ImplementPropertyChanged] attribute on the type. Is there a way to disable this behavior without having to use the [DoNotNotify] attribute - as we don't want to go through the codebase to add this. 

The reason we don't want this to happen is that we have code that is explicitly dealing with INPC and falls over when this gets implemented. 

Thanks!

**Comment by SimonCropp** [comment]
What do you mean by

> we have code that is explicitly dealing with INPC

**Comment by hakonhc** [comment]
I mean that I have a 
 public class Class1 : INotifyPropertyChanged
{
 public int Something { get; set; }
}

and the Something will look like this decompiled:

 public int Something
        {
            get
            {
                return this.<Something>k__BackingField;
            }
            set
            {
                if (this.<Something>k__BackingField == value)
                {
                    return;
                }
                this.<Something>k__BackingField = value;
                this.OnPropertyChanged("Something");
            }
        }

and I have not added [ImplementPropertyChanged]

**Comment by SimonCropp** [comment]
` [ImplementPropertyChanged]` adds `INotifyPropertyChanged` if you dont already have it. otherwise all types that implement `INotifyPropertyChanged`  get processed. So that is all working as designed

**Comment by hakonhc** [comment]
Question is if it is possible to turn of this behavior in any way through configuration? Its just too much of a gamble for us to have using it on our project since we have already "legacy" code doing INPC explicitly and there are properties around in the codebase that shouldn't notify that now starts notifying. Retrofitting something like [DoNotNotify] to avoid this is just too much work. Was hoping to just be able to turn off this behavior.

Happy to look at implementing it and doing a pull request for this, if this is something you'd want configurable.

**Comment by SimonCropp** [comment]
@hakonhc sorry no this it not something you can disable. so you will need to add [DoNotNotify] to all types you want to exclude. If adding this attribute to each class is is too much work then I suggest you continue doing notifications manually. 

And sorry no it is not something I want to be configurable

**Comment by hakonhc** [comment]
OK perhaps something for the docs then. When I read the documentation, my impression of that is that the "magic" only happens when you actually set [ImplementPropertyChanged] and not if you implement INPC interface. Not sure I get why you would want this. If I already have implemented INPC why would I want to have properties raises the propertychanged event?

**Comment by SimonCropp** [comment]
because INPC  is just the event.  So you can implement the interface but not raise the event from properties

**Comment by hakonhc** [comment]
Right, so my problem now is that I have lots of existing code which does not raise the event on certain properties and it breaks my application when it does. And from the doc I can't find any reference to the fact that the PropertyChanged.Fody will do something with my existing code if I don't add [ImplementPropertyChanged]. Just though it should be mentioned somewhere...

**Comment by hakonhc** [comment]
...and thanks for the prompt response :smile:

**Comment by SimonCropp** [comment]
done https://github.com/Fody/PropertyChanged#your-code
