### ISSUE TITLE
ReactiveUI and PropertyChanged

### ISSUE THREAD

**Issue by schjan** [Fody/PropertyChanged#117]
Hello,

it seems that PropertyChanged and PropertyChanging isn't working with ReactiveUI 6.4. When compiling I get the following warning
_Warnung	6	Fody/PropertyChanged: 	Could not find EventInvoker method on type 'RasterControlViewModel'. Possible names are 'raisePropertyChanged, OnPropertyChanged, SetProperty, NotifyOfPropertyChange, RaisePropertyChanged, NotifyPropertyChanged, NotifyChanged, raisePropertyChanged'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Please either correct 'EventInvokerNames' or implement your own EventInvoker on this class. No derived types will be processed. If you want to suppress this message place a [DoNotNotifyAttribute] on RasterControlViewModel._

It doesn't make a difference if I set _EventInvokerNames="raisePropertyChanged"_ or not.

I think the problem is, that _RaisePropertyChanged_ is actually an extension method for IReactiveObject used like
```csharp
this.RaisePropertyChanged("propertyName");
```

**Comment by schjan** [comment]
My current workaround:
```csharp
    public abstract class FodyReactiveObject : ReactiveObject
    {
        protected void PropertyChangedExt([CallerMemberName] string propertyName = null)
        {
            // ReSharper disable once ExplicitCallerInfoArgument
            this.RaisePropertyChanged(propertyName);
        }

        protected void PropertyChangingExt([CallerMemberName] string propertyName = null)
        {
            // ReSharper disable once ExplicitCallerInfoArgument
            this.RaisePropertyChanging(propertyName);
        }
    }
```

**Comment by SimonCropp** [comment]
This is already tracked on the reactive repo https://github.com/reactiveui/ReactiveUI/issues/812. 

So please +1 that
