### ISSUE TITLE
property-specific ischanged property attribute

### ISSUE THREAD

**Issue by jbruening** [Fody/PropertyChanged#119]
basically, a feature for an attribute to mark on an IsChanged-like property that would only be marked as true for the specified properties in the attribute. Example:

```csharp
class Foo
{
  public int Prop1 {get;set;}
  public double Prop2 {get;set;}
  public float Prop3 {get;set;}
  [IsChanged("Prop1", "Prop3")] //only marked as true if prop1 or prop3 are modified
  public bool IsChangedProp1Prop3 {get;set;}
  public bool IsChanged {get;set;}  //normal ischanged property as it works now
}

**Comment by SimonCropp** [comment]
This is too much of an edge case to support. And you achieve this yourself through some fairly trivial code.
