### ISSUE TITLE
IsChanged automagically set

### ISSUE THREAD

**Issue by MihaMarkic** [Fody/PropertyChanged#120]
I've noticed by coincidence that if you have a bool IsChanged property declared then it is set to true automagically when any property changes.
There is nothing wrong with this, the problem is, that this behavior isn't obvious. Unbeknowingly I had an IsChanged property and it was true plenty of times even though my code didn't set it.
So, this feature should really be at least visibly documented, or better, it should be attribute driven i.e. using TrackChangedAttribute (or any other name).

**Comment by SimonCropp** [comment]
Isnt this enough https://github.com/Fody/PropertyChanged/wiki/ImplementingAnIsChangedFlag

**Comment by distantcam** [comment]
@SimonCropp other way around. The IsChanged property changed unexpectedly because @MihaMarkic wasn't aware of that feature.

The problem with changing this from "always-on" to "opt-in" is that it will break existing projects. I'm not sure how @SimonCropp feels about this but given how little it comes up I'd lean towards leaving it.

**Comment by MihaMarkic** [comment]
@SimonCropp That's enough but it isn't all that obvious. I've been using plugin for quite some time and could be that I've forgotten about that chapter (until recently that is) and I am quite sure 90% of your users aren't aware of this (I made that number up, obviously). So, I'd put a big warning on front page at least - that's what most users read.

@distantcam Sure, I wasn't aware (probably forgot about it) and probably most users aren't aware as well. And that's a problem that might bite you in specific cases.

The thing is that I wouldn't expect this behavior from PropertyChanged plugin and thus opt-in makes much more sense to me. That would give you an option of arbitrary property name as well. As per breaking changes by switching to opt-in, that would be a problem indeed. (post) Compile time warnings/errors could be used if you switch to opt-in.

**Comment by SimonCropp** [comment]
> I'd put a big warning on front page at least - that's what most users read. 

Unfortunately this is just one of the many conventions that this project uses. For example it is no different from [On_PropertyName_Changed](https://github.com/Fody/PropertyChanged/wiki/On_PropertyName_Changed),  [PropertyDependencies](https://github.com/Fody/PropertyChanged/wiki/PropertyDependencies) or [NotificationInterception](https://github.com/Fody/PropertyChanged/wiki/NotificationInterception). In fact almost every feature is done via a convention. 

> The thing is that I wouldn't expect this behavior from PropertyChanged plugin

Um we are ILWeaving here, most people when i have shown them this for the first time either think i am playing some trick or shout "black magic". So in this context "expect behavior" is a matter of perspective.

I think when using ILWeavers people should be aware of the conventions. In this case all those conventions are linked to on the front page. 

So sorry this has caused you issues but I wont be switching to an opt in model.
