### ISSUE TITLE
Using On_Property_Changed event in abstract class

### ISSUE THREAD

**Issue by julesx** [Fody/PropertyChanged#121]
I have a base abstract class that has a property `Favorite`.

I want to do
`       public abstract void OnFavoriteChanged();`

but it doesnt fire in any class inheriting my base.

**Comment by SimonCropp** [comment]
is Favorite abstract?

**Comment by julesx** [comment]
No

**Comment by distantcam** [comment]
@SimonCropp why? https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/OnChangedWalker.cs#L26

**Comment by SimonCropp** [comment]
i suspect that is a copy paste bug
