### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by arteny** [Fody/PropertyChanged#123]
I get exception
System.MissingMethodException was unhandled by user code
  HResult=-2146233069
  Message=Метод не найден: "?". (Method not found: "?". )
  Source=
  StackTrace:
       в SoccerMatchedScrapper.Engine.set_StatusMessage(String value)
       в SoccerMatchedScrapper.Engine..ctor() в \Business\Engine.cs:строка 45
  InnerException: 

For this class:

```	
	[ImplementPropertyChanged]
        public class Engine
	{
		public Engine()
		{
			StatusMessage = " ..."; // here is exception!!!
		}
	
	public string StatusMessage { get; set; }
        ...
       }
```

If remove [ImplementPropertyChanged], there is no exception

**Comment by SimonCropp** [comment]
can you upload a repro somewhere?

**Comment by arteny** [comment]
Sorry, what is repro?

**Comment by SimonCropp** [comment]
a fully contained solution that "reproduces" the problem. you can place this in a github repository or share it on something like dropbox

**Comment by arteny** [comment]
I found code part which cause of this error, it is because this property in class:
		public static bool IsChanged { get; set; }

here is all code:
```
using PropertyChanged;

namespace MissingMethodExceptionFodyTest
{
	[ImplementPropertyChanged]
	public class Engine
	{
		public Engine()
		{
			StatusMessage = "...";
		}

		public string StatusMessage { get; set; }
		public static bool IsChanged { get; set; }
	}
}
```
In main class just call constructor:
public Engine Engine = new Engine();

**Comment by SimonCropp** [comment]
change IsChanged  to non static

**Comment by arteny** [comment]
@SimonCropp, of course when the cause was found, I found workaroun like rename the variable, but I think it will be more perfect if this can be corrected in library implementation (IsCanged static bool variable existence).

**Comment by SimonCropp** [comment]
in the next version an error will be thrown for that case

**Comment by arteny** [comment]
@SimonCropp :thumbsup:
