### ISSUE TITLE
Overriden instance property has an invalid comparison injected, causing the base to never be updated.

### ISSUE THREAD

**Issue by roflkins** [Fody/PropertyChanged#124]
When compiling an object whose parent has a virtual property {Range} that is overridden, yet still uses the parent object's value, an invalid comparison is injected that compares the new value of the property incorrectly to a field mentioned inside the getter of the property. This causes certain changes to never fall through to the parent.

This excerpt of original code that made this issue for me:
```
private bool stateBeforeBlink = false;
public override double Range
        {
            get
            {
                if (Blinking)
                    return stateBeforeBlink;
                return base.Range;
            }
            set
            {
                base.Range = value;
            }
        }
```

Which reverse compiles to:
```
  public override double Range
        {
            get
            {
                return (!this.Blinking ? base.Range : this.stateBeforeBlink);
            }
            set
            {
                if (this.stateBeforeBlink == value)
                {
                    return;
                }
                base.Range = value;
                this.OnPropertyChanged("Range");
            }
        }
```
The  `if (this.stateBeforeBlink == value)`, should not be included since it is private and all other methods that change that private field were injected with the correct OnPropertyChanged addition. It's important to note that changing the private field to a private property, solved this particular issue.

Thank you so much for this amazing plugin - it has been a life saver so many times.

**Comment by SimonCropp** [comment]
@roflkins want to have a go at submitting a Pull Request for this one?

**Comment by SimonCropp** [comment]
closing this one as not worth fixing. you should try to avoid using overrides in your binding models. a flatter binding model with less inheritance will cause you less pain in the long run.

if you ever get around to a PR i will accept it.
