### ISSUE TITLE
Is PropertyChanged automatically disposed? 

### ISSUE THREAD

**Issue by help-14** [Fody/PropertyChanged#129]
Hi guys, in my project I'm using `PropertyChanged` for almost every model, but my app's facing some memory issues. After discussing with a support person from Microsoft, I was told that many items generated by `PropertyChanged` prevent the models from being disposed completely. Here is a screenshot:
 
![Example](http://i.imgur.com/qe35kcC.png)

Anyone encountered this problem before?

**Comment by SimonCropp** [comment]
This is not really a question related to propertychanged.fody. Since if u manually implemented it u would have the same problem.

Suggest your raise this on stackoverlow
