### ISSUE TITLE
Raise PropertyChanged on behalf of contained item

### ISSUE THREAD

**Issue by MendelMonteiro** [Fody/PropertyChanged#132]
Feature requst: e.g.:

```csharp
class Holder 
{
    private Inner _inner = new Inner();
    public int SomeProp
    {
        get { return _inner.SomeProp; }
    }
}
```

Should raise "SomeProp" when _inner.SomeProp is modified (assuming it raisess NotifyPropertyChanged correctly).

**Comment by SimonCropp** [comment]
@MendelMonteiro sorry but bubbling notification for nested properties it not within the scope of this project. There is also significant complexity around reference tracking, collections and circular references.
