### ISSUE TITLE
Windows 10 Universal App

### ISSUE THREAD

**Issue by SebastianStehle** [Fody/PropertyChanged#134]
Hi, I tried it with Windows 10 Universal App. I just followed the tutorial, tried some older versions and also added the Fody NuGet Package.

I also added a FodyWeaver.xml file from another project, but it doesnt work. The resulting Assembly does not include the property notification calls (check it with ILSpy)

**Comment by SimonCropp** [comment]
can u upload a repro somewhere

**Comment by distantcam** [comment]
Doesn't Windows 10 Universal apps use the new project.json for Nuget instead of packages.config?

**Comment by SebastianStehle** [comment]
Yes, the windows 10 universal apps have the new project.json file since the RTM version.

I dont have access to my windows 10 machine for the next days, but what I did was the following:

1. I created an empty project
2. I added your NuGet package via Package Manager Console
3. I added your sample class from the wiki
4. I compiled everything and had a look to the assembly using ILSpy and JustDecompile

**Comment by jlnostr** [comment]
Even if `PropertyChanged.Fody` is in `project.json` it won't work. ([sample project](https://github.com/wallabag/windows-app/tree/v2))

**project.json:**
```json
{
  "dependencies": {
    "Fody": "1.29.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "Newtonsoft.Json": "7.0.1",
    "PropertyChanged.Fody": "1.50.1",
    "sqlite-net": "1.0.8"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**FodyWeavers.xml:**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PropertyChanged/>
</Weavers>
```

**Comment by SebastianStehle** [comment]
Starting with NuGet 3.1 when using project.json, we are deprecating support for executing the install.ps1/uninstall.ps1 scripts and delivering elements in the /content folder of packages. Installing packages that have these elements will not execute the install.ps1 file and will not copy content to your project. There are several reasons for these decisions:

http://blog.nuget.org/20150729/Introducing-nuget-uwp.html

Might be the reason. Probably it is more complicated to fix everything, can you publish / document a solution how to add fody manually.

**Comment by SebastianStehle** [comment]
Hi, 

I got it working by adding it manually: https://github.com/SebastianStehle/FodyTest

I took the packages from another project add the target to the project file and fixed some paths and now it is running well without NuGet

**Comment by SimonCropp** [comment]
please try https://www.nuget.org/packages/Fody/1.29.1-beta2 and https://www.nuget.org/packages/PropertyChanged.Fody/1.50.2-beta2

**Comment by SebastianStehle** [comment]
Doesnt work. The FodyWeavers.xml has not been added.

**Comment by jlnostr** [comment]
Even if you add it, you got some errors.

FodyWeavers.xml:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PropertyChanged/>
</Weavers>
```

> Detected a PropertyChanged.dll in 'D:\Dokumente\Visual Studio 2015\Projects\windows-app\src\wallabag.Universal\bin\x86\Debug\'. This is a reference only file and should not be deployed. Set the reference to not be copied to the output directory. You may also need to manually add '<PropertyChanged />' into your FodyWeavers.xml. See https://github.com/Fody/Fody/wiki/SampleUsage

Is there a way to fix this error? I got it even on a new project :worried:
