### ISSUE TITLE
PropertyChanged not working with Compiled Bindings

### ISSUE THREAD

**Issue by nightworks** [Fody/PropertyChanged#138]
The PropertyChanged addin is not working in combination with compiled bindings (Windows 10 Universal Apps)

I've created a small example project to demonstrate the problem (requires Windows 10 and Windows 10 SDK). It contains two projects, one with manual INotifyPropertyChanged implementation one using Fody PropertyChanged, only the manual one is working as expected:
https://github.com/nightworks/PropertyChangedCompiledBindings

**Comment by igorkulman** [comment]
Any news on this? I am also having problems with compiled bindings in certain situations.

**Comment by SimonCropp** [comment]
ATM i cant even debug that project

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error : DEP6200 : Bootstrapping 'Device' failed. Device cannot be found. Deployment failed because no Windows Phone was detected. Make sure a phone is connected and powered on.	App1			

```
any ideas?

**Comment by igorkulman** [comment]
Try the emulator. Deploying to Windows 10 devices is still really buggy.

**Comment by distantcam** [comment]
Isn't this just a problem with `ImplementPropertyChanged` not being compatible with compiled bindings? 

My understanding is that the XAML compiler detects if a class implements `INotifyPropertyChanged` and if so adds the binding in code, but since the `INotifyPropertyChanged` is added by Fody after the XAML compiler the compiled binding code isn't added.

What happens if you manually implement `INotifyPropertyChanged` but still use PropertyChanged.Fody and automatic properties?

**Comment by nightworks** [comment]
Yes, manually implementing `INotifyPropertyChanged` works. (I actually figured this out some time ago but forgot to mention it here).
Would it be possible to move the fody code generation before the XAML compiler to make this workaround unnecessary?

@SimonCropp did you select your local machine as deploy target? (I think the default is Windows Phone)

**Comment by SimonCropp** [comment]
my local machine does not show up. i am running win10, i have all the VS bits installed. i even did a VS repair. so unless someone wants to help me debug further i would appreciate if anyone can produce a PR for this.  If not i will have to put it on hold till i rebuild my machine next

**Comment by SimonCropp** [comment]
@distantcam 

> but since the INotifyPropertyChanged is added by Fody after the XAML compiler the compiled binding code isn't added.

i checked and fody is running before the xaml task

**Comment by SimonCropp** [comment]
@distantcam ok i was mistaken

So it seems the xaml compilation is actually done before the compile. it does this with string concatenation on the raw .cs files. as such this will never work with fody. 

so unfortunately i have to close as wont fix
