### ISSUE TITLE
Property assignment doesn't work anymore

### ISSUE THREAD

**Issue by hcd** [Fody/PropertyChanged#139]
Hello,

In my solution I have a strange issue with the notification, but I can't reproduce it in a simple repro case.

My viewmodel layer consists of a hierarchy of viewmodels, with 1 `ViewModelBase` (inheriting from Caliburn's Screen base class) for all viewmodels
I have put the `[ImplementPropertyChanged]` on this ViewModelBase, so I don't have to put it anywhere else.
Now I have a `class EditViewModelBase<T> : ViewModelBase where T is IEntity` that has a property  `public T Entity {get;set;}`
Then I have a bunch of xxxEditViewModels for all types of IEntity's. Here is where the issue is:
if in such a derived viewmodel I want to set the property Entity to a new value, I first have to set it to null and then the new value or it won't take it.
And by "won't take it' I mean not only the notification won't work, the property assignment doesn't even work ... it's like it's just ignored ! 
It's "fixed" by setting Entity = null just before it. It has to be set to null, setting it twice to the new value doesn't work.

For instance, this code where I set the entity to a newer entity with a different timestamp : 

    Debug.WriteLine(string.Format("OldEntity: {0} / NewEntity : {1} ", Entity.GetType(), newEntity.GetType()));
    Debug.WriteLine(string.Format("Objects are equal ? : {0} ", object.ReferenceEquals(Entity, newEntity)));
    //try setting it multiple times
    Debug.WriteLine(string.Format("OldEntity: {0} / NewEntity : {1} ", Entity.ActualTimestamp, newEntity.ActualTimestamp));
    Entity = newEntity;
    Debug.WriteLine(string.Format("OldEntity: {0} / NewEntity : {1} ", Entity.ActualTimestamp, newEntity.ActualTimestamp));
    Entity = newEntity;
    Debug.WriteLine(string.Format("OldEntity: {0} / NewEntity : {1} ", Entity.ActualTimestamp, newEntity.ActualTimestamp));
    Entity = newEntity;
    Debug.WriteLine(string.Format("OldEntity: {0} / NewEntity : {1} ", Entity.ActualTimestamp, newEntity.ActualTimestamp));
    Entity = null;
    Entity = newEntity;
    Debug.WriteLine(string.Format("OldEntity: {0} / NewEntity : {1} ", Entity.ActualTimestamp, newEntity.ActualTimestamp)); 
    await Save();

In the debugger output during running in debug mode :

    OldEntity: EntityClasses.SampleEntity / NewEntity : EntityClasses.SampleEntity 
    Objects are equal ? : False 
    OldEntity: 2036 / NewEntity : 2037 
    OldEntity: 2036 / NewEntity : 2037 
    OldEntity: 2036 / NewEntity : 2037 
    OldEntity: 2036 / NewEntity : 2037 
    System.Windows.Data Error: 17 : Cannot get 'Item[]' value (type 'SampleDescriptionEntity') from     'SampleDescriptions' (type 'EntityCollection`1'). BindingExpression:Path=Entity.SampleDescriptions[0]; DataItem='SampleEditViewModel' (HashCode=27415277); target element is 'TextBox' (Name=''); target property is 'Text' (type 'String') ArgumentOutOfRangeException:'System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
    Parameter name: index'
    OldEntity: 2037 / NewEntity : 2037 

The binding error is because I have set the Entity to null, it triggers the notification and ofcourse the bindings in my XAML fail - no problem.
But as you see, I'm trying to set the property 3 times, and only when I first set it to null, it picks it up.

If I change the property to : 

	private T _entity;

        [DoNotNotify]
        public T Entity
        {
            get { return _entity; }
            set { _entity = value; NotifyOfPropertyChange(()=>Entity); }
        }

Then it works as expected

I've tried quickly slapping up a repro solution, but as I said, I can't reproduce it ..can you give me some pointers on how I could debug this or should start looking ?

**Comment by hcd** [comment]
Ok, I have compiled different versions of my DLL with & without fody, and looked at the generated code with Reflector. 
The issue I'm having is  that there is an Object.Equals check before setting the property and not an object.ReferenceEquals. In my case, I'm cloning an entity and annotating it with the IDataErrorInfo infrasturcture to show validation errors in a screen. But functionally, the object.Equals it still correct, the entities still hold the same information. (and that's probably how Equals() is implemented in the base entity classes of the ORM I'm using)  althought they're different objects.

**Comment by distantcam** [comment]
You could try turning off equality checking for that property by adding the `[DoNotCheckEquality]` attribute.

https://github.com/Fody/PropertyChanged/wiki/EqualityChecking

**Comment by hcd** [comment]
Sweet, it works :) Thnx !
