### ISSUE TITLE
ObservableCollection doesn't update UI

### ISSUE THREAD

**Issue by aline-almeida** [Fody/PropertyChanged#141]
I've got a class decorated with PropertyChanged, let's say MyModel. 
In my ViewModel (also decorated with PropertyChanged) I've got an ObservableCollection<MyModel>. When I change a property of a MyModel item in my collection, the UI (binded ListView) doesn't get updated.
Is there any way to achieve this ?

Thanks

**Comment by SimonCropp** [comment]
Unfortunately no. Observable collections is not a problem domain this project is trying to address

**Comment by aline-almeida** [comment]
Ok, thanks for your quick feedback.

**Comment by dotnetnoobie** [comment]
Make sure you have the attribute on your MyModel class as well and your
ViewModel class

if that does not work you could try using this class from the T10 project

ObservableItemCollection

https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Common/ObservableItemCollection.cs

**Comment by aline-almeida** [comment]
Thanks dotnetnoobie ! 
I do have the attribute on both model and ViewModel and still doesn't work. I'll go with ObservableItemCollection :)
