### ISSUE TITLE
Misdirected OnPropertyChanged

### ISSUE THREAD

**Issue by tomzorz** [Fody/PropertyChanged#142]
Since version 1.50.1 the changes in this commit https://github.com/Fody/PropertyChanged/commit/e102139ad3ada7f614c7788911ad72d270992804 made it so that when there's already an "OnPropertyChanged" method in the class the weaver calls that, and doesn't add a new one. 

This seems to be a fine addition, unless you wanted to handle propertychanged events in your viewmodel class as well, and may have subscribed to the event with the help of ReSharper: it creates the method "private void OnPropertyChanged(object sender, PropertyChangedEventArgs args)" and subscribes to it this way "PropertyChanged += OnPropertyChanged;".

By checking the IL, we saw that all the calls were redirected to this method (which obviously didn't actually raise the INPC event). When we changed the "OnPropertyChanged" method name to a random one, suddenly the weaver did its job properly.

**Comment by SimonCropp** [comment]
how would you suggest this be fixed?

**Comment by tomzorz** [comment]
Not sure if this is possible, but I'd check if the found OnPropChanged method raises the event or not and only using it if it raises it.

**Comment by SimonCropp** [comment]
> but I'd check if the found OnPropChanged method raises the event or not and only using it if it raises it.

That is very difficult to do in a definitive way. the method could call any other method(s). so at best it would be a guess. I prefer to not attempt these things since it make it difficult to document the behavior and difficult for people to reason about

**Comment by tomzorz** [comment]
Yup, that's what I guessed. I don't have a better idea though - maybe add a warning on compilation saying "hey, sure you wanted to do this?"?

**Comment by SimonCropp** [comment]
but the warning would also fire when the dev has done the correct behavior.

**Comment by tomzorz** [comment]
That is true.

**Comment by SimonCropp** [comment]
so close this?

**Comment by tomzorz** [comment]
Well I don't have anything better than the warning, so ok :)

**Comment by distantcam** [comment]
@tomzorz Could you create a separate method for triggering the `INotifyPropertyChanged` event and tell `PropertyChanged` to use that method instead?

https://github.com/Fody/PropertyChanged/wiki/EventInvokerSelectionInjection#event-invoker-name

```
<Weavers>
  <PropertyChanged EventInvokerNames="RaisePropertyChange"/>
</Weavers>
```

```
public virtual void RaisePropertyChange(string propertyName)
{
    // Standard propertychanged implementation
}
```
