### ISSUE TITLE
doesnt work in f# interactive

### ISSUE THREAD

**Issue by fpawel** [Fody/PropertyChanged#143]
In my WPF project I have something like this:
```
open PropertyChanged
[<ImplementPropertyChanged>]
type Type1 =
    {   mutable Name : string
        mutable Value : decimal }
```
, and it works fine when compiled and application is running. But in F# interactive I see that "Type1" is not instance of IPropertyChanged. Is there any way to fix it?

**Comment by SimonCropp** [comment]
is there any way to tie into the MSBuild pipeline in  F# interactive  ?

**Comment by SimonCropp** [comment]
ok i did some research and ATM the answer is "no"
