### ISSUE TITLE
Multiple OnPropertyChanged calls in derived classes

### ISSUE THREAD

**Issue by 7-bit** [Fody/PropertyChanged#144]
Hi,

I have a problem in one of our projects where we are using your Fody extension. If you have a base class for your ViewModels which has the `[ImplementPropertyChanged]` Attribute and a derived class which also derives from `INotifyPropertyChanged` you get multiple class to `OnPropertyChanged()` injected.

A little example:
The result of the following code
```
[ImplementPropertyChanged]
public abstract class ViewModelBase
{
}

public class PersonViewModel : ViewModelBase, INotifyPropertyChanged
{
  public string FamilyName { get; set; }

  public string FullName
  {
    get
    {
      return string.Format("{0} {1}", this.GivenNames, this.FamilyName);
    }
  }

  public string GivenNames { get; set; }

  public event PropertyChangedEventHandler PropertyChanged;
}
```
looks like this:

```
public string FamilyName
{
  get
  {
    return this<FamilyName>k__BackingField;
  }
  set
  {
    if (string.Equals(this.<FamilyName>k__BackingField, value, StringComparison.Ordinal))
      return;
    this.<FamilyName>k__BackingField = value;
    this.OnPropertyChanged("FullName");
    this.OnPropertyChanged("FamilyName");
    this.OnPropertyChanged("FullName");
    this.OnPropertyChanged("FamilyName");
    this.OnPropertyChanged("FullName");
    this.OnPropertyChanged("FamilyName");
    this.OnPropertyChanged("FullName");
    this.OnPropertyChanged("FamilyName");
  }
}
```
I was able to resolve this for the moment by removing the attribute from the base class and adding it to every ViewModel class. Then Fody complains if I also implement `INotifyPropertyChanged`.

I tried to find the right place in your code where the multiple injection of `OnPropertyChanged` happens but had no luck.

Best regards

**Comment by SimonCropp** [comment]
the reason is u r doubling up the INotifyPropertyChanged. 

this
```
[ImplementPropertyChanged]
public abstract class ViewModelBase
```

means u want `INotifyPropertyChanged` injected into ViewModelBase. so it makes no sense for it to be implemened on `PersonViewModel `. 

try this instead 

```
[ImplementPropertyChanged]
public abstract class ViewModelBase
{
}

public class PersonViewModel : ViewModelBase
{
    public string FamilyName { get; set; }

    public string FullName
    {
        get
        {
            return string.Format("{0} {1}", this.GivenNames, this.FamilyName);
        }
    }

    public string GivenNames { get; set; }
}
```
