### ISSUE TITLE
Explicit attributes

### ISSUE THREAD

**Issue by t-denis** [Fody/PropertyChanged#146]
It would be nice to have an option to use more explicit relations instead of implicit conventions.
Otherwise the code becomes too fragile and it can be broken after a minor refactoring.
The build will succeed and you won't even know that you have introduced an issue.

For example, explicitly set dependency between a property and a corresponding On_PropertyName_Changed method.
Something like:
```c#
[ImplementPropertyChanged]
public class Person
{
    public string Name { get; set; }

    [OnChanged(nameof(Name))]
    public void OnNameChanged()
    {
    }
}
```

For now there is an option to manually implement INPC and inside OnPropertyChanged check an argument (using nameof or lambda expression) and call the appropriate method:
```c#
public class Person : INotifyPropertyChanged
{
    public string Name { get; set; }

    public void OnNameChanged()
    {
    }

    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        if (propertyName == nameof(Name))
            OnNameChanged();

        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
```
Also need to stop auto On_PropertyName_Changed injection using
```
<PropertyChanged InjectOnPropertyNameChanged='false'/>
```
otherwise the method will be called twice.
Maybe there is a better solution? Too much boilerplate code.

And what about an option to override global FodyWeavers.xml configuration. Something like:
```c#
[ImplementPropertyChanged(injectOnPropertyNameChanged: InjectionPolicy.Inject)]
```

The other question is what about a special attribute to mark OnPropertyChanged/RaisePropertyChanged/whatever method. Like R# does with its annotations (NotifyPropertyChangedInvocator).

What do you think?

**Comment by distantcam** [comment]
You could introduce the explicit `OnChanged` attribute without having to do anything else. By default methods matching the naming convention will be used but if there's a method with a matching attribute that will be used. The question here is should the method with the attribute be used instead or as well as the method named correctly?

Then you wouldn't need to set any config, and now methods with the attribute are refactor friendly.

> Also need to stop auto On_PropertyName_Changed injection

Do you mean stop automatically using methods with the correct name? I'm not sure that's needed.

**Comment by t-denis** [comment]
>Do you mean stop automatically using methods with the correct name? I'm not sure that's needed.

Looks like there is a misunderstanding. I'm not talking about changing the default behavior, I'm talking just about the provided sample. In my case I have to change xml, otherwise the method OnNameChanged will be called twice (by naming convention and by explicit call). And I need to be sure that the method will be called even if the property (or method) will be renamed, that`s why I call it explicitly. Otherwise a support of large classes can easily become a nightmare.

Fortunately changing xml is not a problem.

**Comment by t-denis** [comment]
> The question here is should the method with the attribute be used instead or as well as the method named correctly?

Good question. Need to avoid confusion somehow.

**Comment by t-denis** [comment]
Need advice. Which one is better?

```c#
[ImplementPropertyChanged]
public class Person
{
    [OnChanged(nameof(OnNameChanged))]
    public string FirstName { get; set; }

    [OnChanged(nameof(OnNameChanged))]
    public string LastName { get; set; }

    public void OnNameChanged()
    {
    }
}
```

```c#
[ImplementPropertyChanged]
public class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    [OnPropertyChanged(nameof(FirstName), nameof(LastName))]
    public void OnNameChanged()
    {
    }
}
```

**Comment by t-denis** [comment]
Since there could be both
```c#
public void OnNameChanged() { }
public void OnNameChanged(object before, object after) { }
```
methods, so the first approach requires introducing some hints (call NoArg, call BeforeAfter, call everything).

**Comment by SimonCropp** [comment]
Have u considered doing this as a new fody addin. Since what u r proposing is on the edge of what should be in this project

**Comment by t-denis** [comment]
You are right, that's why I'am asking your opinion in the original message. To understand if you would like to extend the project that way. I provided a PR to consider. Not too much changes and no side-effects for existing users.

**Comment by SimonCropp** [comment]
> Not too much changes and no side-effects for existing users.

perhaps but 500+  more lines

**Comment by t-denis** [comment]
Well, it's up to me to offer, it's up to you to reject that offer :)

**Comment by SimonCropp** [comment]
ok. https://github.com/Fody/PropertyChanged/pull/147 is simply too much more code. it also really doesnt have anything to do with "injecting INotifyPropertyChanged". and yes i realize that nether does the current On_PropertyName_Changed feature, and i will consider dropping this in a future breaking version.

I suggest you write your own weaver that performs your specific task
