### ISSUE TITLE
Flag enums and Fody/PropetyChanged

### ISSUE THREAD

**Issue by 537mfb** [Fody/PropertyChanged#149]
Can this handle flag enums in any way?

i have a flag enum that i need to bind to checkboxes (one per bit) - Is this handled properly?

**Comment by SimonCropp** [comment]
> i have a flag enum that i need to bind to checkboxes (one per bit) - Is this handled properly?

I have no idea what you would consider "proper" so i cant answer that.

> Can this handle flag enums in any way?

How would u expect it to be handled

Perhaps illustrate what you want in a unit test?

**Comment by 537mfb** [comment]
I've more or less wipped out a working solution of my own for this, but i meant if there's a wait to have a property sort of like this (made up code)

`[FlagProperty(Property=MyFlagProperty, Flag=MyEnum.ThirdFlag)]
public MyEnum ThirdFlag {get;set;}`

and this would generate:

`public MyEnum ThirdFlag {
     get { return MyFlagProperty.HasFlag(MyEnum.ThirdFlag): }
     set {
          if (MyFlagProperty.HasFlag(MyEnum.ThirdFlag) != value) {
               if (value)
                  MyProperty |= MyEnum.ThirdFlag;
              else
                 MyProperty &= MyEnum.ThirdFlag;
             OnPropertyChanged();
          }
     }
}`

Or something like that

**Comment by SimonCropp** [comment]
sorry i think this is out of the scope of this project
