### ISSUE TITLE
virtual PropertyChangedEventHandler

### ISSUE THREAD

**Issue by cataliz3er** [Fody/PropertyChanged#151]
I'm trying to use PropertyChanged.Fody in conjunction with NHibernate, but it fails because the PropertyChangedEventHandler is not virtual. Any ideas on how to make it virtual?

**Comment by SimonCropp** [comment]
why would an event handler need to be virtual ?

**Comment by cataliz3er** [comment]
NHibernate needs it to be virtual in order to create its proxies. Otherwise, I get the following:

The following types may not be used as proxies:
DomainModel.Client: method add_PropertyChanged should be 'public/protected virtual' or 'protected internal virtual'
DomainModel.Client: method remove_PropertyChanged should be 'public/protected virtual' or 'protected internal virtual'

This works:
```C#
public virtual event PropertyChangedEventHandler PropertyChanged;
public virtual void NotifyPropertyChanged(string info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }
```

**Comment by SimonCropp** [comment]
doesnt this only happen if u r attempting to map that property to nhibernate? which makes no sense since u cant persist an event.

**Comment by cataliz3er** [comment]
Apparently it does not happen only when you map a property. I know it makes no sense, but the fact is that if you have an event in the class that you're trying to map, you need to make it virtual whether or not you map it. It's just the way NHibernate seems to work. If you don't declare it as virtual, you get an exception that clearly tells you that it has to be virtual:
The following types may not be used as proxies:DomainModel.Comanda: method add_PropertyChanged should be 'public/protected virtual' or 'protected internal virtual'DomainModel.Comanda: method remove_PropertyChanged should be 'public/protected virtual' or 'protected internal virtual'
Once I declare the event as virtual, everything works. 

    On Monday, February 1, 2016 11:31 AM, Simon Cropp <notifications@github.com> wrote:
 

 doesnt this only happen if u r attempting to map that property to nhibernate? which makes no sense since u cant persist an event.—

**Comment by SimonCropp** [comment]
how about sending me a PR that makes them virtual?

**Comment by SimonCropp** [comment]
bump

**Comment by pkunze** [comment]
Hey, I am facing exactly the same Problem. I would also love to contribute the mentioned PR, but from browsing your code hier in GitHub, it seems to me as if this would have already been implemented? 

see https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/InterfaceInjector.cs#L37

Or would that be the wrong place to look?

**Comment by distantcam** [comment]
@pkunze No that's the right place to look.

I believe this line is the problem https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/InterfaceInjector.cs#L34 it needs to be taken out.

**Comment by pasqualedante** [comment]
I don't understand if this ticket is closed as fixed or the reply is that Fody.PropertyChanged in conjunction with NH could be used only in 
`public virtual event PropertyChangedEventHandler PropertyChanged;`
way and not with data annotation 
`[ImplementPropertyChanged]`

According with [Ms MSDN](https://msdn.microsoft.com/en-us/library/system.reflection.methodattributes(v=vs.110).aspx), as pointed by  @distantcam, MethodAttributes.Final should be the solution.
