### ISSUE TITLE
Support for Template 10?

### ISSUE THREAD

**Issue by JerryNixon** [Fody/PropertyChanged#153]
Can there be support for Template 10 for Windows UWP apps?

https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Mvvm/IBindable.cs

**Comment by dotnetnoobie** [comment]
Yes I use this in UWP apps, 

the trick is you need to manually add the FodyWeavers.xml file to the root of your UWP project

<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PropertyChanged/>
</Weavers>

I just add it to my projects via NuGet or just add it directly in the project.json file
"PropertyChanged.Fody": "1.50.3"

**Comment by SimonCropp** [comment]
@JerryNixon as @dotnetnoobie suggested you need to do some manual work to get fody working for UWP projects. have a look at this https://github.com/Fody/UniversalAppSample. to get it working for template 10 i would assume https://github.com/Fody/PropertyChanged/wiki/Options#eventinvokernames would work for you. let me know how you go
