### ISSUE TITLE
How is ImplementingAnIsChangedFlag used

### ISSUE THREAD

**Issue by escamoteur** [Fody/PropertyChanged#154]
Hi,
on tge Wiki Page ImplementingAnIsChangedFlag is mentioned, but no information on it. It sounds really interesting.
Thanks
Thomas

**Comment by stecydube** [comment]
The link from the page does nothing, however the same link from the right column does.

**Comment by escamoteur** [comment]
Thanks. But how does IsChanged know which property it should monitor?

Also can it be used together with [ImplementPropertyChanged] because in the Wiki 

```
public class Person : INotifyPropertyChanged
{
  public string Name { get; set; }
  public event PropertyChangedEventHandler PropertyChanged;
  public bool IsChanged { get; set; }
}
```
PropertyChangedEventHandler PropertyChanged;
is defined "manually"

**Comment by SimonCropp** [comment]
sp the doco is here https://github.com/Fody/PropertyChanged/wiki/Implementing-An-IsChanged-Flag and i have fixed the link on the home page.

The property i looks for is hard coded to `IsChanged`

and yes it should work OOTB with  ` [ImplementPropertyChanged]`

**Comment by escamoteur** [comment]
@SimonCropp Thanks. What was not clear to me was that it reacts to any property change in the class , not on a specific one. Perhaps you can clearify this in the Wiki.

**Comment by SimonCropp** [comment]
@escamoteur sounds good. what new content do you suggest?
