### ISSUE TITLE
DependsOn attribute does not work for properties in base class.

### ISSUE THREAD

**Issue by robertbaker** [Fody/PropertyChanged#156]
Is there a way to support `[DependsOn]`to a property in an inherited class?

Also would like a way to have IsChanged defined in the derived class and also be set to true for base class property changes.

**Comment by SimonCropp** [comment]
can u give me a before and after weaving of how u would expect this to work?

**Comment by robertbaker** [comment]
I was thinking about that after I created the issue. It would be practically impossible. I guess you could somehow detect the property does not exist in the same class, find it in the derived class and copy it, override with the needed calls.

**Comment by SimonCropp** [comment]
Yeah I think what u are asking for would be leaking child implementation details into the parent. Something u prob want to avoid. If u can share some example models I might be able to show u an alternative implementation

**Comment by SimonCropp** [comment]
bump
