### ISSUE TITLE
Custom setter

### ISSUE THREAD

**Issue by fcogutierrez** [Fody/PropertyChanged#157]
How can I put extra code in the setter, for example a call to RecalculateData() method?

**Comment by SimonCropp** [comment]
you mean like this https://github.com/Fody/PropertyChanged/blob/master/TestAssemblies/AssemblyToProcess/ClassWithLogicInSet.cs  ?

**Comment by SimonCropp** [comment]
does the above approach work for you?

**Comment by 1ucas** [comment]
Yes. But at a class using the [ImplementPropertyChanged].

**Comment by dfoulk** [comment]
I would also like to know how/if we can do this. I am working it out as we speak, but some guidance or advice would be appreciated!

**Comment by SimonCropp** [comment]
@dfoulk i am not sure what guidance or advice u are after. yes custom code is supported in the set

**Comment by dfoulk** [comment]
@SimonCropp - I believe I have sorted this out. I was trying to learn how to use the `[AddINotifyPropertyChangedInterface]` on a class, but in that same class use a backing store in a property's setter. The link that you presented to the OP did not contain this attribute on the class...

I wanted to make sure that my adding and using a backing store wouldn't cause anything funky when using this package. I was just being overly cautious as I was implementing this change late in a sprint.

Thank you for getting back to me, I'm all set!

**Comment by SimonCropp** [comment]
glad u got it worked out
