### ISSUE TITLE
OnPropertyChanged(string propertyName, object after)

### ISSUE THREAD

**Issue by mortengjesing** [Fody/PropertyChanged#158]
Hi,

It would be very useful to us if a implementation of OnPropertyChanged with only an after value (and not a before).

The reason is that the before value is using the get method of the property, and we have multiple properties that lasy loads within the get method - and we want to avoid this.

We still wants to be able to track what the property is changed to.

Another alternative could be able to specify where to get the before value (field name)

Best regards

Morten

**Comment by SimonCropp** [comment]
why r u lazy loading in a view model? isnt that kind of out of scope for what a view model should be doing?

**Comment by mortenmercell** [comment]
We find our model very effective for multible resons, faster coding, effektive caching fx. We found your framework just what we need to improve our framework, but we need it to be a little more flexible.

**Comment by mortenmercell** [comment]
I have looked more into how the framework works, and discovered that the Equals check is done with the field but the before and after value is done via get. This seem inconsistent to me.

`
private string _test;

		public string Test
		{
			get
			{
				if (_test == null)
				{
					_test = "default";
				}

				return _test;
			}

			set { _test = value; }
		}
`

is compiled into

`
private string _test;

    public string Test
    {
      get
      {
        if (this._test == null)
          this._test = "default";
        return this._test;
      }
      set
      {
        if (string.Equals(this._test, value, StringComparison.Ordinal))
          return;
        object before = (object) this.Test;
        this._test = value;
        object after = (object) this.Test;
        this.OnPropertyChanged("Test", before, after);
      }
    }
`

This means that sometimes it uses get and other times it uses the field to get current value.

**Comment by SimonCropp** [comment]
The equals is meant to be guarding against uncecessary notifying if the backing field has not changed. The before after feature is meant to the the external representation of the property hcen using the get

**Comment by SimonCropp** [comment]
Re the OnPropertyChanged(string propertyName, object after)... Feel free to submit a pr
