### ISSUE TITLE
Error because of redundant INotifyPropertyChanged implementation

### ISSUE THREAD

**Issue by thomasjoscht** [Fody/PropertyChanged#159]
Hey, how can I mix ImplementPropertyChanged Attribute with custom INotifyPropertyChanged implementation? 

I'm using Fody in multiple layers of my application. I've a custom implementation of INotifyPropertyChanged in some of my base classes too. This called ValidatableModel and has lot of additionally functionality like validation, notify errors, and so on. Sometimes I would define simple objects using auto property and won't call Notify on each property. This is the place of ImplementPropertyChanged attribute. But I would/must also call sometime my Notify method. This is only possible in case marking class with ImplementPropertyChanged and also inherit from my ValidatableModel. This works in case my ValidatableModel is defined in a different assembly.

But using both in one assemby this will cause an build error "Fody: The type '...' already implements INotifyPropertyChanged so [ImplementPropertyChanged] is redundant.". Why does this happen? Is it possible to suppress this?

**Comment by SimonCropp** [comment]
Can u upload a repro that illustrates your problem

**Comment by thomasjoscht** [comment]
That's not easily possible. Let me try to explain it a little bit further in a minimum example:

I have two assemblies. On is called Common and one is called App. The Common contains a class ValidatableModel which implements INotifyPropertyChanged (and some other stuff). The App contains a class TestModel which inherits form ValidatableModel and also annotats [ImplementPropertyChanged] (The reason for using both is that I will auto property of fody and also my custom validation stuff). The solution will build and it works. No problem!

Moving the TestModel class from assembly App to Common will raise the build error explained above. The class TestModel could not inherit from a class which implements INotifyPropertyChanged and annotate [ImplementPropertyChanged] at same time (which works in case TestModel is in a different assembly as the base class ValidatableModel).

Why this happen? I know this library supports other toolkits with there own Implementation of INotifyPropertyChanged (which is same case for me and my implementation of it). But I'm forced to separate my implementation in a different assembly.

**Comment by SimonCropp** [comment]
So the ImplementPropertyChanged method is only for injecting the property changed event. It does not in any way effect if notification calls are injected into properties. So for any child class, of a base class that already implements inotifypropertychanged, notification calls will be injected and you dont need the attribute

**Comment by thomasjoscht** [comment]
Thank's a lot. That's a big point I have missed so far. My suggestion was that ImplementPropertyChanged attribute is necessary for marking class for injection. But the only thing necessary for Fody to inject PropertyChanged notifications is implementing INotifyPropertyChanged interface.

But this brings me to two further things: 

First: Why does Fody only produce a build error if the code is in same assembly? I think the code in TypeNodeBuilder should produce this error everytime so a misusing is no longer possible:
```c#
if (HierarchyImplementsINotify(node.TypeDefinition))
{
   throw new WeavingException($"The type '{node.TypeDefinition.FullName}' already implements INotifyPropertyChanged so [ImplementPropertyChanged] is redundant.");
}
```
Second: In my code I'm using a method for setting values by ref and Notify in one step. It looks like:
```c#
public string Description
{
   get { return _description; }
   set { SetAndRaiseIfChanged(ref _description, value); }
}
```
This is very short and easy to use. Sometimes in big nodels I would avoid private fields and use auto properties. This is where Fody comes in. But using Fody means that EVERY CLASS will be handled. So my self notification code will be changed to this:
```c#
public string Description
{
   get
   {
      return this._description;
   }
   set
   {
      if (string.Equals(this._description, value, StringComparison.Ordinal))
      {
         return;
      }
      base.SetAndRaiseIfChanged<string>(ref this._description, value, "Description");
      this.NotifyOfPropertyChange("Description");
   }
}
```
How can I avoid this? I would only inject notification in some classes (f.e. marked by an attribute) and not in all (because they will produce this mess of code).

**Comment by SimonCropp** [comment]
> Why does Fody only produce a build error if the code is in same assembly

because the weaver removes that attribute on weaving and hence it is not inherited

> Second: In my code I'm using a method for setting values by ref and notify in one step. How can I avoid this? I would only inject notification in some classes (f.e. marked by an attribute) and not in all (because they will produce this mess of code).

try this 
```
<?xml version="1.0" encoding="utf-8"?>
<Weavers VerifyAssembly="true">
  <PropertyChanged  EventInvokerNames="SetAndRaiseIfChanged"/>
</Weavers>
```

**Comment by SimonCropp** [comment]
ping me if it doenst work for u
