### ISSUE TITLE
Doesn't use custom operator ==

### ISSUE THREAD

**Issue by MihaMarkic** [Fody/PropertyChanged#162]
When a type implements operator ==, setter doesn't use it.

To repro, create a type that implements operator == and use it as property type. It won't be used looking at IL code (and behavior). I think it'd make sense to use it (when available).
Should I try to create a pull request (seems quite complicated)?

**Comment by distantcam** [comment]
It's recommended when overloading the equality operator (==) that you also override the `Object.Equals` method with the same code. See [Equality Operators](https://msdn.microsoft.com/en-us/library/7h9bszxx(v=vs.110).aspx)

Fody PropertyChanged uses the `Object.Equals` comparer.

**Comment by MihaMarkic** [comment]
Hi Cameron,

Is it possible that it uses it only on value types? That would explain it.

**Comment by MihaMarkic** [comment]
I mean I'm seeing this IL:

    L_0015: ldarg.0 
    L_0016: ldarg.1 
    L_0017: stfld class ClassWithCustom==OperatorAndEquality XyClass::someField

**Comment by distantcam** [comment]
Correct, for value types, arrays and enums it uses `==`.

**Comment by MihaMarkic** [comment]
It should be used on reference types as well, shouldn't it?

**Comment by MihaMarkic** [comment]
i.e. in my case I'm using a derived List<T> where I compare items.

**Comment by distantcam** [comment]
No I think Object.Equals is correct here.

`==` is for checking if they are actually equal. For objects that's a reference equal.
`Object.Equal` is for checking if they are effectively equal, even if they are 2 different objects.

**Comment by MihaMarkic** [comment]
== is reference equals only until somebody implements a custom operator. Then it should be used regardless of it is a reference or value type one is comparing.

The problem is that you aren't using object.Equals for reference types...
Does it make sense?

**Comment by MihaMarkic** [comment]
Let me correct the above, not == operator but rather override bool Equals.

**Comment by MihaMarkic** [comment]
For example, when comparing this type
class Tubo2
{
	public override bool Equals(object obj)
	{
		return true;
	}

	public override int GetHashCode()
	{
		return base.GetHashCode();
	}
}

it should always return true. Unless explicitly using ReferenceEquals

**Comment by distantcam** [comment]
If both should be overriden, and both should return the same result, then why does it matter which one is used?

**Comment by MihaMarkic** [comment]
Err, what do you mean by both?
The original question was why isn't object.Equals used on reference types.

**Comment by distantcam** [comment]
Ah, sorry. Well I've given my explanation.

**Comment by MihaMarkic** [comment]
Sorry for me being thick, but I didn't understand why object.Equals (or ==) isn't used on reference types?

**Comment by distantcam** [comment]
Your original comment asked why an overload for == isn't used on a reference type. The answer is because Object.Equals is used to compare reference types, not ==.

**Comment by MihaMarkic** [comment]
Ah, but the problem is that it isn't. Not == nor object.Equals.

**Comment by MihaMarkic** [comment]
But I'll double check, perhaps I read it wrong.

**Comment by MihaMarkic** [comment]
So, when I implement it manually, the op_Inequality is used (!=).
When autoimplemented by Fody, ceq is used (which I believe just compares two values which happen to be references to the two items- reference equals I guess).

**Comment by SimonCropp** [comment]
@MihaMarkic can you illustrate this issue with a failing test in a PR?

**Comment by MihaMarkic** [comment]
Created #164. It looks like the problem is deeper that I thought - it has all to do with properties of generic types.

**Comment by MihaMarkic** [comment]
I've created also tentative fix for the issue (in second commit). All tests are green.
