### ISSUE TITLE
Postsharp and Fody Compatibility

### ISSUE THREAD

**Issue by michalsteyn** [Fody/PropertyChanged#163]
I am using the free edition of PostSharp extensively in a project. I would like to use the PropertyChanged.Fody addin to handle all the PropertyChanged Notifications automatically.

(I know that PostSharp offers a library for this, but it is not free, thus I would like to use Fody)

It appears that when I use both PostSharp and Fody in a project, the debug symbol files goes out of sync with the source code. When I debug a project I can no longer properly step through code. It looks similar to when you attach a debugger in VS to a process where the source code is different than that of the executing binary.

If I disable either PostSharp or Fody, then debugging works immediately again.

Is it possible to use both PostSharp and Fody in the same project? Does this require special / extra configuration?

**Comment by SimonCropp** [comment]
yes it should be possible
@michalsteyn it is most likely cause by one of these two bugs in cecil https://github.com/jbevain/cecil/issues/90 https://github.com/jbevain/cecil/issues/4

not really something i can fix at the fody level. sorry
