### ISSUE TITLE
PropertyChanged and PropertyChanging, calling both

### ISSUE THREAD

**Issue by napocoelho** [Fody/PropertyChanged#169]
- Sorry if here is not the right place to this kind of question. I'm new here and I didn't find better option. =/
- What exactly does when I use both [ImplementPropertyChanging] and     [ImplementPropertyChanged] at the same class?
- I'm afraid if, calling both, will duplicate (unnecessarily) something, like the set to the property's attribute value or something else.

Thx very much!

**Comment by SimonCropp** [comment]
It will implement both INotifyPropertyChanged and INotifyPropertyChanging. To see the result have a look at the result in a decompiler
