### ISSUE TITLE
Alternatively allow Rewriting based on Inclusion instead of Exclusion

### ISSUE THREAD

**Issue by 0x53A** [Fody/PropertyChanged#175]
I want to introduce Fody.PropertyChanged into an existing project.

Currently, that is not possible because it would then rewrite all classes (and I don't really want to mark them all with DoNotNotifyAttribute).

What would you think about adding a new Attribute (maybe named ``DoNotRewriteAllClasses`` or similar) which can be applied at the assembly level?

If this attribute is set, Fody would only rewrite types which have ``ImplementPropertyChangedAttribute`` set.

**Comment by SimonCropp** [comment]
in what cases would you not want notification code injected into INPC classes?

**Comment by 0x53A** [comment]
When I have existing classes with manually implemented INPC

**Comment by SimonCropp** [comment]
those should be detected and skipped

**Comment by 0x53A** [comment]
Okay then there is an issue with the detection. I will try and see if I can find that out ...

**Comment by 0x53A** [comment]
After taking a look at the code, I think my Scenario already works with the existing Attribute ``FilterTypeAttribute``.

I now get an error because the Attribute is not removed after rewriting, but I will open another issue for that.

```
4>------ Build started: Project: LogisticsToolsWpf, Configuration: Release x64 ------
4>    Fody: Fody (version 1.29.4.0) Executing
4>    Fody:   Finished Fody 9ms.
4>  LogisticsToolsWpf -> D:\p4\Precast3\TimPrecast\BuildOutput_Libs\Release\LogisticsToolsWpf\LogisticsToolsWpf.dll
4>  Running Code Analysis...
4>MSBUILD : error : CA0001 : The following error was encountered while reading module 'LogisticsToolsWpf': Could not resolve type reference: [PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]PropertyChanged.FilterTypeAttribute.
4>  Code Analysis Complete -- 1 error(s), 0 warning(s)
========== Build: 3 succeeded, 1 failed, 9 up-to-date, 0 skipped ==========
```
