### ISSUE TITLE
Generates invalid code for VB properties with parameter

### ISSUE THREAD

**Issue by vaughanje** [Fody/PropertyChanged#176]
[WindowsApplication1.zip](https://github.com/Fody/PropertyChanged/files/296267/WindowsApplication1.zip)

If a VB class has a property that takes a parameter, the code generated is invalid and when Set is called, .NET throws an InvalidProgramException.  JustDecompile craps out when I try to open it and decompile it.

I have attached an example

**Comment by vaughanje** [comment]
I noticed that if I put <DoNotCheckEquality> it works.  So something in the equality check is messed up.

**Comment by SimonCropp** [comment]
can u try 1.51.2

**Comment by SimonCropp** [comment]
let me know if the newest version fixes your problem

**Comment by vaughanje** [comment]
The newest version works. Thanks!
