### ISSUE TITLE
Disable PropertyChanged weaving in the base class depends on the derived class

### ISSUE THREAD

**Issue by menmen12** [Fody/PropertyChanged#186]
Hi, 

I'm just starting to implement your great work inside my project and I came accross to a question if it is possible to disable the weaving process that is in my base class from its derived class?

Best Regards,

**Comment by AgentFire** [comment]
If you don't need the `PropertyChanged` attribute on a base class, don't decorate it.

**Comment by MihaMarkic** [comment]
Did you try using [DoNotNotifyAttribute](https://github.com/Fody/PropertyChanged/wiki/Attributes#donotnotifyattribute)?

**Comment by SimonCropp** [comment]
>  is possible to disable the weaving process that is in my base class from its derived class

no this is not supported
