### ISSUE TITLE
NotifyPropertyWeaver 1.52.1.0 fails with Visual Studio 2015

### ISSUE THREAD

**Issue by ravindrank** [Fody/PropertyChanged#187]
- Works fine for the same same VS solution using VS 2013 Update 5
- Fails in 2015 with below:

`NotifyPropertyWeaver (version 1.52.1.0) Executing (Change MessageImportance to get more or less info)
2>MSBUILD : error : NotifyPropertyWeaver: Failed to extract target assembly path from the BuildEngine. 
2>MSBUILD : error : Please raise a bug with the below exception text.
2>MSBUILD : error : The temporary work-around is to change the weaving task as follows 
2>MSBUILD : error : <WeavingTask ... TargetPath="PathToYourAssembly" />
2>MSBUILD : error : Exception details: System.Exception: Could not extract targetBuilderCallback from Microsoft.Build.BackEnd.TaskHost
2>MSBUILD : error :    at BuildEnginePropertyExtractor.GetProjectInstance()
2>MSBUILD : error :    at BuildEnginePropertyExtractor.GetEnvironmentVariable(String key, Boolean throwIfNotFound)
2>MSBUILD : error :    at TargetPathFinder.Execute()
2>      Finished (48ms)`

 I'm not too clear on the Temporary Workaround suggested...
Any suggestions/examples for workaround?

**Comment by SimonCropp** [comment]
what version of fody?

**Comment by ravindrank** [comment]
Hi Simon,

Thanks for your response. Sorry forgot to include it.. 

"Fody" version="1.29.4"

Regards
Ravindran

**Comment by SimonCropp** [comment]
can u upload a repro

**Comment by robcecil** [comment]
Simon, I'm getting the same error as ravindrank. VS2015. Fody 1.29.4.

**Comment by SimonCropp** [comment]
can u upload a repro?

**Comment by SimonCropp** [comment]
closed due to no response
