### ISSUE TITLE
Boxing of value types

### ISSUE THREAD

**Issue by Mikant** [Fody/PropertyChanged#191]
I've recently noticed that regular value types are boxed on equality checks in generated code. This equality check for let's say Byte defaults to object.Equals(object, object) with no reason I can imagine. I know it's a pretty minor impropriety, but it's definitely "non comme il faut". I've just read the code responsible for this behavior, there are 5 cases: string equality checks defaults to string.Compare(string, string, Ordinal), for regular classes a simple ceq instruction is called and so on... and everything's ok... but structs happily see they can be applied to object.Equals and we have what we have.

As far as I can see the case sequence was interrupted after the most recent commit, @distantcam, May 13.

Dear comrades, I beg you to insert a single call to EqualityComparer<T>.Default.Equals(T, T) in PropertyChanged.Fody/EqualityCheckWeaver.cs which will be a completely generic (in all senses) solution for equality checks. It is very fast, simple, and will make the code cleaner.

And thank you for a great job!=)

**Comment by Mikant** [comment]
Moreover, since it previously defaulted to T.Equals(T) and now to object.Equals(object) and there are some people which tend to implement IEquatable<T> on structs and do not override Equals(object) that (100 days ago) change should be considered a bug cause it changes the entire logic.

**Comment by distantcam** [comment]
>  since it previously defaulted to T.Equals(T) and now to object.Equals(object)

@Mikant The new code is `object.Equals(a, b)` which internally calls `a.Equals(b)` but doesn't require using generics, which is what was causing a lot of bugs and complexity before.

Boxing structs and bytes shouldn't be happening. I'll take a look.

**Comment by Mikant** [comment]
> The new code is object.Equals(a, b) which internally calls a.Equals(b)
@distantcam Please consider the following code snippet:
`using System;
using PropertyChanged;

namespace ConsoleApplication1 {
    [ImplementPropertyChanged]
    public class Foo {
        public Baz Bar { get; set; }
    }

    public struct Baz : IEquatable<Baz> {
        public int Qux { get; }

        public Baz(int qux) {
            Qux = qux;
        }

        public bool Equals(Baz other) {
            return Qux == other.Qux;
        }

        // despite of being a must have this code is
        // absent sometimes. it even causes a (omg) warning
        // by default, because of not overriding (mysterious) GetHashCode
        //public override bool Equals(object obj) {
        //    return obj is Baz && Equals((Baz)obj);
        //}
    }
}`

Equals(object) method is missing here because ~~coder was drunk~~ it is generally not needed to use Baz properly with HashSet<T>, Dictionary<T, U> and so on. But your current implementation of equality checks will not take Equals(T) in account and will raise the event. I just think that it is fine to implement .NET code logically compatible with .NET Framework classes.

Equals(object) also causes boxing which is considered a bad practice. And it is very easy to avoid. Moreover the performance of this method is really poor. See test results below.

EqualityComparer.Default.Equals(T, T) is designed to handle all the types, it IS a standard of equality checks for .NET I and I don't see any obstacles on the way to implement it.

@distantcam Should I create a pull request? (with all the type variations available)

Test results:
 Method |        Median |      StdDev |
------- |-------------- |------------ |
  TestA |   467.8108 us |   4.5240 us |
  TestB | 1,374.7547 us |  21.6072 us |
  TestC | 3,279.0837 us | 436.1008 us |

**Comment by distantcam** [comment]
@Mikant I was simply pointing out that the new implementation is not a bug, even if it is slower than using EqualityComparer.

**Comment by Mikant** [comment]
@distantcam Please see this pull request https://github.com/Fody/PropertyChanged/pull/192 All tests are running fine, one minor bug fixed and finally changed equality checks generation. Hope you will find it useful.

**Comment by distantcam** [comment]
@Mikant Using EqualityComparer on basic value types like `int` is 10x slower than using `ceq`, and for nullable types it's 12x slower.

                               Method |         Median |      StdDev |
------------------------------------- |--------------- |------------ |
                              CeqTest |    823.1951 us |   5.7949 us |
                            ECIntTest |  8,268.2902 us |  98.4178 us |
                           ECByteTest |  8,666.4825 us |  39.0743 us |
                    ECNullableIntTest | 10,705.2437 us | 195.2499 us |
 EqualityComparer_StructWithEquatable |  3,845.1063 us |  15.9367 us |
 EqualityComparer_StructWithOverrides |  9,136.2886 us |  43.9837 us |
   EqualityComparer_StructWithNothing | 39,317.2106 us | 634.4013 us |
     ObjectEquals_StructWithEquatable | 36,144.1799 us | 179.9713 us |
     ObjectEquals_StructWithOverrides | 10,064.8269 us | 105.1439 us |
       ObjectEquals_StructWithNothing | 36,137.4984 us | 388.0838 us |

**Comment by cbordeman** [comment]
Please guys, if you don't speed this up one would be kind of crazy to use this package.

**Comment by distantcam** [comment]
@Mikant Another reason not to use EqualityComparer, it's not available in the PCL.

**Comment by distantcam** [comment]
This was done in #197 and can be closed.
