### ISSUE TITLE
Automatic dependent notification not working for iterator property (yield return)

### ISSUE THREAD

**Issue by forbjok** [Fody/PropertyChanged#193]
With this, no property notification will be given for IncludeWorkPlanTypes when either IncludeRules or IncludeSingles change:

``` C#
public bool IncludeRules { get; set; }
public bool IncludeSingles { get; set; }

public IEnumerable<int> IncludeWorkPlanTypes
{
    get
    {
        if (this.IncludeRules)
            yield return (int) WorkPlanRegType.Rule;

        if (this.IncludeSingles)
            yield return (int) WorkPlanRegType.Single;
    }
}
```

...but with this, which functionally does the exact same thing in a slightly less elegant way, it does:

``` C#
public IEnumerable<int> IncludeWorkPlanTypes
{
    get
    {
        var types = new List<int>();

        if (this.IncludeRules)
            types.Add((int) WorkPlanRegType.Rule);

        if (this.IncludeSingles)
            types.Add((int) WorkPlanRegType.Single);

        return types;
    }
}
```

I don't know whether this is a bug, or some sort of technical limitation due to it being somehow impossible to correctly detect it in iterators using yield return, but either way it seems very counter-intuitive that it doesn't work.

**Comment by SimonCropp** [comment]
this is a bug. want to have a go at a PR?

**Comment by navozenko** [comment]
I think this is the right behavior. In the first case, the value of the property never changes, it always returns a reference to the same object in memory. Only content of the collection are changed. Therefore, notification should not occur.
