### ISSUE TITLE
PropertyChangedEventHandler is called without checking its name

### ISSUE THREAD

**Issue by sleschinski** [Fody/PropertyChanged#194]
When a class already has an event with PropertyChangedEventHandler signature, Fody notifies this event instead of the one which it injected. It's arguable whether to have another event with the same signature is a good practice, but the way the situation is handled now is totally confusing. Here is a code sample.

// the class
[ImplementPropertyChanged]
public class Test
{
    public decimal Value { get; set; }
    public event PropertyChangedEventHandler PropertyChangedByUser;
}

// test code
var test = new Test();
test.PropertyChangedByUser += (s, e) => Debug.Print("Property changed by user.");

var notifier = test as INotifyPropertyChanged;
if (notifier != null)
{
    notifier.PropertyChanged += (s, e) => Debug.Print("Property changed.");
}

test.Value = 100;     // "Property changed by user."  is printed instead of "Property changed."

// decompiled code from ILSpy
[method: CompilerGenerated]
[DebuggerBrowsable(DebuggerBrowsableState.Never), CompilerGenerated]
public event PropertyChangedEventHandler PropertyChangedByUser;

[field: NonSerialized]
public event PropertyChangedEventHandler PropertyChanged;

public virtual void OnPropertyChanged(string propertyName)
{
        // why not this.PropertyChanged ???
    PropertyChangedEventHandler propertyChangedByUser = this.PropertyChangedByUser;
        if (propertyChangedByUser != null)
    {
        propertyChangedByUser(this, new PropertyChangedEventArgs(propertyName));
    }
}

**Comment by SimonCropp** [comment]
please upload a repro

**Comment by SimonCropp** [comment]
closed due to no response
