### ISSUE TITLE
Emit static PropertyChangedEventArgs field for each property to take pressure off GC

### ISSUE THREAD

**Issue by NickStrupat** [Fody/PropertyChanged#195]
Most implementations of `INotifyPropertyChanged` create a new instance of the event args every time the event is raised. If a property (or many) is changed very frequently, this starts to cause significant (and totally unnecessary) GC pressure.

The solution is to have a static `PropertyChangedEventArgs` for each field, which is just passed by reference. Like so:

```
private string firstName;
private static readonly PropertyChangedEventArgs firstNameEventArgs = new PropertyChangedEventArgs("FirstName");
public string FirstName {
    get {
        return firstName;
    }
    set {
        if (firstName == value)
            return;
        firstName = value;
        OnPropertyChanged(firstNameEventArgs);
    }
}

public void OnPropertyChanged(PropertyChangedEventArgs  eventArgs)
{
    PropertyChanged?.Invoke(this, eventArgs);
}
```

The change would be pretty trivial except that this `PropertyChanged` library supports MVVMLight and several other libraries which are incompatible with this approach since they supply their own method which takes `string propertyName`.

So the other aspect to this change is only using the new approach when no external lib is used.

**Comment by SimonCropp** [comment]
sounds good. send us a PR

**Comment by SimonCropp** [comment]
let me know if u ever get to that PR
