### ISSUE TITLE
Inheritance and DependsOn() Not working...

### ISSUE THREAD

**Issue by bkettouche** [Fody/PropertyChanged#199]
Hi, 

i have an issue about Inheritance. Imagine this :

```
[ImplementPropertyChanged]
    public class a1
    {
        public string a { get; set; }

        [DependsOn("a")]
        public string b => this.a + " LAURE ";
    }
```

It's working well. But now imagine this :
```
`    [ImplementPropertyChanged]
    public class a1
    {
        public string a { get; set; }

    }

    // Change nothing : [ImplementPropertyChanged]
    public class a2 : a1
    {
        [DependsOn("a")]
        public string b => this.a + " LAURE ";
    }
```

The second case is not working (my binding is never notified). "a" is not found by Fody.PropertyChanged compilator (a warning say it) so it ignor it... Any solution ? Or any way to call it manually ?

**Comment by distantcam** [comment]
@bkettouche If you were not using PropertyChanged.Fody how would you write
the classes a1 and a2 manually?

**Comment by bkettouche** [comment]
Somethings like that     
```
// Parent for have children who use the same PropertyChangedEventHandler
public class classImplementINotify: INotifyPropertyChanged
{
	public event PropertyChangedEventHandler PropertyChanged;
	public void NotifyPropertyChanged(String propertyName = "")
	{
		if (PropertyChanged != null)
			PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
	}

public class a1 : classImplementINotify
{
	private string _a;
	public string a
	{
		get
		{
			return _a;
		}
		set
		{
			_a = value;
			NotifyPropertyChanged("a"); // Notify A
			NotifyPropertyChanged("b"); // [AlsoNotifyFor("b")]
		}
	}
}

public class a2 : a1
{
	public string b
	{
		get
		{
			return this.a + " LAURE ";
		}
	}
}
```

**THE CODE UNDER WORKS**
```

// Will be auto-binded by Fody.PropertyChanged
[ImplementPropertyChanged]
public class classImplementINotify: INotifyPropertyChanged
{
	public event PropertyChangedEventHandler PropertyChanged;
	public void NotifyPropertyChanged(String propertyName = "")
	{
		if (PropertyChanged != null)
			PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
	}

public class a1 : classImplementINotify
{
	
	private string _a;
	public string a
	{
		get
		{
			return _a;
		}
		set
		{
			_a = value;
			// Not necessary to notify A, Fody.PropertyChanged will do it for me
			NotifyPropertyChanged("b"); // [AlsoNotifyFor("b")]
		}
	}
}

public class a2 : a1
{
	public string b
	{
		get
		{
			return this.a + " LAURE ";
		}
	}
	
	public string c { get; set; } // Will be auto-notified cause of inheritance
}
```

I would like to have this annotation 
`[AlsoNotifyFor(string PropertyName, bool bindItEvenIfNotFound = false)]`
or
`[NotifyAnywaysFor(string PropertyName)]`
By this way we could ask to autogenerate the property "blindly"
And after this i could have "proper" code like this :
```
public class a1 : classImplementINotify
{
	[AlsoNotifyFor("b", true)] // Where true = bind it anyways | or something like : [NotifyAnywaysFor(string "b")]
	public string a { get; set;}
}

public class a2 : a1
{
	public string b => this.a + " LAURE ";
	public string c { get; set; } // Will be notified cause of inheritance
}
```

It would be usefull and i don't think it's that so hard compared to all the job is already done. Indeed in case i create "a1" object, "b" property will be notified but it represent nothing for it. I don't think it matter.

Or alternative solution would be to override "a" property in the class a2 when [DependsOn("a")] is used and found in parent class ? (Probably more harder)

**Comment by distantcam** [comment]
@bkettouche Ok so in the setter for property `a` you have this code.

    set
    {
        _a = value;
        NotifyPropertyChanged("a"); // Notify A
        NotifyPropertyChanged("b"); // [AlsoNotifyFor("b")]
    }

How can fody know that it should notify for b if it's in a child class? Class a2 could be in a different project that isn't even using fody.

What about when class `a3` is written and also requires a notify method in the setter of `a`? Should we have to recompile the project that `a1` is in because of `a3` now?

What about instead just writing the classes independently?

    [ImplementPropertyChanged]
    public class a1
    {
        public string a { get; set; }
    }

    [ImplementPropertyChanged]
    public class a2 
    {
        public string a { get; set; }
        public string b => this.a + " LAURE ";
    }

And if both of these classes need a shared base, use an interface.

    public interface IA
    {
        string a { get; set; }
    }

    public class a1 : IA
    public class a2 : IA

**Comment by bkettouche** [comment]
a2 is a child of a1 ! It's the same project and the property "a" of a1 is used on the child a2. It's not just the same variable, i need the value from the parent "a1" !

Btw a1 AND a2 have to use fody in my case, i want all property notified for my form.

If i use [DependsOn] on a2, fody should be able to check if the property name exists in parent right ? 
What about "notify also even if not found" decorator ?

**In my case "a2" is clearly a child of a1, not because they have "a" in common but because it's an extension of the class "a1"** this is just an simplified example of my case. 

Some properties who changes have to notify some others property for the "IDataErrorInfo" management of my wpf form. In my case when "a" is changed it have to notify "b". I don't want to merge a1 and a2 because a1 is not the same entity of a2 but a2 is clearly a child of a1, not a different class with common interface.

**Comment by bkettouche** [comment]
Another simplest example of what i mean

```
public class a1 : classImplementINotify
{
    public string a { get; set; }
}

public class a2 : a1
{
    [AlsoNotifyFor("a")]
    public string c { get; set; } // WORKS
    [DependsOn("a")]
    public string d { get; set; } // Not working but should right ? a2 know "a" property, the property "c" proove it
}
```
What should be generated ;

```
public class a1 : classImplementINotify
{
    private string _a = String.Empty;
    public string a 
    { 
        get
        {
			return _a;
        } 
        set
        {
			_a = value;
			NotifyPropertyChanged("a"); // Notify HimSelf
			if (this is a2) // For not notify if the object is a simple a1, not an a2
				NotifyPropertyChanged("d"); // This is the "[DependsOn("a")]" of a2
        }    
    }
}

public class a2 : a1
{
    
	private string _c = String.Empty;
    public string c 
	{
        get
        {
			return _c;
        } 
        set
        {
			_c = value;
			NotifyPropertyChanged("c"); // Notify HimSelf
			NotifyPropertyChanged("a"); // This is the "[AlsoNotifyFor("a")]"
        }  
	}
	
    private string d = String.Empty;
    public string d 
        get
        {
			return _c;
        } 
        set
        {
			_c = value;
			NotifyPropertyChanged("d"); // Just Notify HimSelf
        }  
}
```

**Comment by SimonCropp** [comment]
sorry but the parent class should not know about child property notifications.
