### ISSUE TITLE
Fody ProperyChanged and Expression Bodies?

### ISSUE THREAD

**Issue by adamhill** [Fody/PropertyChanged#206]
Does PropertyChanged support expression bodies if you markup at the class level?

R# has a refactoring suggestion now that turns this:

`public bool LoginEnabled
        {
            get
            {
                return SelectedDivision != null;
            }
        }`

into this:

`public bool LoginEnabled => SelectedDivision != null;`

Thanks.

**Comment by mutzl** [comment]
Short answer: yes.
