### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by igorushi** [Fody/PropertyChanged#207]
Hi @SimonCropp, could you please add some notes to releases?

**Comment by SimonCropp** [comment]
https://github.com/Fody/PropertyChanged/milestones?state=closed

**Comment by igorushi** [comment]
@SimonCropp , so ... are you going to add release notes or just closing the issue? Shall I explain why am I asking for it?

**Comment by SimonCropp** [comment]
i was hoping milestones with assigned issues would suffice

**Comment by igorushi** [comment]
@SimonCropp , oh I wasn't aware of it, thanks for pointing out. Now I'm trying to understand - the latest stable version on nuget is `2.0.1` and I have `1.53.0` installed none of those is on the milestone list ... how should one know what was changed ? 

---

![image](https://cloud.githubusercontent.com/assets/7131092/26528435/a95c7f44-43b4-11e7-915b-bd73df325fd4.png)
---

I'm using your library in many projects and it's really cool, but I can't update it 3 times a month :)

**Comment by pfaucon** [comment]
Kind of necro-posting but I would second this.  We are updating some projects and the version have changed significantly.  Milestones are great for one version to the next, but a changelog where everything is visible would be nice.

I also found https://github.com/github-tools/github-release-notes (disclosure I've never used it) that can auto-generate the documentation, it might be nice to have.

**Comment by SimonCropp** [comment]
@pfaucon if u r happy to research, implement, and send PRs for all the fody repos https://github.com/Fody i am happy to consider this

**Comment by SimonCropp** [comment]
@igorushi i maintain many packages, 114 at current count https://www.nuget.org/profiles/simoncropp, i have chosen a solution that allows me to maintain the release information with the available time i have. if u can propose an alternative that takes equivalent or less time i am happy to consider it
