### ISSUE TITLE
Nuget Package folder 'Lib' casing

### ISSUE THREAD

**Issue by Splamy** [Fody/PropertyChanged#208]
Hi, I've noticed that the current Nuget package folder hierarchy to `Lib` by default looks like this:
`/packages/PropertyChanged.Fody.1.52.1/Lib`
and Visual Studio will then add a reference in the .csproj like that:
`..\packages\PropertyChanged.Fody.1.52.1\lib\[...]`

While on Windows the casing of `Lib` doesn't matter, on Linux it won't build since it cant find the .dll
I've now renamed the Reference in my Project and it works fine.

My question is, did I mess something up during setup, or is this a configuration error?
For the latter I'd recommend to change it to `lib` since pretty much all other Nuget packages are like that too.

**Comment by SimonCropp** [comment]
Have u raised this with the nuget team? Since this would seem to cause many bugs in a significant number of nugets

**Comment by SimonCropp** [comment]
can u try  2.0.0-beta001

**Comment by Splamy** [comment]
Hey, thanks for the update.
Unfortunately I can't test it since get this error when updating with nuget:
`Could not install package 'PropertyChanged.Fody 2.0.0-beta001'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

**Comment by SimonCropp** [comment]
@Splamy version 2 has been moved to netstandard1.3 which means you need to update to at least .net 4.6

https://docs.microsoft.com/en-us/dotnet/standard/library#net-platforms-support

Hopefully it will not be a problem for you to update to a 2 year old version of .net
