### ISSUE TITLE
Globally disable notifications for backing fields 

### ISSUE THREAD

**Issue by igitur** [Fody/PropertyChanged#213]
I'd like `PropertyChanged` notifications to be raised only for properties and not when I touch their backing fields. I'm aware of the `DoNotNotify` attribute, but would you consider an easy way to globally disable notifications for when backing fields change?

**Comment by SimonCropp** [comment]
sounds good. submit a PR

**Comment by SimonCropp** [comment]
let me know if u ever get to that PR

**Comment by igitur** [comment]
Yes, I still plan to submit one.
