### ISSUE TITLE
How do I deal with interfaces that should have INotifyPropertyChanged?

### ISSUE THREAD

**Issue by tofutim** [Fody/PropertyChanged#214]
For example, if you have
```
	public interface IFlag : INotifyPropertyChanged
	{
		string Name { get; set; }
		bool IsOn { get; set; }
		bool IsEnabled { get; set; }

		void AddTo(IDictionary<string, IFlag> flags);
	}
```
and 
```
	[ImplementPropertyChanged]
	public class BaseFlag : IFlag
	{
```
it doesn't work, because the compiler does not see implementation until after compilation. But I want IFlag to have the iNotifyPropertyChanged.... any tips?

**Update.** It would be nice if you could also add INotifyPropertyChanged to interfaces maybe
```
	[ImplementPropertyChanged]
	public interface IFlag : INotifyPropertyChanged
```
?? I get this though

>Attribute 'ImplementPropertyChanged' is not valid on this declaration type. It is only valid on 'class' declarations.

**Update2.** It looks like if I do not use the [ImplementPropertyChanged] and use INotifyPropertyChanged on IFlag and then implement PropertyChanged in BaseFlag (but do not do anything with the Properties), Fody will do the right thing, with the exception that it swaps out my own RaisePropertyChanged with its own. 

```
    public virtual void RaisePropertyChanged(string propertyName)
    {
      // ISSUE: reference to a compiler-generated field
      PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
      if (propertyChanged != null)
        propertyChanged((object) this, new PropertyChangedEventArgs(propertyName));
    }
```

Never mind maybe it doesn't do that.

**Comment by dpedrinha** [comment]
Any news on this?

**Comment by SimonCropp** [comment]
just have somewhere in your class hierachy an interface with INotifyPropertyChanged  and it should work

**Comment by SimonCropp** [comment]
btw `[ImplementPropertyChanged]` on a class  that has `INotifyPropertyChanged` in it hierarchy is redundant
