### ISSUE TITLE
Minor issue in nodes populating-related code

### ISSUE THREAD

**Issue by ultimate-deej** [Fody/PropertyChanged#215]
[This check](https://github.com/Fody/PropertyChanged/blob/427f0baabb69b17689fb15af99c2f0a756dd5a5e/PropertyChanged.Fody/TypeNodeBuilder.cs#L60-L63) is never true because any node that could possibly pass the check is [removed](https://github.com/Fody/PropertyChanged/blob/427f0baabb69b17689fb15af99c2f0a756dd5a5e/PropertyChanged.Fody/TypeNodeBuilder.cs#L33-L37).
I suggest deleting the loop to make the check actually useful. Alternatively, the check itself can be removed. All tests still pass in either case.

As a side note, the file mentioned seems to be the perfect place for implementing #183.

**Comment by SimonCropp** [comment]
can u submit a PR with a failing test

**Comment by ultimate-deej** [comment]
As I said, no tests are failing. The issue is simply that the code mentioned is confusing (the intended logic is not clear). Either the check or the loop is redundant.

**Comment by SimonCropp** [comment]
why is that redundant. using the fody attribute when you already implement the interface is redundant. hence the exception

**Comment by ultimate-deej** [comment]
I explained why in the very first sentence

> [This check](https://github.com/Fody/PropertyChanged/blob/427f0baabb69b17689fb15af99c2f0a756dd5a5e/PropertyChanged.Fody/TypeNodeBuilder.cs#L60-L63) is never true because any node that could possibly pass the check is [removed](https://github.com/Fody/PropertyChanged/blob/427f0baabb69b17689fb15af99c2f0a756dd5a5e/PropertyChanged.Fody/TypeNodeBuilder.cs#L33-L37).
