### ISSUE TITLE
Click Once installation is failed without PropertyChanged dll

### ISSUE THREAD

**Issue by arteny** [Fody/PropertyChanged#216]
Althoug PropertyChanged removes itself after compiling, it is impossible to install application, when PropertyChanged dll excluded from Publish. Error: PropertyChanged dll not found in GAG.

**Comment by SimonCropp** [comment]
looks like you are bundling the click once prior to the weaving happening. can u extract out the dll from the click once and see if the property notifications have been added?

**Comment by SimonCropp** [comment]
closed due to no response
