### ISSUE TITLE
Bug : OnPropertyChanged function is called 4 times

### ISSUE THREAD

**Issue by Shiloovr** [Fody/PropertyChanged#217]
OnPropertyChanged function is called 4 times

It happens when I inherits from class with a ImplementPropertyChanged attribute

Here's the code:

[https://drive.google.com/file/d/0B0C_KheExAN7RGQwR2lvUzZMZ28/view?usp=sharing](url)

![image](https://cloud.githubusercontent.com/assets/10143678/22012128/41b2d184-dc9b-11e6-95e5-91edbacbcb91.png)

**Comment by SimonCropp** [comment]
ImplementPropertyChanged  causes OnPropertyChanged  to be implemented in your base class. then u duplicate it in the child class. why would you want to do that?

**Comment by Shiloovr** [comment]
A few months later, I remember that I needed this structure, but I do not remember why. Anyway, I've worked out since then. I'll close the ticket, thank you.

**Comment by SimonCropp** [comment]
Good to hear
