### ISSUE TITLE
DependsOn build warning in derived class

### ISSUE THREAD

**Issue by computinglabs** [Fody/PropertyChanged#218]
A message like the one below is shown in Output window of Visual Studio:
Fody/PropertyChanged:   Could not find property 'AProperty' for DependsOnAttribute assigned to 'BProperty'.

Here is an example to reproduce it:
```
[ImplementPropertyChanged]
public class AClass {
   public string AProperty { get; set; }
}

[ImplementPropertyChanged]
public class BClass : AClass {
   [DependsOn("AProperty")]
   public string BProperty { get { return string.Format("AProperty = '{0}'.", AProperty); } }
}
```

The basic idea is to have a property in a derived class that depends on a property from a base class. It seems that right now this is not supported.

Is it possible to support it? Eventually by using something like [DependsOn("AClass.AProperty")], so that weaving framework knows the "origin" of the property (in case of multiple/deeper inheritance).

**Comment by SimonCropp** [comment]
sorry this is not supported by design as it would leak the design of child classes into the parent
