### ISSUE TITLE
AlsoNotifyFor/DependsOn and Exceptions

### ISSUE THREAD

**Issue by vitidev** [Fody/PropertyChanged#219]
We have property

        [AlsoNotifyFor("RelatedProp")]
        public string BottomString
        {
            get { return _BottomString; }
            set
            {
                if (value == null)
                    throw new ArgumentException();
                _BottomString = value;
            }
        }

Fody rewrite the code:

    public string BottomString
    {
      ...
      set
      {
        if (string.Equals(this._BottomString, value, StringComparison.Ordinal))
          return;
        if (value == null)
          throw new ArgumentException();
        this._BottomString = value;
        this.OnPropertyChanged("RelatedProp");
        this.OnPropertyChanged("BottomString");
      }
    }

if value==null the code OnPropertyChanged("RelatedProp"); will never be called.

maybe we need a new attribute "AlsoNotifyForAlways", which rewrite code like:

    public string BottomString
    {
      ...
      set
      {
        if (string.Equals(this._BottomString, value, StringComparison.Ordinal))
          return;
        try{
             if (value == null)
                  throw new ArgumentException();
             this._BottomString = value;
             this.OnPropertyChanged("BottomString");
        }finally{
              this.OnPropertyChanged("RelatedProp");
        }
      }
    }

**Comment by SimonCropp** [comment]
sorry this would be way too difficult to implement
