### ISSUE TITLE
Initializing properties in constructor generates CA2214:DoNotCallOverridableMethodsInConstructors

### ISSUE THREAD

**Issue by tom-englert** [Fody/PropertyChanged#220]
Seems that the OnPropertyChanged is virtual by default, and when initializing properties in the constructor it gets already called.
Calling OnPropertyChanged from within the constructor is usually not needed (no one can have attached to the PropertyChanged event yet), so from within the constructor only the backing field should be initialized, and no event should be raised.

**Comment by SimonCropp** [comment]
cant a class attach to its own PropertyChanged in the constructor  ?

**Comment by tom-englert** [comment]
Not if you don't implement `INotifyPropertyChanged` explicitly, but only rely on  `[ImplementPropertyChanged]`.

However it would still be possible to see OnPropertyChanged override methods being called in derived classes for properties of the base class, even before the constructor of the derived class has been called - a common source of bugs.

If you explicitly implement `INotifyPropertyChanged`, you can register for and get events also before the constructor of the class has been finished, which can lead to the same problems. 

So ignoring this warning is really dangerous, and making use of the side effects of the above is error prone.

I agree considering the above it's possible that unexperienced developers might be already using such error prone patterns, so it's not possible to fix this without adding a another switch (e.g. GenerateOnlySafeCde = true)

[CA2214](https://msdn.microsoft.com/en-us/library/ms182331.aspx):

**Rule Description**

When a virtual method is called, the actual type that executes the method is not selected until run time. When a constructor calls a virtual method, it is possible that the constructor for the instance that invokes the method has not executed.

**How to Fix Violations**

To fix a violation of this rule, do not call a type's virtual methods from within the type's constructors.

**When to Suppress Warnings**

Do not suppress a warning from this rule. The constructor should be redesigned to eliminate the call to the virtual method.

**Comment by tom-englert** [comment]
Also an annoying side effect: If you initialize properties in the constructor, and have an `IsChanged` property, `IsChanged` is `true` right after creating the object.

**Comment by SimonCropp** [comment]
I am a little confused. OnPropertyChanged is not called in the constructor but in the property.

**Comment by tom-englert** [comment]
... and the property is set in the constructor, so the call chain starts in the constructor.

LG
Tom
________________________________
Von: Simon Cropp<mailto:notifications@github.com>
Gesendet: ‎26.‎05.‎2017 04:33
An: Fody/PropertyChanged<mailto:PropertyChanged@noreply.github.com>
Cc: tom-englert<mailto:mail@tom-englert.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Fody/PropertyChanged] Initializing properties in constructor generates CA2214:DoNotCallOverridableMethodsInConstructors (#220)


I am a little confused. OnPropertyChanged is not called in the constructor but in the property.

**Comment by SimonCropp** [comment]
but in the context of a property set there is no way we can know that the caller is inside the constructor

**Comment by tom-englert** [comment]
In the constructor the property setter should be replaced by just initializing the backing field

LG
Tom
________________________________
Von: Simon Cropp<mailto:notifications@github.com>
Gesendet: ‎26.‎05.‎2017 08:26
An: Fody/PropertyChanged<mailto:PropertyChanged@noreply.github.com>
Cc: tom-englert<mailto:mail@tom-englert.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Fody/PropertyChanged] Initializing properties in constructor generates CA2214:DoNotCallOverridableMethodsInConstructors (#220)


but in the context of a property set there is no way we can know that the caller is inside the constructor

**Comment by SimonCropp** [comment]
> In the constructor the property setter should be replaced by just initializing the backing field

but that is something you would have to do. that is outside the scope of this project

**Comment by tom-englert** [comment]
I'll have a look, I will post a PR whenever I got time to fix it.

**Comment by 0x53A** [comment]
Damn, this just bit me. :D
I am using INPC to synchronize internal state, and was expecting this to also work in the ctor.

Short (non-representative) example: 
```C#
    public class C
    {
        public string Text { get; set; }
        public int TextLength { get; set; }

        public C()
        {
            // internal helper which just subscrives to the event and checks the property name
            INPC.Subscribe(this, _ => _.Text, () =>
            {
                TextLength = Text?.Length ?? 0;
            });

            Text = "Hello!";
            // Expected: TextLength is 6
            // Actual: TextLength is 0
        }
    }
```

I guess for now I can work around this by extracting parts into an ``Init`` method, and call that from the ctor.

@tom-englert Could you maybe also update the documentation?

**Comment by SimonCropp** [comment]
@0x53A given there is clearly breaking scenarios we had not considered, perhaps we should make this an opt in setting?

**Comment by 0x53A** [comment]
I would obviously prefer an opt-in setting.

Depending on the motivation there may be different solutions:

1) opt-in (maybe a new attribute ``WriteDirectlyToBackingFields`` applied to methods?
2) opt-out (a new attribute ``NotifyInsideCTor`` applied to a ctor)
3) if the only issue is the code-analysis warning, then maybe a new switch that controls whether ``OnPropertyChanged `` is virtual or not?
4) [revert, and tell the user to suppress the warnings in their tool.] :D

In my case there is no hierarchy, so virtuality does not matter.

**Comment by tom-englert** [comment]
@0x53A why not just use 
```
    public int TextLength => Text?.Length ?? 0;
```

4. is not an option => As the documentation says: "Do not suppress a warning from this rule. The constructor should be redesigned to eliminate the call to the virtual method.". And you could only suppress this for the whole constructor and would miss violations caused by other code.

3. The issue is not the warning, as the warning is not just for fun, but points out bad design. Also the behavior of `IsChanged` depends on this, so the behavior would be different if `OnPropertyChanged` is virtual or not - something that would drive you nuts finding out why this happens in one class but not in another.

1./2. opt-out, either on class or assembly level, should be the preferred option. The default should be clean and robust code that does not violate the basic rules of programming.

In the sample above, if you really need this design, you can easily move the code to an `Init` method or convert the auto-property into a property with backing field

**Comment by 0x53A** [comment]
@tom-englert 

> why not just use    public int TextLength => Text?.Length ?? 0;

That's why I wrote the code is not representative. =)

> ... The default should be clean and robust code that does not violate the basic rules of programming. ...

I do not agree with the assertion that such code is not robust, or bad design.

> 4. is not an option => As the documentation says: "Do not suppress a warning from this rule."

Now that is just entering dogmatic territory.
Besides, it was not completely serious, that's why it was in braces and the smiley.

----


The only issue I see is that the method is incidentally virtual.

My preference in hindsight would be opt-in AND non-virtual by default.
Then there would be neither a code-analysis warning nor surprising behavior in the case of sub-classing.

But the ship for non-virtual by default has probably sailed...

-----

I find the current behavior a bit unintuitive, because some places do notify, and others do not.
At the least, this should be documented in bold in the readme.

As I said, my preference would be opt-in, but I can also live with opt-out.

**Comment by tom-englert** [comment]
It does not assert that code that can't be proven to be robust by static analysis is not robust at all, or a design that just fits your needs is generally bad - it just says that the proven one should be the one that goes out of the box, and if you can live with less, you have to opt-in.

I'll see if I can make a proposal next weekend - and of course extend the documentation.

**Comment by navozenko** [comment]
@tom-englert I understand your motives. But for solving this (not very significant) problem you paid too high a price: you disrupted the work of a huge number of existing applications. In addition, the solution you proposed is in itself a potential source of confusion and error.

**Comment by navozenko** [comment]
Since we returned to this topic, I repeat that I wrote in #264.

I like the idea to provide a some way to disable notifications in constructor. But I do not like it if the notification disabling will apply to auto-properties only. In my opinion, notification disabling should affect to all properties. Otherwise, we will get confusion and an even more dangerous situation than now.

It seems to me that a good option (in terms of uniformity and clarity) would be to use the [DoNotNotify] attribute on any method. Unfortunately, I do not see a way of thread-safe implementation of such  attribute without a significant performance loss.

There remains the variant of creating a special attribute [DoNotNotifyInConstructor] or [NotifyInConstructor] as we discussed in #264. However, I was not able to come up with a good implementation here. The only variant that came to my mind is to check the contextual information in each property. For example:

```
class Model
{
    protected bool _isNotificationEnabled;
    private int _foo;

    public Model()
    {
        Foo = 1;
        _isNotificationEnabled = true;
    }

    public int Foo
    {
        get { return _foo; }
        set
        {
            ...
            if (_isNotificationEnabled)
            {
                ...Notify here...
            }
        }
    }
}
```
I understand that the idea is not ice. Does anyone have better ideas?

**Comment by tom-englert** [comment]
@navozenko  There are already differences for auto-properties, depending on how you use them:

```C#
public class WithInlineInitializedAutoProperties : ObservableObject
{
    public string Property1 { get; set; } = "Test";
}

public class WithExplicitConstructorInitializedAutoProperties : ObservableObject
{
    public string Property1 { get; set; }
	
    public WithExplicitConstructorInitializedAutoProperties()
    {
        Property1 = "Test";
    }
}
```
Looking at the code you would expect the same behavior for both, but the first one complies to 
```C#
public class WithInlineInitializedAutoProperties : ObservableObject
{
  [CompilerGenerated]
  [DebuggerBrowsable(DebuggerBrowsableState.Never)]
  private string <Property1>k__BackingField = "Test";
  ...
```
and you will get no event from within the constructor. So when using Fody/PropertyChanged with auto-properties, there are already some surprises built in today - so you already have to be careful and know what you're doing when implementing more than a simple POCO view-model.

My approach uses exactly the same technique that the Microsoft C# compiler does, it's absolutely thread save, and has no performance impact. It solves exactly the problem, and does not interfere with code that is not affected by the problem.

**Comment by navozenko** [comment]
@tom-englert 
This is natural, because auto-property initialization is performed before calling of constructor.

I'm talking about something else. If in constructor we write `Foo = 1; Bar = 2;` and property `Foo` raises event, and property `Bar` does not raise this is strange behavior.

Moreover, the `Foo` property will still call the virtual method. In addition, if we call in the constructor some method `Init()` which sets the auto-property `Bar`, we will again receive a notification and calling a virtual method. It turns out that your proposal does not provide a complete solution to the problem.

**Comment by tom-englert** [comment]
Right, as it never claimed to provide a complete solution to a problem that does not exist.

It only solves exactly the problem that it's impossible to bypass the property setter and assign a value to the backing field of an auto-property.

**Comment by tom-englert** [comment]
The best approach would have been some pseudo code like `MyProperty.SetBackingField("value");`
that is replaced when weaving the assembly. However I did not find an acceptable notation - maybe someone has an idea how this could be done?

**Comment by navozenko** [comment]
@tom-englert Do you propose to call a special method instead of setting values to properties? For all properties or for auto-properties only?

**Comment by SimonCropp** [comment]
isnt the easiest way to fix this to make OnPropertyChanged  non virtual?

**Comment by navozenko** [comment]
@SimonCropp 
I like your suggestion. We can add an attribute `[AutoGenerateVirtuals(true|false)]` or `[AutoGenerateVirtualMethods(true|false)]`.

Indeed, if a developer uses his own methods for notifications handling and declares its as virtual, he must take care of its safe using (for example, do not assign properties in constructor). This is responsibility of the programmer.

But if we are talking about auto-generated methods, then what should be its default modifier? Virtual or not? Should we refuse backward compatibility? In most cases, virtuality is not required, since this method is not available in source code and we can’t override it in a derived class. But it's possible that someone uses a base class from another compiled assembly created by Fody. In this case, the we can override a virtual `OnPropertyChanged` method. Although, most likely, this is a rare situation.

By the way, I was surprised that the auto-generated `OnPropertyChanged` method is public. Is not it better to make it protected?

**Comment by tom-englert** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/event:

DO use a **protected virtual** method to raise each event.

**Comment by navozenko** [comment]
I here still thought. An auto-generated OnPropertyChanged method is not exist in source code. Therefore, warnings about calling a virtual method should not be issued. That is no problem for the auto-generated method. Or I'm wrong?

**Comment by tom-englert** [comment]
@navozenko:
- FxCop analyses the IL code after weaving, so the auto-generated methods will be analyzed, too.
- We don't want to just omit the warning - we want to fix the problem.
- Also to consider: Objects in assembly B can see the auto-generated OnPropertyChanged of their base object declared in assembly A!

**Comment by navozenko** [comment]
@tom-englert
Thank you. Then I think that the SimonCropp's suggestion is the simplest and best solution to the problem.

I think, it's normal if the implementation of OnPropertyChanged is not virtual. For example, the RaisePropertyChanged in [DevExpress](https://github.com/DevExpress/DevExpress.Mvvm.Free/blob/master/DevExpress.Mvvm/ViewModels/BindableBase.cs) is not a virtual. And even in the [MSDN](https://msdn.microsoft.com/en-us/library/ms229614(v=vs.100).aspx) the corresponding method is not virtual.


The only question is which implementation should be by default: virtual or not.

**Comment by tom-englert** [comment]
This only shows that many developers don't care too much about design guides and quality measures. Just because some code is public, it does not mean it's free of bugs or design flaws.

In the MSDN sample the method is private - you could not use property changed from a derived class, so the class should have be sealed.

**Comment by navozenko** [comment]
@tom-englert 
Excuse me, I don't believe that a non-virtual OnPropertyChanged is a bad design. From my opinion, the both approaches are correctly and each programmer can choose what it is better for him:

```csharp
var foo = new Foo(id, name);    // For non-virtual OnPropertyChanged 
```
or
```csharp
var foo = new Foo { Id = id, Name = "name" };   // For virtual OnPropertyChanged
```

**Comment by tom-englert** [comment]
@navozenko I never said it's bad design in general - it just does not follow the [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/event).
Our coding guidelines enforce compliance with the [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines), so for **us** it would be considered to be a bug.

**Comment by navozenko** [comment]
@tom-englert 
If you use virtual event raisers, what prevents you do NOT assign properties in constructor? Is this not right design for such cases?

**Comment by tom-englert** [comment]
@navozenko you would not be able to force initialization nor to define non-null contracts for those properties.

**Comment by ylatuya** [comment]
Please, also consider the scenario in which weavers changing the setter are chained. In our case, we first a apply a custom weaver that we use to forward PropertyChanged events of properties with types implementing INPC or emitting CollectionChanged events. If in the constructor only the backing field is initialied, you will also be skipping other weaving code people might rely on.
This how our weaved setter would look like:

```
public RangeObservableCollection<Point> Points {
    set {
        if (value.Equals(this._points)) {
            return;
        }
        ConnectChild (value);
        IsChanged = true;
        OnPropertyChanged ("points");
    } 
}
```

When Points is initialized in the constructor we still want to call ConnectChild.

**Comment by tom-englert** [comment]
After thinking twice I came to the conclusion that this problem has a more global nature, and is not just related to PropertyChanged - it could occur with any other tool that modifies the setter of an auto-property.

So I have packed my solution in another add-in: [AutoProperties.Fody](https://github.com/tom-englert/AutoProperties.Fody).

Now the solution is totally distinct from this add-in, and there is no more risk to break the behavior of Fody.PropertyChanged.

**Comment by navozenko** [comment]
Still, I think that it would be good to give developers the ability to make auto-implemented OnPropertyChanged as non-virtual.

**Comment by SimonCropp** [comment]
@navozenko they can implemented a non virtual explicitly if they want

**Comment by tom-englert** [comment]
@navozenko or simply declare the class as sealed
