### ISSUE TITLE
Is Fody meant to deal with collections too?

### ISSUE THREAD

**Issue by weitzhandler** [Fody/PropertyChanged#221]
Hi,

Does Fody also implement INotifyCollectionChanged on ICollection<T> property types?

**Comment by SimonCropp** [comment]
no

**Comment by weitzhandler** [comment]
@SimonCropp 
Thanks for your quick response.
Does anything like that exists?
Would it be easy to implement with Fody?

**Comment by SimonCropp** [comment]
> Does anything like that exists?

not that i know of

> Would it be easy to implement with Fody?

it is not a matter of "easy". It is a matter of "what value could IL weaving ad"

**Comment by weitzhandler** [comment]
I mean, with the existing implementation of Fody, would that be a whole new project to make or simply changing few lines here and there

**Comment by SimonCropp** [comment]
my point is INotifyCollectionChanged is mostly about runtime code. ie tracking of add and remove of items

i dont see how IL can solve the problem

**Comment by weitzhandler** [comment]
You're right.
But essentially reverting any `ICollection<T>` property implementation to `ObservableCollection<T>` would be the goal.

**Comment by SimonCropp** [comment]
isnt that a trivial code change?

**Comment by weitzhandler** [comment]
It's classes from other assemblies...

**Comment by SimonCropp** [comment]
then you should not attempt to bind to them. instead copy them to the specific binding model that u require for the UI

**Comment by weitzhandler** [comment]
It's a large coding base.
You're probably right IL is not the solution but I'll have to find a better automated way.
