### ISSUE TITLE
After upgrading this code does not Run anymore:

### ISSUE THREAD

**Issue by TonyHenrique** [Fody/PropertyChanged#229]
I often did this code, but after upgrading 
Fody to 2.0.6 
PropertyChanged.Fody to 1.53.0
this code does Run anymore:

` ((INotifyPropertyChanged)this).PropertyChanged += MyClass_PropertyChanged;`

it gives this Exception

System.InvalidCastException: 'Unable to cast object of type 'MyClass' to type 'System.ComponentModel.INotifyPropertyChanged'.'

**Comment by TonyHenrique** [comment]
After try to Build again, it worked.

**Comment by SimonCropp** [comment]
an u upload a repro please

**Comment by SimonCropp** [comment]
closed due to no response
