### ISSUE TITLE
IChangeTracking

### ISSUE THREAD

**Issue by weitzhandler** [Fody/PropertyChanged#232]
Are you aware of [this](https://msdn.microsoft.com/en-us/library/system.componentmodel.ichangetracking.aspx) interface? Would be nice if you make the `IsChanged` property work along with it.

**Comment by SimonCropp** [comment]
That interface seems deprecated. Ie not implemented in newer runtimes?

**Comment by weitzhandler** [comment]
It is in netstandard...

On Jun 9, 2017 6:06 AM, "Simon Cropp" <notifications@github.com> wrote:

That interface seems deprecated. Ie not implemented in newer runtimes?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Fody/PropertyChanged/issues/232#issuecomment-307283355>,
or mute the thread

**Comment by SimonCropp** [comment]
can u point me to that. since i cant see it here

![image](https://user-images.githubusercontent.com/122666/26960806-5d81ecc2-4d1d-11e7-91fe-8fd59de4240a.png)

**Comment by weitzhandler** [comment]
https://github.com/dotnet/standard/blob/master/netstandard/pkg/shims/netstandard/System.ComponentModel.Forwards.cs#L3

**Comment by tom-englert** [comment]
@weitzhandler: doesn't this work already?

```C#
[AddINotifyPropertyChangedInterface]
class Test : IChangeTracking
{
    public void AcceptChanges()
    {
        IsChanged = false;
    }

    public bool IsChanged
    {
        get;
        protected set;
    }
}
```

**Comment by SimonCropp** [comment]
@weitzhandler I will accept a PR for this

**Comment by weitzhandler** [comment]
Unfortunately I don't speak IL, and currently don't have the time to get into it.
I'm gonna close this issue for now. If it bothers anyone, I'll open up on demand / comments etc.

Thank you @SimonCropp for everything!
