### ISSUE TITLE
Weaver.xml v2.0

### ISSUE THREAD

**Issue by dansiegel** [Fody/PropertyChanged#236]
After testing v2.0 noticed the following issues

1) The `FodyWeavers.xml` is not getting created in the netstandard library. 
2) The FodyWeavers doesn't actually contain the `<PropertyChanged />` node. Really would be nice to include the following:

**FodyWeavers.xml.install.xdt**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Weavers xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <PropertyChanged xdt:Transform="Insert"/>
</Weavers>
```

**FodyWeavers.xml.uninstall.xdt**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Weavers xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <PropertyChanged xdt:Transform="Remove" />
</Weavers>
```

nuspec
```xml
<file src="FodyWeavers.xml.install.xdt" target="content"/>
<file src="FodyWeavers.xml.uninstall.xdt" target="content"/>
```

**Comment by MihaMarkic** [comment]
AFAIK this is by design since NuGet doesn't allow that anymore. @SimonCropp written that somewhere.
You simply create it manually.

**Comment by SimonCropp** [comment]
@MihaMarkic is correct. also the `xml.install.xdt` is fundamentally broken since it doesnt understand upgrades, so during an upgrade u delete any customizations to the node
