### ISSUE TITLE
Use explicit method instead of On_PropertyName_Changed

### ISSUE THREAD

**Issue by nganbread** [Fody/PropertyChanged#237]
Regarding this feature: https://github.com/Fody/PropertyChanged/wiki/On_PropertyName_Changed

Instead of looking for a method with the correct name, it would be useful to be able to declare it using an attribute instead

Something like:

```csharp
[OnPropertyChanged(nameof(PropertyChanged))]
public string Property { get; set; }

private void PropertyChanged()
{

}
```

**Comment by SimonCropp** [comment]
why would that be useful? you would need to define the same thing on every property resulting in a large amount of duplciation

**Comment by nganbread** [comment]
Sorry, I meant to say that this functionality could be provided alongside the existing On_PropertyName_Changed

When using the `nameof` operator it creates a reference between the function and the property which is useful for static analysis tools and usage finding. Also, in the case of working in teams (where developers may not be aware of the weaving), it wouldn't look as magical

**Comment by SimonCropp** [comment]
Sorry but explicitness is not one of the aims of the project. It aims to reduce redundant code. This proposal is not in keeping with those aims

**Comment by navozenko** [comment]
I agree with @nganbread and suggest to return to this issue. I now got an unpleasant situation, when after renaming a property, the method no longer be called. This mistake was not easy to find. Explicitly specifying the name of the called method would protect against the refactoring problem.

And besides, I agree with @nganbread that the existing "magic" with method calling is an inelegant programming style.

It seems to me that the new attribute that he proposed is a convenient and simple solution.
