### ISSUE TITLE
AlsoNotifyFor

### ISSUE THREAD

**Issue by LazyCuteLion** [Fody/PropertyChanged#240]
I want use "AlsoNotifyFor" on a method, can you modify it in future versions?

**Comment by SimonCropp** [comment]
why would u want an AlsoNotifyFor on a method?

**Comment by LazyCuteLion** [comment]
public List<string> Items { get; private set; } = new List<string>();

public bool CanRemove { get { return this.Items.Count>0; } }

[AlsoNotifyFor("CanRemove")]
public void Load()
{
  this.Items.Add("one");
}

public void Remove(string item)
{
  this.Item.Remove(item);
}

<Button IsEnabled="{Binding CanRemove}" Command=""/>

**Comment by LazyCuteLion** [comment]
In current version :

public bool CanRemove { get; private set; } 
public void Load()
{
  this.Items.Add("one");
  this.CanRemove=this.Items.Count>0;
}

**Comment by SimonCropp** [comment]
i dont understand why you would need

```
[AlsoNotifyFor("CanRemove")]
public void Load()
{
  this.Items.Add("one");
}
```
when u can do 
```
public void Load()
{
  this.Items.Add("one");
  OnPropertyChanged("CanRemove");
}
```
it is essentially the same amount of code

**Comment by LazyCuteLion** [comment]
when i use "PropertyChanged.Fody", the "model class" has not "OnPropertyChanged" before compile.
so i think, the "AlsoNotifyFor" use on a method is very nice !
just as you say:
[AlsoNotifyFor("CanRemove")]
public void Load()
{
  this.Items.Add("one");
}
after compiled:
public void Load()
{
  this.Items.Add("one");
  OnPropertyChanged("CanRemove");
}

**Comment by SimonCropp** [comment]
> when i use "PropertyChanged.Fody", the "model class" has not "OnPropertyChanged" before compile.

this is optional. you can implement INotifyPropertyChanged, have your own OnPropertyChanged and that will be detected. then u can use `OnPropertyChanged("CanRemove");` with no new feature in this project

**Comment by zspitz** [comment]
@SimonCropp Is this documented anywhere? The closest page I found was [On_PropertyName_Changed](https://github.com/Fody/PropertyChanged/wiki/On_PropertyName_Changed), but if I understand correctly you're saying that a method named `OnPropertyChanged` would also be detected, not just e.g. `OnNameChanged`?

**Comment by SimonCropp** [comment]
https://github.com/Fody/PropertyChanged/wiki/EventInvokerSelectionInjection#method-selection--injection
