### ISSUE TITLE
I suspect DoNotCheckEquality not working when applied to a baseclass defined in another DLL

### ISSUE THREAD

**Issue by hcd** [Fody/PropertyChanged#241]
Hi, I have applied [ImplementPropertyChanged, DoNotCheckEquality] to the "VIewModelBase" of a WPF project and it all worked very nice until recently. 
I started to experience some weird behavior that I couldn't explain, notifications that should have happened. (like setting a property to a same value, just to force the notification). 
This was shortly after I moved my ViewmodelBase to another "common" project (thus, another dll).
So now I have the suspicion that, while the propertychanged weaving still works on subclasses of the viewmodelbase in another dll, the [DoNotcCeckEquality] is skipped.

How can i verify this ?

**Comment by hcd** [comment]
I have just verified this with ILSpy. So I have this viewmodel baseclass with [ImplementPropertyChanged] applied, and also [DonotcheckForEquality].  Then in a subclass (with no attributes applied)  in another project, I have some property in that subclass that i inspected with IL Spy : 
[CompilerGenerated]
	get
	{
		return this.<Form>k__BackingField;
	}
	[CompilerGenerated]
	set
	{
		if (object.Equals(this.<Form>k__BackingField, value))
		{
			return;
		}
		this.<Form>k__BackingField = value;
		this.NotifyOfPropertyChange("Form");
	}

If i apply the [DonotCheckEquality] on the subclass , I get in ILSPy: 

[CompilerGenerated]
	get
	{
		return this.<Form>k__BackingField;
	}
	[CompilerGenerated]
	set
	{
		this.<Form>k__BackingField = value;
		this.NotifyOfPropertyChange("Form");
	}

So effectively, the [implementPropertyChanged] is passed down to the subclass, but not the DoNotcheckEquality ...

**Comment by SimonCropp** [comment]
can u please format your code blocks in issues https://help.github.com/articles/creating-and-highlighting-code-blocks/

I know this might seem minor but it makes it much easier to read and understand your issue

**Comment by hcd** [comment]
My bad, sorry, I've adapted it with formatting

**Comment by SimonCropp** [comment]
This is expected since all attributes are stripped from an assembly on build. So than cant span assemblies
