### ISSUE TITLE
Cannot Install Package

### ISSUE THREAD

**Issue by JeremyButts** [Fody/PropertyChanged#243]
Could not install package 'PropertyChanged.Fody 2.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by SimonCropp** [comment]
version 2 has been moved to netstandard1.3 which means you need to update to at least .net 4.6

https://docs.microsoft.com/en-us/dotnet/standard/library#net-platforms-support

Hopefully it will not be a problem for you to update to a 2 year old version of .net

**Comment by JeremyButts** [comment]
Cool, thanks. First time messing with Xamarin on Visual Studio for Mac.  Just going with the flow.

**Comment by SimonCropp** [comment]
i deployed 2.1 that now supports netstandard 1.0 so you should no be able to install with no changes
