### ISSUE TITLE
[2.0.1] PCL Xamarin.Forms error

### ISSUE THREAD

**Issue by moreirawebmaster** [Fody/PropertyChanged#244]
look image down:

![image](https://cloud.githubusercontent.com/assets/1142139/26517698/e715723c-4274-11e7-8425-67b1714e27ee.png)

**Comment by SimonCropp** [comment]
duplicate of https://github.com/Fody/PropertyChanged/issues/243

**Comment by SimonCropp** [comment]
i deployed 2.1 that now supports netstandard 1.0 so you should no be able to install with no changes
