### ISSUE TITLE
What is the .NET framework requirement for version 2.0.1?

### ISSUE THREAD

**Issue by arisliang** [Fody/PropertyChanged#248]
I was getting below error when trying to upgrade from 1.53.0 to 2.0.1.

Could not install package 'PropertyChanged.Fody 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by SimonCropp** [comment]
can u try 2.1

**Comment by arisliang** [comment]
2.1 worked. Thanks!

**Comment by SimonCropp** [comment]
just an FYI net4.5 is now unsupported https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by arisliang** [comment]
Wow, didn't know about this. Thanks for the info.
