### ISSUE TITLE
PropertyChanged.Fody version is not passed when using PackageReference.

### ISSUE THREAD

**Issue by virzak** [Fody/PropertyChanged#250]
Steps to reproduce.

Using VS 2017, PackageReference
Start project 1 using version 1.53.0 Use ImplementPropertyChangedAttribute
Make sure it builds and runs.

Start project 2 using version 2.1.0

Rebuild Project 1
Project 1 will no longer have INotifyPropertyChanged

Tried putting this into the FodyTarget, but got an empty string.

    <Error Text="Throw @(PackageDefinitions->'%(ResolvedPath)')" />

**Comment by SimonCropp** [comment]
sorry can u re-raise in https://github.com/Fody/Fody  and include the version of fody u r using

**Comment by SimonCropp** [comment]
replaced by https://github.com/Fody/Fody/issues/354
