### ISSUE TITLE
Does not rewrite IL in debug assembly 

### ISSUE THREAD

**Issue by vitidev** [Fody/PropertyChanged#251]
Clean test wpf project with Fody 2.0.10 and PropertyChanged 2.1.0

Simple one class 

    public class TestVm : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public string Foo { get; set; }

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

Debug build

     public string Foo { get; set; }

Release build

    public string Foo
    {
      get
      {
        return this.\u003CFoo\u003Ek__BackingField;
      }
      set
      {
        if (string.Equals(this.\u003CFoo\u003Ek__BackingField, value, StringComparison.Ordinal))
          return;
        this.\u003CFoo\u003Ek__BackingField = value;
        this.OnPropertyChanged("Foo");
      }
    }

What's wrong? what changed?

**Comment by SimonCropp** [comment]
can u please upload a repro solution?

**Comment by vitidev** [comment]
http://s000.tinyupload.com/index.php?file_id=98622825492787680249

**Comment by vitidev** [comment]
Also in output:

      Fody: Fody (version 2.0.10.0) Executing
      1>      Fody/PropertyChanged:   	No reference to 'PropertyChanged' found. References not modified.
      1>    Fody:   Finished Fody 73ms.

**Comment by vitidev** [comment]
Ooops

1) In work project IL rewriting began after computеr reboot. Mystic
2) Test project - my mistake. DotPeek read pdb file instead of decompliling dll/exe.
3) No reference to 'PropertyChanged' found.  - I do not know why this message appears, but it does not bother me

**Comment by SimonCropp** [comment]
"No reference to 'PropertyChanged' found" just means u r not using attributes to configure things.

will close for now. let me know if u hit it again and can reliably repro
