### ISSUE TITLE
Unexepected behavior with base classes

### ISSUE THREAD

**Issue by AsValeO** [Fody/PropertyChanged#254]
Caliburn.Micro 3.1.0
PropertyChanged.Fody 2.1.1
Not calls `NotifyOfPropertyChange()` for property `HasComplexClassConflict` when `Building` changed in this case:

```
  public class BuildingCardViewModelBase : CardViewModelBase
    {
           public Building Building { get; set; }
    }

public class OperatorBuildingCardViewModel : BuildingCardViewModelBase
    {
            public bool HasComplexClassConflict
            =>
                Building?.Conflict != null &&
                Building.Conflict.Any(x => x.ConflictValueType == ConflictValueType.ComplexClass);
    }
```
Still not calls `NotifyOfPropertyChange()` for property `HasComplexClassConflict` when `Building` changed  in this case:
```
  public class BuildingCardViewModelBase : CardViewModelBase
    {
           public virtual Building Building { get; set; }
    }


public class OperatorBuildingCardViewModel : BuildingCardViewModelBase
    {
          //! Added Building property overriding
           public override Building Building { get; set; }
           
           public bool HasComplexClassConflict
            =>
                Building?.Conflict != null &&
                Building.Conflict.Any(x => x.ConflictValueType == ConflictValueType.ComplexClass);
    }
```
Calls `NotifyOfPropertyChange()` for property `HasComplexClassConflict` when `Building` changed only in this case:
```
  public class BuildingCardViewModelBase : CardViewModelBase
    {
           public virtual Building Building { get; set; }
    }


public class OperatorBuildingCardViewModel : BuildingCardViewModelBase
    {
           //! Notifying manually added
           [AlsoNotifyFor(nameof(HasComplexClassConflict)]
           public override Building Building { get; set; }
           
           public bool HasComplexClassConflict
            =>
                Building?.Conflict != null &&
                Building.Conflict.Any(x => x.ConflictValueType == ConflictValueType.ComplexClass);
    }
```
I expected it should work in case 1. 
Great library!

**Comment by distantcam** [comment]
Case 1 is not possible because the notification for the subclass `OperatorBuildingCardViewModel` has to be done in the base class `BuildingCardViewModelBase` which is bad object orientation. A base class should not know about subclasses.

I would have thought case 2 would work, but I'm not certain. @SimonCropp can you confirm?

**Comment by AsValeO** [comment]
Why can't PropertyChanged.Fody automatically override properties in case like this?

**Comment by SimonCropp** [comment]
@AsValeO in theory it probably could. But it would be enabling a design that will cause you long term pain. You would be much better served long term by just duplicating the Building  property in child classes. If u need to treat the base in common code scenarios then you can achieve this using an interface instead of a base class

**Comment by AsValeO** [comment]
I'm now reinvertigating case 2.
I think case 1 definetely should work. I expect from PropertyChanged.Fody to **completely** forget about headache with notifying. But if case 1 not works I get another headache with remembering to reimplement properties. I can't work without a base classes.

**Comment by AsValeO** [comment]
**NEW INFO FOR CASE 2:**

Method `OnBuildingChanged()` of base class `BuildingCardViewModelBase` not calls if `Building` property overrided:

```
  public class BuildingCardViewModelBase : CardViewModelBase
    {
           public virtual Building Building { get; set; }
           //! Not calls
           protected void OnBuildingChanged()
        {
            BuildingPhoto = Building.BuildingPhoto.SingleOrDefault(x => x.Main) ??
                            Building.BuildingPhoto.FirstOrDefault();
        }
    }


public class OperatorBuildingCardViewModel : BuildingCardViewModelBase
    {
          //! Added Building property overriding
           public override Building Building { get; set; }
           
           public bool HasComplexClassConflict
            =>
                Building?.Conflict != null &&
                Building.Conflict.Any(x => x.ConflictValueType == ConflictValueType.ComplexClass);
    }
```
If I override `OnBuildingChanged()` also, it works.
 ```
protected override void OnBuildingChanged()
        {
            base.OnBuildingChanged();
        }
```

**Comment by AsValeO** [comment]
I've discovered some info about LSP principle. Now I understand better why CASE 1 is not implemented.

**Comment by SimonCropp** [comment]
Can u upload a simplifed repro somewhere. Ideally with the fewest moving pieces that reproduces the problem
