### ISSUE TITLE
VS2017 nuget pack issue

### ISSUE THREAD

**Issue by tofutim** [Fody/PropertyChanged#255]
I am using Fody PropertyChanged 2.1.1. Adding PropertyChanged should not add Fody PropertyChanged to the nuget requirements of a nupkg. When I 'pack' using VS2017, I end up with

    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="PCLStorage" version="1.0.2" exclude="Build,Analyzers" />
        <dependency id="PCLSpecialFolder" version="1.1.0" exclude="Build,Analyzers" />
        **<dependency id="PropertyChanged.Fody" version="2.1.1" exclude="Build,Analyzers" />**
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNet.SignalR.Client" version="2.2.2" exclude="Build,Analyzers" />
      </group>
    </dependencies>

I also use GitVersionTask, which does not show up. So there may be a special flag that needs to be added so that it does not get sucked into the nuspec.

This may help: https://github.com/GitTools/GitVersion/issues/1188 - I think somehow the solution is getting PrivateAssets = true per https://github.com/NuGet/Home/issues/4125 - thread discusses how developmentDependency should automatically set this to true, but then it doesn't.

**Comment by bording** [comment]
You can just manually add `PrivateAssets = "All"` to your package references that need them. Take a look at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj and https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files for more information.

**Comment by SimonCropp** [comment]
Also the package is marked as a development dependency. It is a bug that the new csproj system doesn't respect that https://github.com/NuGet/Home/issues/4125
