### ISSUE TITLE
Failure in UWP Application Certification

### ISSUE THREAD

**Issue by justinmann** [Fody/PropertyChanged#256]
I got the following error:
Error Found: The debug configuration test detected the following errors:
The binary PropertyChanged.dll is built in debug mode.

Is it possible in the 2.1.1 version you pushed a debug build to nuget?

**Comment by SimonCropp** [comment]
You should not be packaging propertychanged.dll so the build config is irrelevant

**Comment by justinmann** [comment]
I did not actively add propertychanged.dll to the build config. It is being included automatically when add this package using nuget. I do not see any documentation on how to prevent this file from being included in the appxupload sent to MSFT when submitting an app.

**Comment by SimonCropp** [comment]
given this is not problem this project perhaps asking "how do i prevent a file from being included in the appxupload sent to MSFT when submitting an app." as a stackoverflow question would get you better results?

**Comment by justinmann** [comment]
I just removed Fody from my project. I was just notifying you in case you
wanted to encourage developers to use your product in UWP apps.

**Comment by SimonCropp** [comment]
sounds like a good decision
