### ISSUE TITLE
Failing in VS2017 for Mac

### ISSUE THREAD

**Issue by tofutim** [Fody/PropertyChanged#258]
Works in VS2017 on Windows, but for Mac, I get
```

Error: Fody: An unhandled exception occurred:
Exception:
Object reference not set to an instance of an object
StackTrace:
  at ModuleWeaver.FindCoreReferences () [0x00023] in <751e1554e80f4c618d8f0db19d37b638>:0 
  at ModuleWeaver.Execute () [0x00012] in <751e1554e80f4c618d8f0db19d37b638>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
  at InnerWeaver.ExecuteWeavers () [0x00087] in <1514fb4c253743788604621fdec363e1>:0 
  at InnerWeaver.Execute () [0x00030] in <1514fb4c253743788604621fdec363e1>:0 
Source:
PropertyChanged.Fody
TargetSite:
Void FindCoreReferences()
 (Kumquat.Common)
```

Target file was a VS2017-style csproj created in VS2017 in Windows. The csproj looks like

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.3' ">portable-net45+win81</PackageTargetFallback>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;LIBLOG_PORTABLE LIBLOG_PUBLIC</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;LIBLOG_PORTABLE LIBLOG_PUBLIC</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="FodyWeavers.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="FodyWeavers.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitVersionTask" Version="3.6.5" PrivateAssets="All" />
    <PackageReference Include="PropertyChanged.Fody" Version="2.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.2.2" />
    <PackageReference Include="PCLSpecialFolder" Version="1.1.0" />
    <PackageReference Include="PCLStorage" Version="1.0.2" />
  </ItemGroup>

</Project>
```
And the FodyWeavers.xml is the usual 
```

<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PropertyChanged EventInvokerNames="RaisePropertyChange"/>
</Weavers>
```

**Comment by tofutim** [comment]
Something else must be going on, I started a new project and it seems to work now.

**Comment by tofutim** [comment]
That was just my imagination. Still doesn't work. VS2017 for Mac.

**Steps:**
1. Create a new .NET Standard Library
![image](https://user-images.githubusercontent.com/157766/26990174-95246500-4d0a-11e7-940e-13ebb42c7ada.png)
2. Modify the default class to 
```
using System;
using System.ComponentModel;

namespace Kumquat.Common2
{
    public class Class1 : INotifyPropertyChanged
    {
		public event PropertyChangedEventHandler PropertyChanged;

        public string Message { get; set; }
	}
}
```
3. Add PropertyChanged.Fody 2.1.1
4. Add FodyWeavers.xml
```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PropertyChanged EventInvokerNames="RaisePropertyChange"/>
</Weavers>

```
5. Build to see error
![image](https://user-images.githubusercontent.com/157766/26990258-e5e7fb28-4d0a-11e7-9e82-94b016a62828.png)

**Comment by tofutim** [comment]
this suggests it might be a nuget version issue?
https://github.com/Fody/PropertyChanged/issues/205

**Comment by tofutim** [comment]
Or maybe it is just because I need to specify a "RaisedPropertyChanged function?

**Comment by SimonCropp** [comment]
I don't think that is it. Can u upload somewhere your system.dll mscorlib.dll and system.runtime.dll that your solution is pointing to

**Comment by tofutim** [comment]
Hi Simon, thank you for writing back. I'm not sure how to find it in VS2017 for Mac, but I will look. I just checked, and if I create a PCL then switch it to netstandard14, PropertyChanged.Fody works just fine. But if I am using the new SDK format, it fails with that error.

**Comment by SimonCropp** [comment]
Yeah it will be because they resolve to different dlls. Turn your build log to verbose and look for those files in the text output. That should give u the full path

**Comment by tofutim** [comment]
I see this. I'm not confused because sometimes I cannot replicate the error but sometimes I can. I'll test some more on a cleaner project.

>         Fody/PropertyChanged:   Executing Weaver 
>         Fody/PropertyChanged: Can not find 'mscorlib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
>     Tried:
>     /Users/tim/.nuget/packages/folderpath/1.1.0/lib/portable-net45+netcore45+wpa81/FolderPath.Abstractions.dll
>     /Users/tim/.nuget/packages/folderpath/1.1.0/lib/portable-net45+netcore45+wpa81/FolderPath.dll
>     /Users/tim/.nuget/packages/microsoft.aspnet.signalr.client/2.2.2/lib/netstandard1.3/Microsoft.AspNet.SignalR.Client.dll
>     /Users/tim/.nuget/packages/microsoft.csharp/4.0.1/ref/netstandard1.0/Microsoft.CSharp.dll
>     /Users/tim/.nuget/packages/microsoft.win32.primitives/4.3.0/ref/netstandard1.3/Microsoft.Win32.Primitives.dll
>     /Users/tim/.nuget/packages/newtonsoft.json/9.0.1/lib/netstandard1.0/Newtonsoft.Json.dll
>     /Users/tim/.nuget/packages/pclspecialfolder/1.1.0/lib/portable-net45+netcore45+wpa81/PCLSpecialFolder.Abstractions.dll
>     /Users/tim/.nuget/packages/pclspecialfolder/1.1.0/lib/portable-net45+netcore45+wpa81/PCLSpecialFolder.dll
>     /Users/tim/.nuget/packages/pclstorage/1.0.2/lib/portable-net45+wp8+wpa81+win8+monoandroid+monotouch+Xamarin.iOS+Xamarin.Mac/PCLStorage.Abstractions.dll
>     /Users/tim/.nuget/packages/pclstorage/1.0.2/lib/portable-net45+wp8+wpa81+win8+monoandroid+monotouch+Xamarin.iOS+Xamarin.Mac/PCLStorage.dll
>     /Users/tim/.nuget/packages/propertychanged.fody/2.1.1/lib/netstandard1.0/PropertyChanged.dll
>     /Users/tim/.nuget/packages/system.appcontext/4.3.0/ref/netstandard1.3/System.AppContext.dll
>     /Users/tim/.nuget/packages/system.collections.concurrent/4.3.0/ref/netstandard1.3/System.Collections.Concurrent.dll
>     /Users/tim/.nuget/packages/system.collections/4.3.0/ref/netstandard1.3/System.Collections.dll
>     /Users/tim/.nuget/packages/system.console/4.3.0/ref/netstandard1.3/System.Console.dll
>     /Users/tim/.nuget/packages/system.diagnostics.debug/4.3.0/ref/netstandard1.3/System.Diagnostics.Debug.dll
>     /Users/tim/.nuget/packages/system.diagnostics.tools/4.3.0/ref/netstandard1.0/System.Diagnostics.Tools.dll
>     /Users/tim/.nuget/packages/system.diagnostics.tracing/4.3.0/ref/netstandard1.3/System.Diagnostics.Tracing.dll
>     /Users/tim/.nuget/packages/system.dynamic.runtime/4.0.11/ref/netstandard1.3/System.Dynamic.Runtime.dll
>     /Users/tim/.nuget/packages/system.globalization.calendars/4.3.0/ref/netstandard1.3/System.Globalization.Calendars.dll
>     /Users/tim/.nuget/packages/system.globalization/4.3.0/ref/netstandard1.3/System.Globalization.dll
>     /Users/tim/.nuget/packages/system.io.compression.zipfile/4.3.0/ref/netstandard1.3/System.IO.Compression.ZipFile.dll
>     /Users/tim/.nuget/packages/system.io.compression/4.3.0/ref/netstandard1.3/System.IO.Compression.dll
>     /Users/tim/.nuget/packages/system.io.filesystem.primitives/4.3.0/ref/netstandard1.3/System.IO.FileSystem.Primitives.dll
>     /Users/tim/.nuget/packages/system.io.filesystem/4.3.0/ref/netstandard1.3/System.IO.FileSystem.dll
>     /Users/tim/.nuget/packages/system.io/4.3.0/ref/netstandard1.3/System.IO.dll
>     /Users/tim/.nuget/packages/system.linq.expressions/4.3.0/ref/netstandard1.3/System.Linq.Expressions.dll
>     /Users/tim/.nuget/packages/system.linq/4.3.0/ref/netstandard1.0/System.Linq.dll
>     /Users/tim/.nuget/packages/system.net.http/4.3.0/ref/netstandard1.3/System.Net.Http.dll
>     /Users/tim/.nuget/packages/system.net.primitives/4.3.0/ref/netstandard1.3/System.Net.Primitives.dll
>     /Users/tim/.nuget/packages/system.net.sockets/4.3.0/ref/netstandard1.3/System.Net.Sockets.dll
>     /Users/tim/.nuget/packages/system.objectmodel/4.3.0/ref/netstandard1.3/System.ObjectModel.dll
>     /Users/tim/.nuget/packages/system.reflection.extensions/4.3.0/ref/netstandard1.0/System.Reflection.Extensions.dll
>     /Users/tim/.nuget/packages/system.reflection.primitives/4.3.0/ref/netstandard1.0/System.Reflection.Primitives.dll
>     /Users/tim/.nuget/packages/system.reflection/4.3.0/ref/netstandard1.3/System.Reflection.dll
>     /Users/tim/.nuget/packages/system.resources.resourcemanager/4.3.0/ref/netstandard1.0/System.Resources.ResourceManager.dll
>     /Users/tim/.nuget/packages/system.runtime.extensions/4.3.0/ref/netstandard1.3/System.Runtime.Extensions.dll
>     /Users/tim/.nuget/packages/system.runtime.handles/4.3.0/ref/netstandard1.3/System.Runtime.Handles.dll
>     /Users/tim/.nuget/packages/system.runtime.interopservices.runtimeinformation/4.3.0/ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll
>     /Users/tim/.nuget/packages/system.runtime.interopservices/4.3.0/ref/netstandard1.3/System.Runtime.InteropServices.dll
>     /Users/tim/.nuget/packages/system.runtime.numerics/4.3.0/ref/netstandard1.1/System.Runtime.Numerics.dll
>     /Users/tim/.nuget/packages/system.runtime.serialization.primitives/4.1.1/ref/netstandard1.3/System.Runtime.Serialization.Primitives.dll
>     /Users/tim/.nuget/packages/system.runtime/4.3.0/ref/netstandard1.3/System.Runtime.dll
>     /Users/tim/.nuget/packages/system.security.cryptography.algorithms/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Algorithms.dll
>     /Users/tim/.nuget/packages/system.security.cryptography.encoding/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Encoding.dll
>     /Users/tim/.nuget/packages/system.security.cryptography.primitives/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Primitives.dll
>     /Users/tim/.nuget/packages/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.3/System.Security.Cryptography.X509Certificates.dll
>     /Users/tim/.nuget/packages/system.text.encoding.extensions/4.3.0/ref/netstandard1.3/System.Text.Encoding.Extensions.dll
>     /Users/tim/.nuget/packages/system.text.encoding/4.3.0/ref/netstandard1.3/System.Text.Encoding.dll
>     /Users/tim/.nuget/packages/system.text.regularexpressions/4.3.0/ref/netstandard1.3/System.Text.RegularExpressions.dll
>     /Users/tim/.nuget/packages/system.threading.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.dll
>     /Users/tim/.nuget/packages/system.threading.timer/4.3.0/ref/netstandard1.2/System.Threading.Timer.dll
>     /Users/tim/.nuget/packages/system.threading/4.3.0/ref/netstandard1.3/System.Threading.dll
>     /Users/tim/.nuget/packages/system.xml.readerwriter/4.3.0/ref/netstandard1.3/System.Xml.ReaderWriter.dll
>     /Users/tim/.nuget/packages/system.xml.xdocument/4.3.0/ref/netstandard1.3/System.Xml.XDocument.dll
>     MSBUILD : error : Fody: An unhandled exception occurred:
>     MSBUILD : error : Exception:
>     MSBUILD : error : Object reference not set to an instance of an object
>     MSBUILD : error : StackTrace:
>     MSBUILD : error :   at ModuleWeaver.FindCoreReferences () [0x00023] in <751e1554e80f4c618d8f0db19d37b638>:0 
>     MSBUILD : error :   at ModuleWeaver.Execute () [0x00012] in <751e1554e80f4c618d8f0db19d37b638>:0 
>     MSBUILD : error :   at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
>     MSBUILD : error :   at InnerWeaver.ExecuteWeavers () [0x00087] in <1514fb4c253743788604621fdec363e1>:0 
>     MSBUILD : error :   at InnerWeaver.Execute () [0x00030] in <1514fb4c253743788604621fdec363e1>:0 
>     MSBUILD : error : Source:
>     MSBUILD : error : PropertyChanged.Fody
>     MSBUILD : error : TargetSite:
>     MSBUILD : error : Void FindCoreReferences()
>     MSBUILD : error : 
>       Fody:   Finished Fody 12ms.
>   Done executing task "Fody.WeavingTask" -- FAILED.
> Done building target "FodyTarget" in project "Kumquat.Common.csproj" -- FAILED.
> Target "_DefaultMicrosoftNETPlatformLibrary" in file "/Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets":
> Done building target "_DefaultMicrosoftNETPlatformLibrary" in project "Kumquat.Common.csproj".
> Target "ComputeDependencyFileCompilerOptions" skipped, due to false condition; ('$(PreserveCompilationContext)' == 'true') was evaluated as ('' == 'true').
> Target "GenerateBuildDependencyFile" in file "/Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets":
>

**Comment by SimonCropp** [comment]
Can u also add an explicit reference to fody. There is a bug in nuget which means it will always resolve to the lowest, and most buggy, version of any transitive reference.

**Comment by SimonCropp** [comment]
And I actually need the binaries of those files. Not just the paths

**Comment by tofutim** [comment]
Simon, adding the newest version of Fody (2.1.0) solves the problem! I totally forgot about this. Thank you so much.

**Comment by SimonCropp** [comment]
Ahhh. Ok so it was caused by an underlying bug fix in the assembly resolution of of Cecil. 

Glad it is working for you. And sorry about the nuget bug, I have fought the battle to get that fixed several times and the answer has always been "by design"

**Comment by tofutim** [comment]
I appreciate you being there Simon.
