### ISSUE TITLE
Property dependencies call on property change before affecting the new value.

### ISSUE THREAD

**Issue by malylemire1** [Fody/PropertyChanged#260]
`public string GivenNames { get; set; }

    public string FamilyName { get; set; }

    public string FullName
    {
        get
        {
            return string.Format("{0} {1}", GivenNames, FamilyName);
        }
    }`

Full name propertychanged is raised before setting the actual value of givennames or familyname.

This happen with before/after enabled on property changed.

Also, Is there a way to completely disable automatic property dependencies?

**Comment by n00bje** [comment]
> Full name propertychanged is raised before setting the actual value of givennames or familyname.

OnPropertyChanged("FullName") will be called before OnPropertyChanged("GivenNames") or OnPropertyChanged("FamilyName") BUT the value of GivenNames / FamilyName will already be set by then. This means FullName will output the expected value.

I used this code to test this:
```
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        var person = new Person();

        Console.WriteLine("Changing GivenNames to 'Fody'...");
        person.GivenNames = "Fody";

        Console.WriteLine("\nChanging FamilyName to 'Weaver'...");
        person.FamilyName = "Weaver";
    }
}

public class Person : INotifyPropertyChanged
{
    public string GivenNames { get; set; }
    public string FamilyName { get; set; }
    public string FullName => $"{GivenNames} {FamilyName}";

    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        Console.WriteLine($"OnPropertyChanged({propertyName}) called");
        Console.WriteLine($"FullName = {FullName}");
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
```

This is the output:

> Changing GivenNames to 'Fody'...
> OnPropertyChanged(FullName) called
> FullName = Fody 
> OnPropertyChanged(GivenNames) called
> FullName = Fody 
> 
> Changing FamilyName to 'Weaver'...
> OnPropertyChanged(FullName) called
> FullName = Fody Weaver
> OnPropertyChanged(FamilyName) called
> FullName = Fody Weaver

> Also, Is there a way to completely disable automatic property dependencies?
As far as I know, there is no way to disable this.

**Comment by malylemire1** [comment]
Did you try with :
protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null), object before, object after)

**Comment by malylemire1** [comment]
Anyone can reproduce the problem?

**Comment by n00bje** [comment]
I'm not sure what you're trying to do because 
`return String.Format("test", GivenNames.ToLowerInvariant()); `
will ALWAYS return "test", no matter what the value of GivenNames is.

**Comment by malylemire1** [comment]
It's just an example to show the null value in GivenNames.

You can test with :

`return String.Format("test{0}", GivenNames.ToLowerInvariant());`

**Comment by n00bje** [comment]
I decompiled the generated code and this is what's really happening:

```
private string givenNames;
public string GivenNames
{
    get
    {
        return givenNames;
    }
    set
    {
        if (string.Equals(givenNames, value, StringComparison.Ordinal))
            return;

        var givenNamesBefore = GivenNames;
        var fullNameBefore = FullName;

        givenNames = value;

        var fullNameAfter = FullName;
        OnPropertyChanged("FullName", fullNameBefore, fullNameAfter);

        var givenNamesAfter = GivenNames;
        OnPropertyChanged("GivenNames", givenNamesBefore, givenNamesAfter);
    }
}

public string FullName
{
    get
    {
        var format = "test{0}";
        var givenNames = GivenNames;
        var str = givenNames.ToLowerInvariant();
        return string.Format(format, str);
    }
}
```

The setter of GivenNames calls the getter of FullName which calls GivenNames.ToLowerInvariant(). GivenNames is initially null so any method called on GivenNames fails.

What you could do is initialize your properties like so:

```
public string GivenNames { get; set; } = ""
public string FamilyName { get; set; } = ""
```

Or use the [Null-conditional Operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators) like so:

```
public String FullName
{
    get
    {
        return String.Format("test{0}", GivenNames?.ToLowerInvariant());
    }
}
```

Or use your own OnPropertyChanged event which doesn't require the 'before' value:
https://github.com/Fody/PropertyChanged/wiki/EventInvokerSelectionInjection

**Comment by malylemire1** [comment]
Hi,

Thanks for the detailed decompiled information.
I already corrected the problem with the null-conditional operator in a small project.
The problem is that I have a huge project were I need to enable before/after values.
There's a lot of code with the property dependencies pattern were I would have to put null-contitional in.

Is there a way to add a global configuration to disable this feature?

Thanks

**Comment by malylemire1** [comment]
Hi,

With version 2.1.4 there is even more dependent property changed raising.
There should be an option to deactivate this feature. It's too expensive if you have round trips to the database when dependent property changed is called.

Thanks

**Comment by SimonCropp** [comment]
> With version 2.1.4 there is even more dependent property changed raising.

how so?

**Comment by malylemire1** [comment]
This property dependent changed is not raised in 2.1.2 
```

Warranties = new EquipmentWarrantyListViewModel(); //Raise HasWarrantyOrMaintenances property changed.

public bool HasWarrantyOrMaintenances { get { return !Warranties.IsEmpty || !Maintenances.IsEmpty; } }
```

**Comment by SimonCropp** [comment]
I will accept a PR that adds condig to disable automatic dependent property detection
