### ISSUE TITLE
Installing multiple versions of PropertyChanged breaks compilation

### ISSUE THREAD

**Issue by alikaraki** [Fody/PropertyChanged#261]
Situation: we have multiple projects using different versions of PropertyChanged. We recently changed all these projects to install their NuGet packages into one 'packages' folder. After this change the projects using the older version of Fody do not compile due to a FileLoadException. If we delete the newer Fody.PropertyChanged package from the packages folder then the build works fine.

Exception
`16>    Fody: Fody (version 1.29.2.0) Executing
16>MSBUILD : error : Fody: Could not load 'ModuleWeaver' from 'PropertyChanged.Fody, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null' due to ReflectionTypeLoadException.
16>MSBUILD : error : It is possible you need to update the package.
16>MSBUILD : error : exception.LoaderExceptions:
16>MSBUILD : error : System.IO.FileLoadException: Could not load file or assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
16>MSBUILD : error : File name: 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' ---> System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
16>MSBUILD : error : 
16>MSBUILD : error : 
16>MSBUILD : error : System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
16>MSBUILD : error : System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
16>MSBUILD : error : 
16>    Fody:   Finished Fody 93ms.`

Project A packages 
`<package id="Fody" version="1.29.2" targetFramework="net452" developmentDependency="true" />
  <package id="PropertyChanged.Fody" version="1.52.1" targetFramework="net452" developmentDependency="true" />`

Project B packages
`<package id="Fody" version="2.0.0" targetFramework="net461" developmentDependency="true" />
  <package id="PropertyChanged.Fody" version="2.1.2" targetFramework="net461" developmentDependency="true" />`

Project A does not build when PropertyChanged.Fody.2.1.2 is installed. When this package is deleted Project A builds fine. Project B always builds with no issues.

**Comment by FrancoisM** [comment]
Just opened a SOF question with similar issue:
https://stackoverflow.com/questions/44859251/propertychanged-fody-conflict-between-solutions-using-version-1-and-2

**Comment by SimonCropp** [comment]
Unfortunately this is very difficult to fix in the old cs project system

Is it possible for you to move the the new 2017 csproj system?

**Comment by FrancoisM** [comment]
Not really:
1°) I use libraries which require .Net Framework
2°) I have about 20 projects in that solution, migrating to .Net Standard would be painful.

**Comment by SimonCropp** [comment]
The new csproj system can target any version of .net. U dont need to migrate to netstandard

**Comment by SimonCropp** [comment]
For example https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/PropertyChanged.Fody.csproj

**Comment by FrancoisM** [comment]
Didn't know. That's great news tks.
However, how does this help with the issue described here?

**Comment by FrancoisM** [comment]
Well actually new csproj format is not available for PCLs.

**Comment by SimonCropp** [comment]
The new project system exposes the path to the nuget package on build. So we can correctly resolve package versions. 

Too bad about pcls. Microsoft seems to have decided to make them legacy as part of the vs 2017 changes. They are now on life support. So your options are, for where u use pcls

 * update to netstandard to replace pcls
 * or dont have a shared package dir for projects that use diff fody weaver versions

**Comment by FrancoisM** [comment]
I'll go with option 2 for legacy projects.
Tks for your support.

**Comment by InquisitorJax** [comment]
I get this issue when upgrading Fody on a branch for a github PR.
Returning to other branches with the old package reference is then broken.
recommendations for a fix?
