### ISSUE TITLE
NETStandard 2.0 - "Fody: An unhandled exception occurred"

### ISSUE THREAD

**Issue by OrihuelaConde** [Fody/PropertyChanged#262]
5> Fody: Fody (version 2.1.0.0) Executing 5>MSBUILD : error : Fody: An unhandled exception occurred: 5>MSBUILD : error : Exception: 5>MSBUILD : error : La secuencia no contiene ningún elemento coincidente 5>MSBUILD : error : StackTrace: 5>MSBUILD : error : en System.Linq.Enumerable.First[TSource](IEnumerable1 source, Func2 predicate) 5>MSBUILD : error : en ModuleWeaver.ExecuteWinRT() 5>MSBUILD : error : en ModuleWeaver.FindCoreReferences() 5>MSBUILD : error : en ModuleWeaver.Execute() 5>MSBUILD : error : en lambda_method(Closure , Object ) 5>MSBUILD : error : en InnerWeaver.ExecuteWeavers() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 181 5>MSBUILD : error : en InnerWeaver.Execute() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 86 5>MSBUILD : error : Source: 5>MSBUILD : error : System.Core 5>MSBUILD : error : TargetSite: 5>MSBUILD : error : TSource First[TSource](System.Collections.Generic.IEnumerable1[TSource], System.Func2[TSource,System.Boolean]) 5>MSBUILD : error : 5> Fody: Finished Fody 21ms.

NETStandard.Library 2.0-preview3
Visual Studio 2017 15.3 Preview 2

**Comment by jianliulin** [comment]
me too,please help

**Comment by Dids** [comment]
Any updates on this? Also seeing it and so far haven't found a solution/workaround.

**Comment by Dids** [comment]
Also related:
https://github.com/Fody/Fody/issues/374

**Comment by virzak** [comment]
I am having the same issue. Please help:

`
1>  Fody: Fody (version 2.0.0.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Sequence contains no matching element
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
1>MSBUILD : error :    at ModuleWeaver.ExecuteWinRT()
1>MSBUILD : error :    at ModuleWeaver.FindCoreReferences()
1>MSBUILD : error :    at ModuleWeaver.Execute()
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 83
1>MSBUILD : error : Source:
1>MSBUILD : error : System.Core
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
1>MSBUILD : error :
1>  Fody:   Finished Fody 38ms.
`

**Comment by Dids** [comment]
Needs to be fixed in Fody, I think.

**Comment by BrunoJuchli** [comment]
@virzak  have you tested the latest Fody version (2.1.2)?

**Comment by virzak** [comment]
@BrunoJuchli Yeah, I think that fixed that!

**Comment by Dids** [comment]
.NET Standard 2.0 library, Fody 2.1.2 and PropertyChanged.Fody 2.1.3 still throws the following:

```
MSBUILD : error : Fody: An unhandled exception occurred:
MSBUILD : error : Exception:
MSBUILD : error : Sequence contains no matching element
MSBUILD : error : StackTrace:
MSBUILD : error :   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00012] in /private/tmp/source-mono-d15-3/bockbuild-d15-3/profiles/mono-mac-xamarin/build-root/mono-x64/external/corefx/src/System.Linq/src/System/Linq/First.cs:34 
MSBUILD : error :   at ModuleWeaver.ExecuteWinRT () [0x0002d] in C:\projects\propertychanged\PropertyChanged.Fody\MsCoreReferenceFinder.cs:98 
MSBUILD : error :   at ModuleWeaver.FindCoreReferences () [0x0006b] in C:\projects\propertychanged\PropertyChanged.Fody\MsCoreReferenceFinder.cs:30 
MSBUILD : error :   at ModuleWeaver.Execute () [0x00012] in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:26 
MSBUILD : error :   at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
MSBUILD : error :   at InnerWeaver.ExecuteWeavers () [0x00087] in <981075239eb84cdc8517dfa0ff3a349e>:0 
MSBUILD : error :   at InnerWeaver.Execute () [0x0004d] in <981075239eb84cdc8517dfa0ff3a349e>:0 
MSBUILD : error : Source:
MSBUILD : error : System.Core
MSBUILD : error : TargetSite:
MSBUILD : error : Mono.Cecil.TypeDefinition First[TypeDefinition](System.Collections.Generic.IEnumerable`1[Mono.Cecil.TypeDefinition], System.Func`2[Mono.Cecil.TypeDefinition,System.Boolean])
MSBUILD : error : 
    0 Warning(s)
    1 Error(s)
```

**Comment by virzak** [comment]
@BrunoJuchli Turns out it is still broken. It worked with Standard 1.6, but not with 2.0

**Comment by tmm360** [comment]
Same here

**Comment by OrihuelaConde** [comment]
Still broken on NETStandard 2.0, Fody 2.1.2 and PropertyChanged 2.1.3.

**Comment by Haadka** [comment]
Hi I am getting this error again in 2.2.1 (2.2.0 is fine)

**Comment by SimonCropp** [comment]
@OrihuelaConde can u upload a repro
