### ISSUE TITLE
Could not install package 'PropertyChanged.Fody 2.1.2' into .Net 4.0 targeted project.

### ISSUE THREAD

**Issue by shibormot** [Fody/PropertyChanged#263]
While installing into class library project with target framework = '.Net Framework 4' I get error message:

> Could not install package 'PropertyChanged.Fody 2.1.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am using Visual Studio 2015 and NuGet 3.4.4

**Comment by cremor** [comment]
PropertyChanged.Fody supports .NET Standard 1.0, which is supported by version 4.5 of the .NET framework. So you need to update to at least 4.5.

Note that anything older than 4.5.2 isn't even supported by Microsoft any more.

**Comment by SimonCropp** [comment]
Yeah sorry, @cremor is correct. .net 4 is not supported
