### ISSUE TITLE
Property depending on Caliburn ActiveItem

### ISSUE THREAD

**Issue by darxis** [Fody/PropertyChanged#269]
I am using Caliburn.Micro package for a WPF project.

I am trying to make a "Back" button only active/visible when the currently active item in a conductor is an exact ViewModel. So I annotate a bool property like this:
```
public class MyViewModel : Conductor<Screen>.Collection.OneActive
{
    public ChildViewModel ChildViewModel1 { get; set; }

    public ChildViewModel ChildViewModel2 { get; set; }

    public MyViewModel(ChildViewModel childViewModel1, ChildViewModel childViewModel2)
    {
        ChildViewModel1 = childViewModel1;
        ChildViewModel2 = childViewModel2;
        ActivateItem(ChildViewModel1);
    }

    // We can go back to the first VM only when it is not the active one
    [DependsOn(nameof(ActiveItem))]
    public bool CanGoBack => ActiveItem != ChildViewModel1;
    
    public void GoBack()
    {
        // Go back to the first ViewModel
        ActivateItem(ChildViewModel1);
    }
}
```

However, it is not working. I guess it is not because ActiveItem is a property within the Caliburn ConductorBaseWithActiveItem class, which I don't have sources when compiling, and thus Fody/PropertyChanged does not generates code in its setter to notify the `CanGoBack` property.

How can I make this work (the clean way)? Is it even possible using the Fody/PropertyChanged library, or do I have to override the `OnPropertyChanged` method and listen for changes of `ActiveItem`?

**Comment by distantcam** [comment]
Caliburn Micro's `ConductorBase` has an `ActivationProcessed` event you could use to handle this case.

    ActivationProcessed += (s, e) => CanGoBack = ActiveItem != ChildViewModel1;

**Comment by darxis** [comment]
Ok, I though there was a way to achieve it using only attributes :/

**Comment by distantcam** [comment]
Not really. Activation is a Caliburn Micro concern, so the best way is to just use Caliburn Micro to handle it.
