### ISSUE TITLE
Question: How are initialized properties compiled?

### ISSUE THREAD

**Issue by weitzhandler** [Fody/PropertyChanged#272]
Hi, what would this be compiled to:

    [ImplementPropertyChanged]
    public class Patient
    {
      public string Address { get; set; } = new Address();
    }

**Comment by SimonCropp** [comment]
Open it in a decompiler and see

**Comment by weitzhandler** [comment]
ok, until i do it, just for the reference, an NPC isn't raised for those properties at initialization (and it probably shouldn't).
