### ISSUE TITLE
Question regarding the (deprecated) behaviour of ImplementPropertyChanged

### ISSUE THREAD

**Issue by lennartb-** [Fody/PropertyChanged#274]
I just updated PropertyChange.Fody and saw the deprecation warning. No biggie, but now I don't really understand the role of the attribute before it was deprecated.

The docs of the new, re-introduced attribute say

> Specifies that the class will be marked with INotifyPropertyChanged. Note that all classes that implement INotifyPropertyChanged will have property notification injected irrespective of the use of this attribute.

The old docs said 
> Allows the injection of the INotifyPropertyChanged interface.

As I understand:
1. PropertyChanged class gets weaved in if a class implements INotifyPropertyChanged, no matter if I add the attribute or not
2. The attribute makes the class implement INotifyPropertyChanged if it is not implemented

What was the use of the Attribute before then? Was it merely a convenience attribute (you don't need to explicitly implement INotifyPropertyChanged because an attribute looks nicer) or...? I probably used it wrong the whole time, I just want to understand why.

**Comment by distantcam** [comment]
A lot of people assumed it was an opt-in way of enabling weaving, and that classes without the attribute that still implement `INotifyPropertyChanged` would not be weaved.

**Comment by lennartb-** [comment]
Ok, and what were the actual uses of ImplementPropertyChanged?

**Comment by SimonCropp** [comment]
see the second last point here https://github.com/Fody/PropertyChanged#notes

**Comment by lennartb-** [comment]
Yeah, I read this, but I don't understand fully what that means. Is it merely another way to implement INotifyPropertyChanged on a class (which isn't marked with INotifyPropertyChanged)?

**Comment by SimonCropp** [comment]
yes

**Comment by lennartb-** [comment]
Great, thank you!
