### ISSUE TITLE
PropertyChanged doesn't fire changing a property from a command

### ISSUE THREAD

**Issue by dscham** [Fody/PropertyChanged#276]
I got this project here https://github.com/dscham/iStorage/tree/mvvm

On Line 82 and 83 in the file /viemodels/MainWindowViewModel.cs
PropertyChanged doesn't automatically fire and i couldn't figure out why.

The function is called by the ICommand DoLogut, Line 61

Sorry about no comments in the code, it's a collegeproject i want to get done quickly.

EDIT: Had the wrong link, added more info

**Comment by dscham** [comment]
Okay, after updating Fody and PropertyChanged.Fody it doesn't work at all anymore. Switched back to implementing fire of PropertyChanged myself.
Maybe you'll figure out why it won't work.

**Comment by SimonCropp** [comment]
can u please share a isolated repro that illustrates the problem

**Comment by lhughey** [comment]
Did you overwrite your FodyWeavers.xml file?  I see you're not importing the PropertyChanged functionality into the file.

**Comment by dscham** [comment]
I abanndoned the project... Sorry
Got a new job and didn't have time. Semester had ended and we got a positive mark on the project so...
Thanks for trying to help though.

If I have enought time i'll see if it was my fault, and not a bug after all.
For now i'll close the issue.
