### ISSUE TITLE
CS0067 Event is Never Used

### ISSUE THREAD

**Issue by mysteryx93** [Fody/PropertyChanged#277]
ImplementPropertyChangedAttribute has been deprecated. I thus add INotifyPropertyChanged and declare the event.

This results in a CS0067 warning for every such event that is not used (until PropertyChanged generates its code).

Any way to avoid these warnings?

**Comment by BrunoJuchli** [comment]
The deprecated-notice states

> [...]This attribute has been **replaced by AddINotifyPropertyChangedInterfaceAttribute**.

So if you want to retain the same behavior just replace `[ImplementPropertyChanged]` with `[AddINotifyPropertyChangedInterface]`.

**Comment by SimonCropp** [comment]
@BrunoJuchli is correct

**Comment by mcattle** [comment]
Note that (in .NET 5.0, at least) if you're using `[AddINotifyPropertyChangedInterface()]` and you have other code that needs to address instances of your class by that interface (such as when applying Generic type constraints), then the other code will complain via compiler errors that there is no implicit reference conversion from your class to INotifyPropertyChanged.

Choosing not to use the attribute and instead implement the interface with the event handler will fix these errors, but brings back the `CS0067` warning.

For the time being, I can suppress the warning as follows, but it's not a pretty solution.

    #pragma warning disable CS0067
            public event PropertyChangedEventHandler PropertyChanged;
    #pragma warning restore CS0067
