### ISSUE TITLE
Add an option to disable automatic dependent property changed.

### ISSUE THREAD

**Issue by malylemire1** [Fody/PropertyChanged#282]
Hi,

There should be an option to deactivate this feature. It's too expensive if you have round trips to the database or any expensive task when dependent property changed is called.

Thanks

**Comment by SimonCropp** [comment]
> round trips to the database or any expensive task when dependent property changed is called.

This goes against the assumptions of how this project treats a view model. I suggest you dont use PropertyChanged.

Having said that i will take a PR that disables this feature

**Comment by malylemire1** [comment]
Hi,

The use case seems really common to me. We have validations on property changed. Some require database values. I'll try to do a PR to add this option when I have the time for it.

Thanks

**Comment by SimonCropp** [comment]
any update on a pr?
