### ISSUE TITLE
Pause OnPropertyChanged

### ISSUE THREAD

**Issue by dagostinelli** [Fody/PropertyChanged#285]
(I'm trying to carefully read the docs to see if this already exists.  I'm posting because I'm not seeing this.  But please correct me if I'm wrong.)

In my ViewModel constructor, I would like to setup the View Model's properties.  But when I do so, the PropertyChanged event fires.  I don't want it to fire yet.   I would like it to wait until after the constructor is finished.  Is there a way to pause/unpause PropertyChanged event for a moment?

I noticed the[ IsChanged flag](https://github.com/Fody/PropertyChanged/wiki/Implementing-An-IsChanged-Flag), but that seems to be for a little bit different purpose.

```
[AddINotifyPropertyChangedInterface]
public class MyViewModel
{
	public string FirstName { get; set; }
	public string LastName { get; set; }

	public MyViewModel(MyModel model)
	{
		// how to pause OnPropertyChanged here?
		
		this.FirstName = model.FirstName;
		this.LastName = model.LastName;
		
		// how to unpause OnPropertyChanged here?
	}

	private void OnFirstNameChanged()
	{
		// save to database
	}
	
	private void OnLastNameChanged()
	{
		// save to database
	}
}

```

**Comment by BrunoJuchli** [comment]
This seems related to: #220

**Comment by SimonCropp** [comment]
No this is not possible.

**Comment by distantcam** [comment]
Easiest way to do this is to write your own base class that only fires the event once a flag is set.

```
public class FireWhenReady : INotifyPropertyChanged
{
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected bool firePropertyChanged;
	
	protected void OnPropertyChanged(string name)
	{
		PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
	}
}

...

public MyViewModel(MyModel model)
{
    this.FirstName = model.FirstName;
    this.LastName = model.LastName;
    firePropertyChanged = true;		
}
```

**Comment by HappyTreesDev** [comment]
The ability to "pause" a call to OnPropertyChanged would be super helpful. It would be equivalent to calling a set on the underlying variable  and would help with init commands and the like if you don't wish to fire off property changed events for no reason.

My suggestion, though I am not sure if it is possible. would be to add an attribute that can be added to a method or even a set call that indicates that the underlying variable should be used instead of the property.

i.e.

```
public bool StayLoggedIn {get;set;}

[NotNotifyPropertyChanged]
public Init()
{
  StayLoggedIn = true;
}
```

would compile to 

```
bool stayLoggedIn;
public bool StayLoggedIn
{
  get {return stayLoggedIn;}
  set 
  {
    if(value != stayLoggedIn)
    {
      stayLoggedIn = value;
      OnPropertyChanged();
    }
 }
}

public Init()
{
  stayLoggedIn = true;
}
```

**Comment by tom-englert** [comment]
@HappyTreesDev 
Simply use [AutoProperties.Fody](https://github.com/tom-englert/AutoProperties.Fody), then you can write

```c#
public bool StayLoggedIn {get;set;}

public Init()
{
  StayLoggedIn.SetBackingField(true);
}
```

**Comment by HappyTreesDev** [comment]
@tom-englert That works perfectly. Thanks so much!

**Comment by dagostinelli** [comment]
@tom-englert Thanks -- this sounds like a solution.

**Comment by n00bje** [comment]
Another (untested) solution:

```
public class SampleViewModel : ViewModelBase
{
    public string SomeProperty { get; set; }

    public SampleViewModel()
    {
        SomeProperty = "Some value";
        FirePropertyChanged = true;
    }
}

public class ViewModelBase : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool FirePropertyChanged = false;

    [NotifyPropertyChangedInvocator]
    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        if (FirePropertyChanged)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
```
