### ISSUE TITLE
It compile all types that implement INotifyPropertyChanged

### ISSUE THREAD

**Issue by Epxoxy** [Fody/PropertyChanged#288]
Is there a option just compile classes I want but not the all that implement INotifyPropertyChanged?

**Comment by SimonCropp** [comment]
no. that is not supported

**Comment by BrunoJuchli** [comment]
According to the Readme.md you can do the following:

> To scope the rewriting only to specific classes, and not the whole Assembly, you can use the FilterType attribute. This changes the general behavior from from opt-out to opt-in. Example: [assembly: PropertyChanged.FilterType("My.Specific.OptIn.Namespace.")]. The string is interpreted as a Regex, and you can use multiple filters. A class will be weaved, if any filter matches.

**Comment by tom-englert** [comment]
Or:
[`[DoNotNotifiy]`](https://github.com/Fody/PropertyChanged/wiki/Attributes#donotnotifyattribute):

Use this attribute to exclude a property or **type** from having notification injected.
