### ISSUE TITLE
FodyWeavers.xml not updated on install

### ISSUE THREAD

**Issue by JustinMinnaar** [Fody/PropertyChanged#289]
I installed PropertyChanged.Fody into several projects and could not figure out at first why the event was not firing. It turns out that the FodyWeavers.xml file was empty. I uninstalled and reinstalled and the problem persisted. Eventually I took a guess and the following change worked.

```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PropertyChanged />
</Weavers>
```

**Comment by BrunoJuchli** [comment]
And how do I reproduce this?

**Comment by SimonCropp** [comment]
Moving forward this will be the default behaviour. Nuget has removed the ability to do this at install time in the new project system. So nothing to fix, just needs to be added to doco

**Comment by JustinMinnaar** [comment]
Thanks for noting this. Simple enough. I hope you can update the docs so that others who try this package are not confused. Great product.

**Comment by SimonCropp** [comment]
doco updated https://github.com/Fody/PropertyChanged#add-to-fodyweaversxml

**Comment by JustinMinnaar** [comment]
Super, thanks Simon. Still a great tool. Best tool when building WPF apps.
