### ISSUE TITLE
Doesn't work if inheriting from INPC base class without OnPropertyChanged

### ISSUE THREAD

**Issue by cmeeren** [Fody/PropertyChanged#291]
While I ideally would like to just use `AddINotifyPropertyChangedInterfaceAttribute`, I need to program against the PropertyChanged event in a few cases, so I need to actually have the classes implement `INotifyPropertyChanged`. I do this by implementing it in a base class and inheriting the base class in all classes where I would like `INotifyPropertyChanged`.

As far as I understand from the documentation, Fody.PropertyChanged should inject an `OnPropertyChanged` method if it can't find any in the class hierarchy. However, it doesn't seem to work for me.

I have the following base class (F#, haven't tested in C# but it's a normal .NET class):

```f#
type INPCBase() =

  let propertyChanged = Event<_,_>()

  interface INotifyPropertyChanged with
    [<CLIEvent>]
    member __.PropertyChanged: IEvent<_,_> = propertyChanged.Publish
```

Classes inheriting from `INPCBase` never trigger the event. However, if I just add a `OnPropertyChanged` method, then everything works fine:

```f#
type INPCBase() =

  let propertyChanged = Event<_,_>()

  interface INotifyPropertyChanged with
    [<CLIEvent>]
    member __.PropertyChanged: IEvent<_,_> = propertyChanged.Publish

  member this.OnPropertyChanged propName =
    propertyChanged.Trigger (this, PropertyChangedEventArgs propName)
```

**Comment by BrunoJuchli** [comment]
Another workaround: instead of inheriting from the base class, just run-time cast the type to `INotifyPropertyChanged`.
We do this routinely for unit tests. Well, it's hidden behind an extension method which is used like:

    objectFoobar.ShouldRaisePropertyChanged(nameof(Foobar.MyEvent));

**Comment by cmeeren** [comment]
Oh, why didn't I think of that? Thanks! Could you describe how the extension method works?

**Comment by BrunoJuchli** [comment]
@cmeeren this is a specific use case for *unit tests*, and i wasn't entirely accurate.
We use [FluentAssertions](http://fluentassertions.com/), and exemplar code would look like:

    this.testee.MonitorEvents();

    this.testee.DoSomething()

    this.testee.ShouldRaisePropertyChangeFor(x => x.SelectedPlaces);

Behind the scenes, the definition is:

    public static class PropertyChangedSourceExtensions {
        public static IEventRecorder ShouldRaisePropertyChangeFor<T>(this T eventSource, Expression<Func<T, object>> propertyExpression);
     }

--------

Run-time casting example:

    ((INotifyPropertyChanged)new FooWeaved()).PropertyChanged += this.HandlePropertyChanged;

**Comment by cmeeren** [comment]
Thanks for the clarification. :)

**Comment by SimonCropp** [comment]
@cmeeren can u try v2.2

**Comment by cmeeren** [comment]
Works, thanks!
