### ISSUE TITLE
Error MSB3027, MSB3021 every second build

### ISSUE THREAD

**Issue by RomanGL** [Fody/PropertyChanged#294]
Hello!

Every second build my UWP project I'll get same error:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4052,5): error MSB3027: could not copy "obj\x86\Debug\LibName.dll" to "bin\x86\Debug\LibName.dll". Exceeded retry count of 10. Failed.
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4052,5): error MSB3021: unable to copy file "obj\x86\Debug\LibName.dll" to "bin\x86\Debug\LibName.dll". The process cannot access the file "bin\x86\Debug\LibName.dll" because it is being used by another process.

Projects without Fody.PropertyChanged builds normally. After restarting VIsual Studio, first build completes with no errors, second fails.

Visual Studio 2017 (15.4.5). 
The error occurs with the latest versions of the PropertyChanged and with the older 1.53.0.

**Comment by BrunoJuchli** [comment]
Does it happen after clean? Does it happen when you manually remove the output dll (of the project) and then build?

**Comment by SimonCropp** [comment]
What version of fody?

**Comment by RomanGL** [comment]
> Does it happen after clean? Does it happen when you manually remove the output dll (of the project) and then build? 

Delete the obj and bin folders doesn't help. Only restart Visual Studio.
> What version of fody? 

2.0.0 and newer.

**Comment by RomanGL** [comment]
![image](https://user-images.githubusercontent.com/7839481/33713201-d7b3fe66-db7c-11e7-8d9d-a35be4721137.png)

**Comment by sebandraos** [comment]
I have encountered this previously and had success by killing msbuild (from Task Manager) rather than restarting VS.

**Comment by SimonCropp** [comment]
can someone upload a sln that repros this?

**Comment by SimonCropp** [comment]
Closed due to no response
