### ISSUE TITLE
can't update to ProperyChanged.Fody 2.2.0 with Xamarin Forms

### ISSUE THREAD

**Issue by julesx** [Fody/PropertyChanged#297]
```
Update-Package : Could not install package 'PropertyChanged.Fody 2.2.0'. You are trying to install this package into a project that targets 
'.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Update-Package
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

**Comment by SimonCropp** [comment]
PCLs are considered legacy by MS. is it possible for you to move to netstandard? https://github.com/dotnet/standard/blob/master/docs/versions.md#mapping-pcl-profiles-to-net-standard

**Comment by julesx** [comment]
not super easily

i have no plans to convert my existing apps to netstandard currently

**Comment by SimonCropp** [comment]
can u try 2.2.1

**Comment by julesx** [comment]
> Update-Package PropertyChanged.Fody -version 2.2.1

`Update-Package : Package 'PropertyChanged.Fody 2.2.1' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'.`

**Comment by SimonCropp** [comment]
u will need to give nuget a few min to load it into the index https://www.nuget.org/packages/PropertyChanged.Fody/2.2.1

**Comment by julesx** [comment]
updated successfully but property change events aren't firing

had a similar issue a few updates ago

**Comment by SimonCropp** [comment]
can u share a repro?

**Comment by julesx** [comment]
https://github.com/julesx/FodyTest2/tree/master/App2/App2

everything is in MainPage.xaml and MainPage.xaml.cs

**Comment by SimonCropp** [comment]
you r missing `<PropertyChanged/>` here https://github.com/julesx/FodyTest2/blob/master/App2/App2/FodyWeavers.xml
https://github.com/Fody/PropertyChanged#add-to-fodyweaversxml

**Comment by julesx** [comment]
This was a default nugget installation. I’ve never had to add that manually before.

**Comment by SimonCropp** [comment]
yeah unfortunately the nuget feature we relied on to perform that xml editing is in the process of being removed. and the nuget team has no plans to give an alternative.

so moving forward u will need to add and remove the xml node when u add and remove a fody weaver nuget

sorry for the inconvenience

**Comment by julesx** [comment]
looks like updating my main project wiped the FodyWeavers.xml file out and replaced it with the default

it used to ask me if i wanted to replace the existing file
