### ISSUE TITLE
New version report change before property initialized

### ISSUE THREAD

**Issue by arteny** [Fody/PropertyChanged#299]
After updating from version 2.1.4 to new one (2.2..), it begin reporting change before intializing property in Release mode and not report when it is initializing, so absolutely erronous behavior.
When rollbacked to 2.1.4 all working ok.

**Comment by SimonCropp** [comment]
can u produce a failing unit test? ore repro solution?

**Comment by SimonCropp** [comment]
let me know if u get around to that failing unit test

**Comment by arteny** [comment]
Issue still reporduced for different app as well, only updating to 2.2.5, Property Changed functionality is breaking...
