### ISSUE TITLE
"typeof(any_of_your_attribute)" causes to crash.

### ISSUE THREAD

**Issue by Torentes** [Fody/PropertyChanged#302]
I just want to obtain the type of DoNotNofifyAttribute, but somehow it is not working. I tried it with the other attributes, but that fails too. It just happens when the debugger enters a method that contains the typeof expression. This method is the last entry of the call stack. I get strange exceptions like System.TypeLoadException's that involves my random assemblies like System.Data.SQLite or Crc32C depending on one of your attribute. 

Perhaps you can tell me, what's wrong with it.

**Comment by SimonCropp** [comment]
The reference to propertychanged.dll is removed at compile time and not meant to be deployed or used via reflection. 

What are you using it for ?

**Comment by Torentes** [comment]
I am not familiar with this kind of technique, but the attribute is just a "reference" or "pointer" you can use, but won't be there when compiled, right?

I wanted to collect all public properties into a list and ignore those public properties, who are not supposed to be tracked, those who are already marked with the DoNotNotifyAttribute.

**Comment by SimonCropp** [comment]
unfortunately you wont be able to do this with `DoNotNotifyAttribute` and will need to find another mechanism.

but i am curious what is the use case that requires "all public properties into a list and ignore those public properties, who are not supposed to be tracked," ?

**Comment by Torentes** [comment]
I am working on a new technique to reflect migration as classes. It is just a hobby. I had the idea a little bit longer, and C# provides the tools. My workaround was to search per derived type and ignore the base class, that contains the unwanted public properties.

**Comment by SimonCropp** [comment]
sorry but you will have to find another way
