### ISSUE TITLE
Cannot set breakpoints

### ISSUE THREAD

**Issue by fjeremic** [Fody/PropertyChanged#303]
I seem to be experiencing the same issue as reported by @SirUppyPancakes in https://github.com/Fody/NullGuard/issues/90, except this issue is with PropertyChanged.Fody. I have checked all versions available and the only way to work around the issue is to downgrade to PropertyChanged.Fody 1.52.1 or earlier which pulls Fody 1.29.4.

I took a look at:
https://stackoverflow.com/questions/2155930/how-do-i-remedy-the-the-breakpoint-will-not-currently-be-hit-no-symbols-have-b

And checked out the module which PropertyChanged.Fody weaves and it says:

```
Binary was not built with debug information.
```

If I attempt to Load Symbols and I select the matching generated PDB I get a warning message:

```
A matching symbol file was not found in this folder.
```

It seems as if the PDB file is somehow corrupted after the weaving process.

**Comment by ewan-derivco** [comment]
Getting a similar issue, breakpoints are not loaded, downgrading doesn't help. 

If you check debug modules, it says "Binary was not built with debug information."

Workaround : changed the debug type from embedded to pdbonly and they are hit again.

**Comment by ewan-derivco** [comment]
I am using fody 2.3.2 and propertychanged.fody 2.2.4

**Comment by SimonCropp** [comment]
@ewan-derivco  so just to be clear you are using version 2.3.2 of fody that was released 20min ago and are still getting the same issue?

**Comment by farth123** [comment]
I had same problem. Last version (2.3.2) works great. Thanks

**Comment by ewan-derivco** [comment]
yes. I was switching around trying the older 1.52.1 version as recommended by Jeremic so i must have picked up the latest as soon as it was released.

Debug -> modules: 
No	No	Binary was not built with debug information.

breakpoint:
the breakpoint will not currently be hit, no symbols... etc

Project settings -> build -> advanced -> debugging information : Embedded

now if I change debugging information to "pdb-only" the breakpoint is hit

**Comment by ewan-derivco** [comment]
ps..  ive just tested the other options, full, and portable and they both work as well, only none and embedded dont hit the breakpoints

**Comment by fjeremic** [comment]
> can u try fody 2.3.2

I have just confirmed Fody 2.3.2 has fixed the issue. Great timing! Thank you very much!

**Comment by SimonCropp** [comment]
Kool

**Comment by ewan-derivco** [comment]
must be something different for me, I will raise a new issue If I can narrow it down. Possibly its something weird about our build
