### ISSUE TITLE
On_PropertyName_Changed doesn't get called

### ISSUE THREAD

**Issue by HeartThrobs** [Fody/PropertyChanged#304]
According to documentation in https://github.com/Fody/PropertyChanged, property-level interception -- For a given property, if there is a method of the form On<PropertyName>Changed, then that method will be called, as in https://github.com/Fody/PropertyChanged/wiki/On_PropertyName_Changed.  But if I add following code in Person.cs, OnFullNameChanged doesn't get called.

    public void OnFullNameChanged(string propertyName)
    {
        Console.WriteLine("FullName Changed");
    }

**Comment by SimonCropp** [comment]
can u add a failing unit test in a PR

**Comment by HeartThrobs** [comment]
No change from original unit testing given in the sample solution;

using System.Collections.Generic;
using Xunit;

public class PropertyChangedSample
{
    [Fact]
    public void Run()
    {
        var target = new Person();
        var propertyNotifications = new List<string>();
        target.PropertyChanged += (sender, args) => propertyNotifications.Add(args.PropertyName);
        target.FamilyName = "Smith";
        Assert.Contains("FamilyName",propertyNotifications);
        Assert.Contains("FullName", propertyNotifications);
    }
}

The unit test does not fail, OnFullNameChanged won't break.

**Comment by KRA2008** [comment]
I am also hitting this.

**Comment by SimonCropp** [comment]
so the `On_PropertyName_Changed` feature is poorly named. it should be `On_PropertyName_Set`. ie it is called when a property is set. since `FullName` is readonly it is never set. it is designed to allow custom set code when still using automatic properties.

**Comment by HeartThrobs** [comment]
Neither of OnFullNameSet or OnFamilyNameChanged breaks.

    public void OnFullNameSet(string propertyName)
    {
        Console.WriteLine("FullName Changed");
    }

    public void OnFamilyNameChanged(string propertyName)
    {
        Console.WriteLine("FullName Changed");
    }

**Comment by BrunoJuchli** [comment]
@HeartThrobs 
use

    public void OnFamilyNameChanged()
    {
        Console.WriteLine("FamilyName changed");
    }

**Comment by HeartThrobs** [comment]
Yup, OnFamilyNameChanged() breaks fine.

**Comment by SimonCropp** [comment]
As per the doco “Allows having a "similar named" method called when a property is set”. So it will not be called for properties without a set.
