### ISSUE TITLE
Allow On_PropertyName_Changed parameters to be of the type of the property

### ISSUE THREAD

**Issue by zspitz** [Fody/PropertyChanged#306]
Given the following property:

    public bool IsSelected { get; set; } = false;

the `OnIsSelectedChanged` method is called only if the parameters are of type `object`:

    public void OnIsSelectedChanged(object oPrevious, object oNew) {

If the parameters are typed as `boolean`:

    public void OnIsSelectedChanged(bool prev, bool @new) {

the method will not be called. [Source code](https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/OnChangedWalker.cs#L67).

(As an aside, I didn't find this point in the documentation, only by reading the source code.)

This is inconvenient, because the first two lines of any such method will usually be a cast to a new variable:

    public void OnIsSelectedChanged(object oPrevious, object oNew) {
        var prev = (bool)oPrevious;
        var @new = (bool)oNew;

When looking for a catch-all `OnPropertyChanged` method, this is understandable, because different properties will have different types, and the same method is used for all of them. But if the method corresponds to a specific property, the arguments could be limited to the type of the property.

I can see allowing three possible variants:
* **Arguments of type `object`** -- In an ideal world, I don't think this should be allowed; but disallowing it would break a lot of existing code
* **Arguments of the exact type of the property**
* **Arguments of a type assignable to the property's type** -- Probably would include inheriting types and implicit conversions. I'm not sure if there's a valid use case for this.

(I would be willing to submit a PR for this.)

**Comment by SimonCropp** [comment]
happy to accept a PR

**Comment by zspitz** [comment]
@SimonCropp Is this no longer relevant? I just haven't had the time to prepare a PR.

**Comment by SimonCropp** [comment]
Sorry. I get a lot of drive by issues where people never follow up

**Comment by SimonCropp** [comment]
Ok i will close this and track when the pr is open
