### ISSUE TITLE
Issue in readme: 'Interception' implies being able to cancel, but OnPropertyChanged / On_PropertyName_Changed doesn't allow this

### ISSUE THREAD

**Issue by zspitz** [Fody/PropertyChanged#307]
From the README:

> * **Intercepting the notification call**
    * [**Global interception**](https://github.com/Fody/PropertyChanged/wiki/NotificationInterception)
    * **Class-level interception** --The `OnPropertyChanged` method will only be injected if there is no such existing method on the class; if there is such a method, then calls to that method will be injected into the setters -- see [here](https://github.com/Fody/PropertyChanged/wiki/EventInvokerSelectionInjection).
    * **Property-level interception** -- For a given property, if there is a method of the form `On<PropertyName>Changed`, then that method will be called -- see [here](https://github.com/Fody/PropertyChanged/wiki/On_PropertyName_Changed).

It is misleading to refer to the `OnPropertyChanged` and `On_PropertyName_Changed` variants as interception; the raising of the PropertyChanged event cannot be cancelled from these.

Instead, maybe something like this:

> * [**Intercepting the notification call**](https://github.com/Fody/PropertyChanged/wiki/NotificationInterception)
> * **Handlers for property changes**
    * **Class-level handler** -- Fody.PropertyChanged will only create an `OnPropertyChanged` method if there is no such existing method on the class; if there is such a method, then calls to that method will be injected into the setters -- see [here](https://github.com/Fody/PropertyChanged/wiki/EventInvokerSelectionInjection).
    * **Per-property handler** -- For a given property, if there is a method of the form `On<PropertyName>Changed`, then that method will be called -- see [here](https://github.com/Fody/PropertyChanged/wiki/On_PropertyName_Changed).

**Comment by SimonCropp** [comment]
interception does not imply cancellable
