### ISSUE TITLE
static Equals not used

### ISSUE THREAD

**Issue by jhartmann123** [Fody/PropertyChanged#309]
According to the wiki a static Equals method should be used for equality checking.
 (https://github.com/Fody/PropertyChanged/wiki/EqualityChecking)

This does not work in two cases:
1) static Equals is defined in a base class
```
public class BaseClass
{
    public static bool Equals(BaseClass first, BaseClass second) {...}
}

public class ChildClass : BaseClass
{ }

public class OtherClass : INotifyPropertyChanged
{
   public ChildClass Property { get; set; }
}
```

Result: after weaving, the setter of OtherClass.Property uses object.Equals() instead of BaseClass.Equals()

2) The class implementing the static Equals method is in another assembly
```
Assembly 1:
public class SomeClass 
{
   public static bool Equals(SomeClass first, SomeClass second) { ... }
}

Assembly 2:
public class OtherClass : INotifyPropertyChanged
{
   public SomeClass Property { get; set; }
}
```

Same result: after weaving, the setter of OtherClass.Property uses object.Equals() instead of SomeClass.Equals()

I've already fixed that and will create a PR soon.

**Comment by SimonCropp** [comment]
i am not sure of case 1 should be supported.

the doco says "Check if the Type has a static Equals method with two parameters matching Type."

ChildClass does not have a static equals

**Comment by jhartmann123** [comment]
For us supporting a static equals from the base class would be just a nice convenience thing tbh. Otherwise (in our specific case) I'd had to implement a static equals for over 200+ classes. That's unit testable and all, but just a lot of copy paste.

I see that using a static equals from the base by default also could break some existing code...

Would you be fine, if that's an optional feature? For example by adding 'UseStaticEqualsFromBase' as a config attribute to the weaver config? (Default: false)

**Comment by jhartmann123** [comment]
fyi: Updated the PR to support a config param

**Comment by davidroth** [comment]
@SimonCropp Do you have any feedback to the latest changes from @jhartmann123? We'd love to bring this forward ;)
