### ISSUE TITLE
NETStandard 1.3 support

### ISSUE THREAD

**Issue by worldbeater** [Fody/PropertyChanged#312]
Hi @SimonCropp!

There seems to be an issue with NETStandard 1.3. When I create an empty class library targeting this NETStandard version, add **PropertyChanged.Fody** and build it using **dotnet build**, I get the following output:
```
Restoring packages for C:\Projects\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj...
  Generating MSBuild file C:\Projects\ClassLibrary2\ClassLibrary2\obj\ClassLibrary2.csproj.nuget.g.props.
  Restore completed in 301,7 ms for C:\Projects\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj.
    Fody: Fody (version 1.0.0.0) Executing
MSBUILD : error : Fody: Could not find 'System.Collections.Generic.EqualityComparer`1'. [C:\Projects\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj]
    Fody:   Finished Fody 332ms.

Build failed.

MSBUILD : error : Fody: Could not find 'System.Collections.Generic.EqualityComparer`1'. [C:\Projects\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj]
```

Project setup:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PropertyChanged.Fody" Version="2.2.5" />
  </ItemGroup>
</Project>
```

If I change project target framework version to NETStandard 2.0, the error goes away. So does this mean, that lower standard versions are no longer supported?

Thanks.

UPD: The same thing happens to NETStandard 1.0, 1.1, ..., 1.6

**Comment by BrunoJuchli** [comment]
According to the [.net api browser](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.equalitycomparer-1?view=netframework-4.7.1) it should be available from .net standard 1.0 on.

**Comment by candidodmv** [comment]
+1 
I'm with the same problem

**Comment by SimonCropp** [comment]
do any of you want to have a go at fixing this?

**Comment by candidodmv** [comment]
No, the problem keeps

**Comment by candidodmv** [comment]
I found a workaround, downgrade for version 2.2.4

**Comment by SimonCropp** [comment]
"the problem keeps"?

**Comment by candidodmv** [comment]
sorry my english is not so good. I want do say that "the problem remains"

**Comment by worldbeater** [comment]
> I found a workaround, downgrade for version 2.2.4

This workaround isn't perfect actually, Fody 2.2.4 doesn't seem to play well with new *dotnet build* command. So, still need a fix. I'll try to investigate and see what's causing the issue, but it would be great if anyone more experienced could take a look at this (perhaps, it can save some time)

**Comment by worldbeater** [comment]
Unable to reproduce this bug in PropertyChanged.Fody's testing environment. Assemblies targeting NETStandard 1.0 and weaved by Fody's **.ExecuteTestRun()** method called in Tests project (which targets *net46; netcoreapp2.0*) are weaved just fine. Code:

```csharp
public class AssemblyWithOldNetStandardTests
{
    [Fact]
    public void Load()
    {
        var weavingTask = new ModuleWeaver();
        var testResult = weavingTask.ExecuteTestRun("AssemblyWithOldNetStandard.dll");
        var instance = testResult.GetInstance("SampleImplementor");
        
        var eventCount = 0;
        ((INotifyPropertyChanged)instance).PropertyChanged += (sender, args) => eventCount++;
        instance.B = 10;
        
        Assert.Equal(1, eventCount); // OK
    }
}
```
AssemblyWithOldNetStandard setup:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.0</TargetFramework>
    <DisableFody>true</DisableFody>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\PropertyChanged\PropertyChanged.csproj" />
  </ItemGroup>
</Project>
```

So maybe there is an issue with a nuget package itself? 🤔

**Comment by SimonCropp** [comment]
can someone upload a repro solution

**Comment by worldbeater** [comment]
Here it is: https://github.com/worldbeater/PropertyChanged_312_repro
Hope this helps.
