### ISSUE TITLE
PropertyChanged.Fody not working in VB.NET in VS2017

### ISSUE THREAD

**Issue by georgeinva2004** [Fody/PropertyChanged#313]
Hate to ask this, but I have a legacy app built in VB.net where I'm trying to add PropertyChanged.Fody.  I'm getting this error at compile time:  **Fody:  Could not find 'System.Object'**.  I built a bare-bones console app in vb.net and am getting the same error.  However, when I build a barebones console app in C#, the project builds with errors from Fody.  Given the fact it works in a C# app, I'm confident it's not a config issue in my environment.

**Comment by SimonCropp** [comment]
having trouble replicating. can u upload a repro

**Comment by georgeinva2004** [comment]
[ConsoleApp1.zip](https://github.com/Fody/PropertyChanged/files/1649815/ConsoleApp1.zip)
ConsoleApp1 is a very simple VB.Net app that has the compile here.
ConsoleApp2 is a very simple C# app that compiles correc
[ConsoleApp2.zip](https://github.com/Fody/PropertyChanged/files/1649816/ConsoleApp2.zip)
tly.

**Comment by SimonCropp** [comment]
can u try adding these references to your project
```
<Reference Include="mscorlib" />
<Reference Include="Microsoft.VisualBasic" />
```

**Comment by ABSTRACT123** [comment]
Hello,

i have this issue with PropertyChanged.Fody not working in VB.NET in VS2017
 Fody: Could not find 'System.Object'. 

mscorlib and microsoft.visulabasic are already added by default in a vb project.

Nugets in my project:
EF 6.2.0
Fody 2.4.4
PropertyChanged.Fody 2.2.6
System.Data.SQLite 1.0.107

If i create a new project I get this error

Fody: Could not find path to weavers file. Searched 'C:\Users\Qwerty\Documents\Visual Studio 2017\Projects\VB\test\FodyWeavers.xml', 'C:\Users\Qwerty\Documents\Visual Studio 2017\Projects\VB\test\test\FodyWeavers.xml'.


Thank you for your help and fody.

**Comment by BrunoJuchli** [comment]
@ABSTRACT123 

Regarding your new Project, you've probably just forgotten to add the FodyWeavers.xml, right?
Once you've added this to the new project and you can still experience the issue "Could not find 'System.Ojbect'" please upload the project so the issue can be reproduced and fixed.

**Comment by ABSTRACT123** [comment]
@BrunoJuchli 

Thank you for your answer. Once I add the FodyWeavers.xml, I have the problem above (could not find system.object)

<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <PropertyChanged />
</Weavers>

I have another project which was running fine with an older version of propertychanged.fody (1.51.3) and fody (1.29.4). I didn't an upgrade via nuget manager, then the FodyWeavers.xml was changed to this 

<?xml version="1.0" encoding="utf-8"?>
<Weavers>
</Weavers>

And since I reset it to 

<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <PropertyChanged />
</Weavers>

I now have system.object not found (this under VS 2015 community same with VS 2017)

[test.zip](https://github.com/Fody/PropertyChanged/files/1770851/test.zip)

**Comment by BrunoJuchli** [comment]
I can confirm/reproduce the issue.
I've updated to the latest packages, removed the old packages and cleaned-up references:

[FodyVB.zip](https://github.com/Fody/PropertyChanged/files/1772044/FodyVB.zip)

Building results in:

> 1>------ Build started: Project: test, Configuration: Debug Any CPU ------
1>    Fody: Fody (version 2.4.4.0) Executing
1>MSBUILD : error : Fody: Could not find 'System.Object'.
1>    Fody:   Finished Fody 412ms.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by ABSTRACT123** [comment]
Hello,

Can you reopen the issue please?

I installed back the old version mentioned above but it seems to actually be an old issue as most (have tried them all) versions afterwards seem to produce the same error.

Thank you.

**Comment by SimonCropp** [comment]
try adding the following to the csproj

```

    <Reference Include="mscorlib" />
    <Reference Include="Microsoft.VisualBasic" />
```

**Comment by SimonCropp** [comment]
i know VB says it adds them by default. but it does not pass them to msbuild

**Comment by BrunoJuchli** [comment]
@ABSTRACT123 
The repro Project was lacking the references to mscorlib and Microsoft.VisualBasic.
After adding them the solution builds fine.

Also see attachment

[FodyVB.zip](https://github.com/Fody/PropertyChanged/files/1782539/FodyVB.zip)

@SimonCropp 
Sorry I missed that, I realize you've mentioned it before.

**Comment by SimonCropp** [comment]
@BrunoJuchli yeah no worries. thanks for helping to triage.

it is weird that those refs are not passed into `@(ReferencePath)`. https://github.com/Fody/Fody/blob/master/Fody/Fody.targets#L78

**Comment by ABSTRACT123** [comment]
Hello,

Thanks for your answer, I'll try that in a few hours and will let you know;

**Comment by SimonCropp** [comment]
glad u got it working

**Comment by protegesolutions** [comment]
I had this issue as well, Fody 3.3.5 and Fody.Costura 3.3.0. Adding the references fixed the issue but I found I actually didn't need the explicit `VisualBasic` reference. (I already had it added as a Namespace if that makes a difference.)

I also couldn't add `mscorlib` via the UI; I had to add it to the `.vbproj` file manually.

It'd be great if this could be fixed; it kinda dirties up the project to have what is really an unnecessary reference.

**Comment by SimonCropp** [comment]
@protegesolutions fody has moved to a pay for use model https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

I suggest you raise a new issue to track this. Please ensure you follow the issue template https://github.com/Fody/PropertyChanged/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
