### ISSUE TITLE
Build error since upgrading to ver 2.2.5

### ISSUE THREAD

**Issue by Peregrine66** [Fody/PropertyChanged#314]
My application build and runs fine when using PropetyChanged.Fody version 2.1.4. 

It's a standard WPF application, built using visual studio 2015 on windows 10.

However, since upgrading to version 2.2.5, the build fails with an error :-
`    Fody: Fody (version 1.0.0.0) Executing
    MSBUILD : error : Fody: Could not find a weaver named 'PropertyChanged'.
    MSBUILD : error : If you have nuget package restore turned on you probably need to do a build to download the weavers.
    MSBUILD : error : Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot to add the appropriate NuGet package.
    MSBUILD : error : Perhaps you need to run 'Install-Package PropertyChanged.Fody'. This url may provide more information http://nuget.org/packages/PropertyChanged.Fody/ .`

My FodyWeavers.xml file is just 
`<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <PropertyChanged />
</Weavers>`

Is there any way to debug the Fody process to see what's going on?

**Comment by SimonCropp** [comment]
you can compile fody locally and then attach to the msbuild process

**Comment by theogumilang** [comment]
@SimonCropp i have the same issues here when try to build my xamarin app in app.center, can you explain more about that ?

**Comment by SimonCropp** [comment]
can one of you upload a minimal solution that reproduces this so i can have a look at it?

**Comment by theogumilang** [comment]
the error i got from app center MSBUILD : error : Fody: Could not find a weaver named 

> []('PropertyChanged'. [/Users/vsts/agent/2.127.0/work/1/s/KGVC/KGVC/KGVC.csproj]
> MSBUILD : error : If you have nuget package restore turned on you probably need to do a build to download the weavers. [/Users/vsts/agent/2.127.0/work/1/s/KGVC/KGVC/KGVC.csproj]
> MSBUILD : error : Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot to add the appropriate NuGet package. [/Users/vsts/agent/2.127.0/work/1/s/KGVC/KGVC/KGVC.csproj]
> MSBUILD : error : Perhaps you need to run 'Install-Package PropertyChanged.Fody'. This url may provide more information http://nuget.org/packages/PropertyChanged.Fody/ . [/Users/vsts/agent/2.127.0/work/1/s/KGVC/KGVC/KGVC.csproj])

i already tried to reinstall and update my PropertyChanged.Fody to the latest version but still got the same error

**Comment by SimonCropp** [comment]
can u try the latest version of fody?

**Comment by gadipaz** [comment]
Also here, same issue.

Fody ver. 2.3.25
PropertyChanged.Fody ver. 2.2.5

Any Idea?

**Comment by SimonCropp** [comment]
Can someone upload a repro. 

Or submit a pr that fixes the issue

**Comment by SimonCropp** [comment]
will reopen if anyone provides a repro

**Comment by theogumilang** [comment]
@SimonCropp  i can upload it  on github, but my code have so many sensitive data. how about i upload my csproj is that can help ?

**Comment by SimonCropp** [comment]
a minimal repro should have all the sensitive code removed
