### ISSUE TITLE
Need a way to mark methods as unrelated to PropertyChanged

### ISSUE THREAD

**Issue by CADbloke** [Fody/PropertyChanged#317]
``` csharp
internal bool OnlyConnectionNameChanged(Connection otherConnection)
``` 

triggers 

```
MSBUILD : error : Fody: The type Blahblahblah has a On_PropertyName_Changed method (OnlyConnectionNameChanged) that has a non void return value. Ensure the return type void.
```

because it fits the criteria of 

``` csharp
var onChangedMethods = methods.Where(x => !x.IsStatic &&
                                                x.Name.StartsWith("On") &&
                                                x.Name.EndsWith("Changed"));
```

at https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/OnChangedWalker.cs#L26

Workaround is to rename the method to `ConnectionNameChangedOnly()`... which is probably the easiest way to mark a method as unrelated to PropertyChanged. If nothing else, at least Google will now return something on that error message.

**Comment by SimonCropp** [comment]
how about check if there is a property that correlates to that method convention. so in this case `OnlyConnectionNameChanged` would not error since there is no property named `lyConnectionName`

**Comment by CADbloke** [comment]
Yup, I like that.  Related: it should return an error if you have inadvertently used the `OnThingChanged` method name for something unrelated.

**Comment by SimonCropp** [comment]
@CADbloke cool. can u submit a PR for that?

**Comment by CADbloke** [comment]
Yah. Leave it with me. Might take a little while.

**Comment by SimonCropp** [comment]
will re-open if the PR is ever forthcoming
