### ISSUE TITLE
Whether to support unity?

### ISSUE THREAD

**Issue by hubluesky** [Fody/PropertyChanged#320]
Whether to support unity

**Comment by SimonCropp** [comment]
as i understand it unity supports .net 4.6?

**Comment by hubluesky** [comment]
Unity 2017 and later versions support .NET 4.6

**Comment by SimonCropp** [comment]
And this project supports 4.6. So what is the problem?

**Comment by hubluesky** [comment]
I am sorry, I am a novice, can tell me how to use in unity.

**Comment by SimonCropp** [comment]
what have you tried?

**Comment by hubluesky** [comment]
I compiled the PropetyChanged and PropertyChanged.Fody project
Then copy these dlls into unity from the compiled path "Release\net452"
![image](https://user-images.githubusercontent.com/6335104/36964475-b83ddca0-2091-11e8-8089-559dc2a57024.png)
Then I wrote a test class
`[PropertyChanged.AddINotifyPropertyChangedInterface]
public class Person {
	public string GivenNames { get; set; }
	public string FamilyName { get; set; }

	public string FullName {
		get {
			return string.Format("{0} {1}", GivenNames, FamilyName);
		}
	}

	public event PropertyChangedEventHandler PropertyChanged;
}`
Question: How can I get this class to have code injected at compile time in Unity3D?

**Comment by SimonCropp** [comment]
can unity consume nuget packages?

**Comment by hubluesky** [comment]
No,Unity itself is incapable of handling Nuget packages.

**Comment by SimonCropp** [comment]
so u cant use this https://github.com/GlitchEnzo/NuGetForUnity  ?

**Comment by hubluesky** [comment]
I am trying to use NuGetForUnity in unity
![image](https://user-images.githubusercontent.com/6335104/37075951-35e0c928-220f-11e8-994b-df85f37ad32d.png)
I installed PropertyChanged.Fody[2.2.9]，And I got this file structure in unity.
![image](https://user-images.githubusercontent.com/6335104/37076030-99e72f3e-220f-11e8-9ee2-11a7f5078bc2.png)
Lib folder is empty，And Play the unity, I got this error.
![image](https://user-images.githubusercontent.com/6335104/37076084-d7c95c46-220f-11e8-93e0-481a4eca1c65.png)

**Comment by SimonCropp** [comment]
sorry i dont have the capacity to invest time in this. i suggest you 

 * try to solve it yourself; or
 * recruit some other people to help you; or
 * pay someone to solve it; or
 * stop using this utility

will close for now
