### ISSUE TITLE
Error		Fody: An unhandled exception occurred: Exception: Could not resolve 'Ozeki.Camera.IWebCamera'.

### ISSUE THREAD

**Issue by goodnewso** [Fody/PropertyChanged#322]
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using MaterialDesignThemes.Wpf;
using Ozeki.Camera;
using Ozeki.Media;

namespace LMS.ViewModel.Teacher
{
    public class BroadCastingViewModel: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged = (sender, e) => { };

        public BroadCastingViewModel()
        {
            _cameraList = new ObservableCollection<VideoDeviceInfo>();
            _micList = new ObservableCollection<AudioDeviceInfo>();
            _speakerList = new ObservableCollection<AudioDeviceInfo>();
            _connector = new MediaConnector();
            _audioConnector = new MediaConnector();
            _provider = new DrawingImageProvider();
            _startPreviewCommand = new RelayCommand(StartPreview);
            _stopPreviewCommand = new RelayCommand(StopPreview);
            _reloadDeviceCommand = new RelayCommand(GetDevices);
            SetVideoViewer();
        }

        #region Private Fields

        private Grid _previewBox;
        private ObservableCollection<VideoDeviceInfo> _cameraList;
        private ObservableCollection<AudioDeviceInfo> _micList;
        private ObservableCollection<AudioDeviceInfo> _speakerList;
        private VideoViewerWPF _videoViewerWpf;
        private DrawingImageProvider _provider;
        private MediaConnector _connector;
        private MediaConnector _audioConnector;
        private MJPEGStreamer _streamer;
        private IVideoSender _videoSender;

        private ICommand _startPreviewCommand;
        private ICommand _reloadDeviceCommand;
        private ICommand _stopPreviewCommand;

        #endregion

        #region Private Methods

        private void SetVideoViewer()
        {
            _previewBox = new Grid();

            if (_videoViewerWpf == null)
            {
                _videoViewerWpf = new VideoViewerWPF()
                {
                    HorizontalAlignment = HorizontalAlignment.Stretch,
                    VerticalAlignment = VerticalAlignment.Stretch,
                    Background = Brushes.Black
                };
            }

            if (PreviewBox.Children.Count != 0)
                PreviewBox.Children.Clear();
            PreviewBox.Children.Add(_videoViewerWpf);
            _videoViewerWpf.SetImageProvider(_provider);

        }

        #endregion

        #region Public Properties

        public IWebCamera SelectedCamera { get; set; }
        public Microphone SelectedMic { get; set; }
        public Speaker SelectedSpeaker { get; set; }
        public ObservableCollection<VideoDeviceInfo> CameraList
        {
            get => _cameraList;
            set => _cameraList = value;
        }

        public ObservableCollection<AudioDeviceInfo> MicList
        {
            get => _micList;
            set => _micList = value;
        }
        public ObservableCollection<AudioDeviceInfo> SpeakerList
        {
            get => _speakerList;
            set => _speakerList = value;
        }
        public Grid PreviewBox
        {
            get => _previewBox;
            set => _previewBox = value;
        }
        
        public ICommand StartPreviewCommand
        {
            get => _startPreviewCommand;
            set => _startPreviewCommand = value;
        }
        public ICommand StopPreviewCommand
        {
            get => _stopPreviewCommand;
            set => _stopPreviewCommand = value;
        }

        public ICommand ReloadDeviceCommand
        {
            get => _reloadDeviceCommand;
            set => _reloadDeviceCommand = value;
        }
        #endregion

        #region Public Method

        public void StartPreview()
        {
            if (SelectedCamera == null) return;
            
            _connector.Connect(SelectedCamera.VideoChannel, _provider);
            _connector.Connect(Microphone.GetDefaultDevice(), Speaker.GetDefaultDevice());
            //_audioConnector.Connect(Selectedmic, _audioProvider);
            _videoSender = SelectedCamera.VideoChannel;
            SelectedCamera.Start();
            _videoViewerWpf.Start();

        }

        public void StopPreview()
        {
            _connector.Disconnect(SelectedCamera.VideoChannel, _provider);
            _connector.Connect(Microphone.GetDefaultDevice(), Speaker.GetDefaultDevice());

            SelectedCamera.Stop();
            _videoViewerWpf.Stop();
        }
        public void GetDevices()
        {
            if (CameraList == null) CameraList = new ObservableCollection<VideoDeviceInfo>();
            if (CameraList.Count > 0) CameraList.Clear();
            var usbList = WebCameraFactory.GetDevices();
            foreach (var videoDevice in usbList)
            {
                CameraList.Add(videoDevice);
            }
            if (MicList == null) MicList = new ObservableCollection<AudioDeviceInfo>();
            if (MicList.Count > 0) MicList.Clear();
            var micList = Microphone.GetDevices();
            foreach (var micDevice in micList)
            {
                MicList.Add(micDevice);
            }
            if (SpeakerList == null) SpeakerList = new ObservableCollection<AudioDeviceInfo>();
            if (SpeakerList.Count > 0) SpeakerList.Clear();
            var speakers = Speaker.GetDevices();
            foreach (var speakerDevice in speakers)
            {
                SpeakerList.Add(speakerDevice);
            }

        }

        #endregion
    }
}

Error 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Could not resolve 'Ozeki.Camera.IWebCamera'.
Type:
System.Exception
StackTrace:
   at ModuleWeaver.InnerResolve(TypeReference reference)
   at ModuleWeaver.Resolve(TypeReference reference)
   at ModuleWeaver.GetStaticEquality(TypeReference typeReference)
   at ModuleWeaver.GetEquality(TypeReference typeDefinition)
   at ModuleWeaver.FindTypeEquality(TypeReference typeDefinition)
   at EqualityCheckWeaver.InjectEqualityCheck(Instruction targetInstruction, TypeReference targetType)
   at EqualityCheckWeaver.CheckAgainstField()
   at EqualityCheckWeaver.Execute()
   at ModuleWeaver.ProcessTypes(List`1 notifyNodes)
   at ModuleWeaver.Execute()
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
PropertyChanged.Fody
TargetSite:
Mono.Cecil.TypeDefinition InnerResolve(Mono.Cecil.TypeReference)
Could not read 'C:\Users\GOODNEWS\Documents\Visual Studio 2017\Projects\JAJA TECH\LMS\bin\Debug\OzekiSDK.dll'.
Type:
System.Exception
StackTrace:
   at AssemblyResolver.GetAssembly(String file, ReaderParameters parameters)
   at AssemblyResolver.Resolve(AssemblyNameReference assemblyNameReference, ReaderParameters parameters)
   at AssemblyResolver.Resolve(AssemblyNameReference assemblyNameReference)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type) in C:\projects\cecil\Mono.Cecil\MetadataResolver.cs:line 101
   at Mono.Cecil.TypeReference.Resolve() in C:\projects\cecil\Mono.Cecil\TypeReference.cs:line 276
   at ModuleWeaver.InnerResolve(TypeReference reference)
Source:
FodyIsolated
TargetSite:
Mono.Cecil.AssemblyDefinition GetAssembly(System.String, Mono.Cecil.ReaderParameters)
Non-negative number required.
Parameter name: count
Type:
System.ArgumentOutOfRangeException
StackTrace:
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Mono.Cecil.PE.ImageReader.ReadDebugHeader() in C:\projects\cecil\Mono.Cecil.PE\ImageReader.cs:line 357
   at Mono.Cecil.PE.ImageReader.ReadImage() in C:\projects\cecil\Mono.Cecil.PE\ImageReader.cs:line 89
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name) in C:\projects\cecil\Mono.Cecil.PE\ImageReader.cs:line 759
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in C:\projects\cecil\Mono.Cecil\ModuleDefinition.cs:line 1094
   at AssemblyResolver.GetAssembly(String file, ReaderParameters parameters)
Source:
mscorlib
TargetSite:
Byte[] ReadBytes(Int32)	LMS

**Comment by SimonCropp** [comment]
Upload a repro solution

**Comment by goodnewso** [comment]
do you mean the full solution of the project
