### ISSUE TITLE
.net 3.5 release

### ISSUE THREAD

**Issue by FruitcakeElemental** [Fody/PropertyChanged#323]
Hi guys, wondering if its possible to get a .net 3.5 version? I'm looking hoping to work with this project in unity but unity only has stable support for 3.5 at this point, it has experimental support for 4.6 but that's a no go for us at the moment (judging by their forums).

**Comment by SimonCropp** [comment]
@FruitcakeElemental sorry i am already struggling to support the existing runtime. i dont have capacity to support runtime that support ended for 5+ years ago 

more details https://github.com/Fody/Fody#supported-runtimes

if i was being paid to provide support it would be a different matter.

**Comment by FruitcakeElemental** [comment]
Yeah not long after that I decided to figure out how hard it would be to make the change by just adding the 3.5 project target, 300+ errors... sounds like a lot of work.

Feel free to close the issue if you don't think you're ever going to get around to it, I've decided to just manually write the boilerplate code.

Thanks

**Comment by SimonCropp** [comment]
again, sorry, but i simply dont have the capacity to support this
