### ISSUE TITLE
Avalonia controls inherit from INotifyPropertyChanged but aren't recognised by the Event Invoker

### ISSUE THREAD

**Issue by distantcam** [Fody/PropertyChanged#335]
Avalonia (http://avaloniaui.net/) has controls that inherit from the base `AvaloniaObject` class https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/AvaloniaObject.cs. This class implements INPC and has this event invoker.

`protected void RaisePropertyChanged(AvaloniaProperty property, object oldValue, object newValue, BindingPriority priority = BindingPriority.LocalValue);`

When using PropertyChanged I get the following error.

> Could not inject EventInvoker method on type 'Cyclops.UI.Main.MainView'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on Cyclops.UI.Main.MainView.

I can work around the problem by adding `DoNotNotify` to all my views, but it would be nice to not have to do that.

**Update** I also realised the INPC event is explicitly defined too, which is also why the EventInvoker can't just make it's own method.

**Comment by worldbeater** [comment]
Explicit INCP implementations support would definitely be a nice feature, many mature MVVM frameworks use explicit implementations. One of them is my favorite one, [Reactive UI](https://github.com/reactiveui/ReactiveUI/blob/74b25861184ce59f2e1e890efa0faf2324991d45/src/ReactiveUI/ReactiveObject.cs#L67). Currently, a ViewModel marked with `[AddINotifyPropertyChangedInterface]` can not inherit from `ReactiveObject` - we have to write a decorator that overrides `RaisePropertyChanged` method, making it non-explicit.

**Comment by ltrzesniewski** [comment]
@worldbeater that's a different issue than what's raised here.

But for your case, explicitly implemented methods simply have a *different* name in metadata (they don't really have a name in C#). So just add this to `FodyWeavers.xml`, I haven't tested it but it *should* work:

```XML
<Weavers>
  <PropertyChanged EventInvokerNames="ReactiveUI.IReactiveObject.RaisePropertyChanged, RaisePropertyChanged" />
</Weavers>
```

Don't forget to add any of your own invoker names.

**Comment by ltrzesniewski** [comment]
Hmm... actually no, forget what I said above. That method is private.

**Comment by ltrzesniewski** [comment]
@worldbeater I just saw your update (there's no notification for edits). Maybe you should try [ReactiveUI.Fody](https://github.com/kswoll/ReactiveUI.Fody) instead of PropertyChanged.Fody.

ReactiveUI seems to do things... [differently](https://github.com/reactiveui/ReactiveUI/issues/812). At least differently enough that I'm not sure if trying to make PropertyChanged.Fody work with it out of the box is necessarily a good idea.

If you still want to continue using PropertyChanged.Fody, I'd stick with the "decorator" as you call it , just put it in a separate class and derive from that instead of `ReactiveObject`.

&lt;/off-topic&gt;

**Comment by SimonCropp** [comment]
this should now be fixed

**Comment by SimonCropp** [comment]
ok re-reviewing this issue i am going to close a "Avalonia is not supported OOTB". you will need to use a custom base class with a compat onpropchanged method
