### ISSUE TITLE
Exception "Sequence contains more than one matching element" 

### ISSUE THREAD

**Issue by josesimoes** [Fody/PropertyChanged#337]
After updating an "old" UWP project to Fall Creator and latest PropertyChange from Nuget, the build suddenly broke with the following exception:
```
Exception:
Sequence contains more than one matching element
StackTrace:
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ModuleWeaver.InjectMethod(TypeDefinition targetType, String eventInvokerName)
   at ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType)
   at ModuleWeaver.FindMethodsForNodes()
   at ModuleWeaver.Execute()
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 83
Source:
System.Core
```

After sometime I was able to isolate the issue and made a class that reproduces the issue. See attached (mind renaming the file).

[Class1.cs.RENAMEME.txt](https://github.com/Fody/PropertyChanged/files/1985892/Class1.cs.RENAMEME.txt)

 * [x] Uploaded a minimal solution that reproduces the problem with the fewest moving pieces. Preferably a public GitHub repository.
 * [ ] Submitted a PR (https://help.github.com/articles/about-pull-requests/) with a failing unit test.
 * [ ] Submitted a PR (https://help.github.com/articles/about-pull-requests/) with a fix.

**Comment by ltrzesniewski** [comment]
I haven't tested this, but from a quick glance at the source code...

It should work if you remove `[AddINotifyPropertyChangedInterface]` and just make the class implement `INotifyPropertyChanged` directly instead (ie `Class1 : ContentDialog, INotifyPropertyChanged`).

`[AddINotifyPropertyChangedInterface]` adds a *second* `PropertyChanged` event, which is wrong here. It should probably reuse an existing event.

**Comment by josesimoes** [comment]
@ltrzesniewski thank for the suggestion. I made those changes in order to succeed with the build.

Nevertheless (because I've seen similar issues/questions) I thought on reporting it in case you guys wanted to add any extra check on the code and report a helpful exception message instead of the general Linq exception that is there now when these situations occur.

**Comment by ltrzesniewski** [comment]
And you did well, thanks for reporting the issue (I'm the one responsible for the crappy error message here).

**Comment by SimonCropp** [comment]
i added a better exception in 2.5.6
