### ISSUE TITLE
Could not inject EventInvoker method

### ISSUE THREAD

**Issue by arnemolland** [Fody/PropertyChanged#338]
This issue seems to be the same as in #316 and is as of now present in PropertyChanged 2.5.6 / Fody 3.0.3 when used in Xamarin.Forms solutions, temporary workaround has been to downgrade the respective packages to 2.2.10 and 2.5.0. Minimal repro has been uploaded [here](https://github.com/arnemolland/FodyRepro). I've yet to test this issue on a Windows PC, however both VSMac and msbuild fails. I'm currently on Xamarin.Forms 3.0.0.446417.

Steps to reproduce:
1. Create a blank Xamarin.Forms application (netstandard 2.0 in this case).
2. Add PropertyChanged 2.5.6 package, adding Fody 3.0.3.
3. Add FodyWeavers.xml to projects, add weaver `<PropertyChanged/>` or `<PropertyChanged EventInvokerNames="RaisePropertyChanged" />`.
4. Build either with VS or msbuild.

Full msbuild log:
```
MSBUILD : error : Fody: An unhandled exception occurred:
MSBUILD : error : Exception:
MSBUILD : error : Failed to execute weaver /Users/arnemolland/.nuget/packages/propertychanged.fody/2.5.6/netclassicweaver/PropertyChanged.Fody.dll
MSBUILD : error : Type:
MSBUILD : error : System.Exception
MSBUILD : error : StackTrace:
MSBUILD : error :   at InnerWeaver.ExecuteWeavers () [0x0007a] in C:\projects\fody\FodyIsolated\InnerWeaver.cs:208 
MSBUILD : error :   at InnerWeaver.Execute () [0x0004d] in C:\projects\fody\FodyIsolated\InnerWeaver.cs:103 
MSBUILD : error : Source:
MSBUILD : error : FodyIsolated
MSBUILD : error : TargetSite:
MSBUILD : error : Void ExecuteWeavers()
MSBUILD : error : Could not inject EventInvoker method on type 'FodyRepro.App'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on FodyRepro.App.
MSBUILD : error : Type:
MSBUILD : error : Fody.WeavingException
MSBUILD : error : StackTrace:
MSBUILD : error :   at ModuleWeaver.InjectMethod (Mono.Cecil.TypeDefinition targetType, InvokerTypes& invokerType) [0x0005e] in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:102 
MSBUILD : error :   at ModuleWeaver.AddOnPropertyChangedMethod (Mono.Cecil.TypeDefinition targetType) [0x0005c] in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:28 
MSBUILD : error :   at ModuleWeaver.FindMethodsForNodes () [0x00026] in C:\projects\propertychanged\PropertyChanged.Fody\MethodFinder.cs:237 
MSBUILD : error :   at ModuleWeaver.Execute () [0x00042] in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:18 
MSBUILD : error :   at InnerWeaver.ExecuteWeavers () [0x0006b] in C:\projects\fody\FodyIsolated\InnerWeaver.cs:204 
MSBUILD : error : Source:
MSBUILD : error : PropertyChanged.Fody
MSBUILD : error : TargetSite:
MSBUILD : error : Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)
```

**Comment by SimonCropp** [comment]
@ltrzesniewski thoughts on this one?

**Comment by ltrzesniewski** [comment]
@SimonCropp I tried to see what's wrong in the last repro uploaded by @arnemolland, but VS refused to load it because I didn't have Xamarin installed. And then I forgot about it 😉 

I'll take a look.

**Comment by ltrzesniewski** [comment]
@arnemolland Ok so I've installed Xamarin and tested your repro.

You've used the following config:

```XML
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
    <PropertyChanged EventInvokerNames="RaisePropertyChanged" />
</Weavers>
```

But the issue here is that `App` inherits from `Application` which ultimately inherits from `BindableObject` which implements `INotifyPropertyChanged`, **but** it declares an event invoker named `OnPropertyChanged`.

=> if you put `EventInvokerNames="OnPropertyChanged"` in your config or if you remove the `EventInvokerNames` attribute altogether, the project compiles just fine.

**Comment by ltrzesniewski** [comment]
You're welcome. Your repro compiled fine when I removed the attribute, so if you manage to extract an example which fails without the attribute, feel free to post it.
