### ISSUE TITLE
Have On_property_Changed events also deliver the old value with special signature

### ISSUE THREAD

**Issue by RedX2501** [Fody/PropertyChanged#341]
The `On_property_Changed` is very useful when adding property changed watchers when a property has changed.

Unfortunately the same mechanism cannot be used to unregister the previous delegate attached to the previous object.

It would be nice if we could either extend `On_property_Changed` so that when given with a signature such as:

   void OnNameChanged(string oldValue)

it would provide the old value as well so we could undo whatever was done to that property before.

Probably it would need to be a nullable to also support value types.

Example:

```
class A {
   public SomeOtherClass Classy { get; set;}

   private OnClassyChanged(SomeOtherClass old){
      if (old != null) {
          old.PropertyChanged -= WatchChanges;
      }

      if (Classy != null) {
          Classy.PropertyChanged += WatchChanges;
      }
}
```

**Comment by RedX2501** [comment]
It seem that this feature is already supported although undocumented. I discovered this works by looking at the code when I wanted to implement this.

Can the Wiki page on OnPropertyChanged be updated to show this feature? I would do that if I could edit the page.

**Comment by SimonCropp** [comment]
what changes would u like done?

**Comment by RedX2501** [comment]
As a reminder to myself:

`void On_properyName_Changed(object old, object new)`

is the current expected signature.

Could the signature maybe be changed to actually provide typed values? I mean they are known from the proerty.

**Comment by ltrzesniewski** [comment]
Hmm, yes the code [currently requires](https://github.com/Fody/PropertyChanged/blob/fe1b43330df27abd4d63a0c69ba08581d36a4773/PropertyChanged.Fody/OnChangedWalker.cs#L182-L188) `object` parameters. I don't know why, from a quick glance at the code it doesn't seem this would be too hard to change, but I may be wrong.

**Comment by tom-englert** [comment]
I had this in my "private backlog" for quite a while, but now found some to look at this.
