### ISSUE TITLE
Again about Equals vs. ==

### ISSUE THREAD

**Issue by AlexEPetrov** [Fody/PropertyChanged#347]
Hi,

Reviewing migration from v. 1 to v.2, we found differences: old version used == while new one - uses Equals in the beginning of the property setters.
And I think it can give unpredictable results in situation when you try to assign different value of reference type, but this new value can be EQUAL (logically, as Equals says) to current one.
But A Equals B does not mean that a property should ignore assignment of B just because its equal to A.

Example (pseudocode to be short):

public class MyStringType
{
    public MyStringType(string value) { Value = value; }
     override Equals(A, B) { return string.Compare(A.Value, B.Value, IgnoreCase); }
     public String Value {get; set;}
}

And main class:

public class MainClassProcessedByFody
{
     public MyValue {  get; set; }
}  

Now imagine that you execute the code:

var storage = new MainClassProcessedByFody();
storage.MyValue = new MyString("ABC");
storage.MyValue = new MyString("abc");

After this, storage.MyValue will be first instance with ABC, and its really not correct, I think.
So, question - how to avoid this? Probably some option for v.2 compatibility?
Current CheckForEquality option is too strong - it will disable any check, including  ==.
Or returning to old version is the only option?

Thanks
Alex

**Comment by SimonCropp** [comment]
Shouldnt == and equals do the same thing

> Override the Equals method whenever you implement the equality operator (==), and make them do the same thing. 

https://msdn.microsoft.com/en-us/library/7h9bszxx(v=vs.110).aspx

**Comment by AlexEPetrov** [comment]
Thanks for comment. Though the impression after reading docs is that I have to implement Equals if I implement ==, but not opposite. But main idea of the question - current implementation does not allow to implement old-style and probably reasonable code:

if (_currentValue.ReferenceEquals(value))    // similar to default == implementation
   return;

The point is - here is property of reference type. And new value is another instance of reference type and the task is to store exactly new instance as property value regardless of Equals logic. Yes, objects can be equal (according to Equals result), but they are still different (reftype) objects. Do you think it's completely invalid case?

**Comment by SimonCropp** [comment]
TBH i dont really have an opinion either way. i always overridden `Equals` and `==` together. so it will never effect me. 

happy to a PR that toggles the equality check

**Comment by tom-englert** [comment]
@AlexEPetrov If you consider "ABC" to be equal to "abc", than none of your code should make any assumptions on the actual instance, so in your sample above, MyValue does not need to change, since you declared both values to be equal. If that really matters to your code, your design is wrong and you must not override equals for your object, but provide some external comparer to use when necessary.

**Comment by ltrzesniewski** [comment]
I disagree with making reference equality the default equality comparison.

Besides making a *nasty* breaking change, `EqualityComparer<T>.Default` is the de-facto standard equality comparison method used in the framework in places such as `HashSet<T>`.

Also, I wouldn't want a change notification when I set a `string` property to a different instance of the same string value (yes, I know `string` is special-cased, but this can apply to other object types too).

If you're going to do a PR for that, *please* at least make the change configurable, and make it non-default behavior.

**Comment by robcecil** [comment]
Was there a migration post or something in the release notes about the internal change from == to Equals in the generator? Seems like a huge change that should not have gone unnoticed, if you were paying attention.

**Comment by SimonCropp** [comment]
There was an issue assigned to a milestone 
https://github.com/Fody/PropertyChanged/issues/309
