### ISSUE TITLE
Nullreference exception when generic class contains generic KeyValuePair property

### ISSUE THREAD

**Issue by RolfSzomor** [Fody/PropertyChanged#356]
Reproduced with version: (all the most recent PropertyChanged nugets: 2.5.9, 2.5.8, 2.5.7, 2.5.6 etc....)
Reproduced with class libraries (.net framework, .net core, .net standard : all of them)
Reproduction steps:

1.
Add PropertyChanged Fody nuget package to project

2.
Add weaver file (FodyWeavers.xml) with content:
`<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <PropertyChanged />
</Weavers>`

3.
Add a class with the following code:

`using System.Collections.Generic;`
`using System.ComponentModel;`
`namespace ClassLibrary1`
`{`
`    public class Class1<T> : INotifyPropertyChanged`
`    {`
`        public KeyValuePair<string, T> Kvp { get; set; }`
`        public event PropertyChangedEventHandler PropertyChanged;`
`        public void RaisePropertyChanged(string propertyName)`
`        {`
`            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));`
`        }`
`    }`
`}`

If you build the solution, Fody will crash with NullReferenceException
Note: this is the only "special" type combination I had this issue with, never encountered the same with other standard .net types.

**Comment by SimonCropp** [comment]
this is now deployed. with thanks to @tom-englert

**Comment by tom-englert** [comment]
:smile:
