### ISSUE TITLE
I updated my visual studio and now fody is creating bugs.

### ISSUE THREAD

**Issue by frooti7** [Fody/PropertyChanged#360]
Faced this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: Could not load 'ModuleWeaver' from 'PropertyChanged.Fody, Version=2.5.10.0, Culture=neutral, PublicKeyToken=null'
 due to ReflectionTypeLoadException.

It is possible the package needs to be updated.
exception.LoaderExceptions:

System.IO.FileLoadException: Could not load file or assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=1ca091877d12ca03' 
or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=1ca091877d12ca03' ---> 
System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	Infinity.Core		1	

Then updated my ProperyChanged.Fody to latest version. But then all the references get lost. It is unable to recognize [AddINotifyPropertyChangedInterface]. Have tried cleaning, and rebuilding. 
Please help. This has got my work stuck like hell

**Comment by BrunoJuchli** [comment]
Please provide a repro. I.e. the minimum amount of code to reproduce the issue?
Have you tried (in the following order):
- Closing Visual Studio
- Cleaning your repository
- clearing your package cache(s)
- re-opening VS
- restoring packages
- rebuilding
?

What did you try to resolve the issue?

**Comment by SimonCropp** [comment]
sorry but i have to close this with "please read the issue template" https://github.com/Fody/PropertyChanged/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Reasons.

 * no repro
 * no md formatting
 * no listing of versions of relevant pieces.

happy to reopen when those are provided.

If you want me to help you with low level debugging of your solution, consider contribution to https://opencollective.com/fody/donate
