### ISSUE TITLE
MSBuild error: *Undefined* does not exist

### ISSUE THREAD

**Issue by c-lamont** [Fody/PropertyChanged#364]
I recently updated my .Net standard 2.0 project `PropertyChanged.Fody` nuget package from `2.5.9 `to `2.5.12`.

This causes a build error: `(FodyTarget target) -> 
  MSBUILD : error : Fody: SolutionDir "/xxx/xxx/xxx/*Undefined*" does not exist.`

The same thing happens when updating `ConfigureAwait.Fody` nuget package from `2.1.1` to `2.1.3`

**Comment by ltrzesniewski** [comment]
Is your Fody version up to date? There was a very similar bug fixed in v3.2.9

If you're up to date, can you post the full log?
Are you trying to build a project or a solution?

**Comment by c-lamont** [comment]
@ltrzesniewski You are correct. The package does not download the latest Fody package but 3.2.6.

Manually installing the latest fixed it. I see it is also mentioned in the readme that you should download the Fody package separately. Would be nice though if the PropertyChanged.Fody package would implement the latest Fody version as well.

**Comment by ltrzesniewski** [comment]
Yes, but I can't do that myself 😉 

I've sent a reminder: https://github.com/Fody/Fody/pull/561#issuecomment-427867026
