### ISSUE TITLE
The "Fody.WeavingTask" task could not be initialized with its input parameters.

### ISSUE THREAD

**Issue by dstampher** [Fody/PropertyChanged#372]
I was using the Fody and Fody.PropertyChanged NuGet packages successfully in my solution until I was installing another package and saw there we're updates available to those previously mentioned packages.  After updating, the following errors are preventing me from building my solution.

> The "Fody.WeavingTask" task could not be initialized with its input
> parameters.
> 
> The "GenerateXsd" parameter is not supported by the "Fody.WeavingTask"
> task. Verify the parameter exists on the task, and it is a settable
> public instance property.

I went and checked the GitHub page for Fody, wondering if there was something new I had to add to FodyWeavers.xml or something...that file is still the same as it was before I updated.

    <?xml version="1.0" encoding="utf-8"?>
    <Weavers>
      <PropertyChanged />
    </Weavers>

Why did simply updating these packages break my app?

**Comment by ltrzesniewski** [comment]
Hi, looks like you're somehow using the Fody.targets from v3.3.3 alongside a previous version of the dll. The `GenerateXsd` parameter was added in v3.3.3.

If you're using the old csproj format, make sure you don't see multiple references to `Fody.targets`. If in doubt, uninstall the Fody package, make sure there's no reference to Fody in your csproj file, and then reinstall it again.

**Comment by dstampher** [comment]
@ltrzesniewski Hi thanks, I just figured that out before you posted.  Removing the old references in my csproj file did fix the problem.  I had done updates on Fody in the past and this issue had never happened before.

**Comment by ltrzesniewski** [comment]
Ok, glad you got it fixed :)
This shouldn't have happened this time either, but your csproj got corrupted somehow (I would suspect a bad merge which duplicated the `Import` tag).
