### ISSUE TITLE
How to enable injection only for specific class?

### ISSUE THREAD

**Issue by DTX-92** [Fody/PropertyChanged#374]
I've read the docs, but i don't know what is namepspace filters. How to enable injection only for MySuperNamespace.Part1.MySuperClass? Should I write something in FodyWeavers.xml?

**Comment by tom-englert** [comment]
See https://github.com/Fody/PropertyChanged#notes:

* To scope the rewriting only to specific classes, and not the whole Assembly, you can use the [`FilterType` attribute](https://github.com/Fody/PropertyChanged/blob/f4905b4f04335e393c8350cc5f06f02614241483/PropertyChanged.Fody/TypeNodeBuilder.cs#L18). This changes the general behavior from from opt-out to opt-in. Example: `[assembly: PropertyChanged.FilterType("My.Specific.OptIn.Namespace.")]`. The string is interpreted as a Regex, and you can use multiple filters. A class will be weaved, if _any_ filter matches.

**Comment by DTX-92** [comment]
I've already read all docs and found it. But I dont know where i should specify it

**Comment by tom-englert** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/set-assembly-attributes

**Comment by Basti82b** [comment]
Wouldn't it be better if only classes with a certain attribute were changed? I know [AddINotifyPropertyChangedInterface], but I want to implement INotifyPropertyChanged myself and leave the rest to Fody.

**Comment by SimonCropp** [comment]
@Basti82b 

>  I want to implement INotifyPropertyChanged myself and leave the rest to Fody.

whats stopping you from doing that?

**Comment by Basti82b** [comment]
@SimonCropp 
Nothing.

"Note that all classes that implement INotifyPropertyChanged will have property notification injected irrespective of the use of this attribute." ([source](https://github.com/Fody/PropertyChanged/wiki/Attributes#addinotifypropertychangedinterfaceattribute)) 

In my opinion it should be opt-in and not opt-out with a filter.

**Comment by SimonCropp** [comment]
@Basti82b a default had to be picked. u can use the filter syntax to change that default. It wont be changing now. BTW 
To be using fody [you should be a patron](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md).

**Comment by phDaveGit** [comment]
I'm using latest Xamarin Forms 4.2.0.778, the latest Fody 6.0 and PropertyChanged weaver 3.13.

I am trying to declare to this line to opt-out in the Assembly file, however PropertyChanged type or namespace could not be found.

I need to do this because it appears that the latest version of ReactiveUI, v10.2.2 and ReactiveUI.Fody 10.2.2 has a conflict.

Visual Studio is telling me that I need to install nuget Microsoft.TeamFoundationServer.ExtendedClient but I cannot seem to install this?!?

Anyone know which nuget I'm supposed to be using?
