### ISSUE TITLE
Hide the package dependency

### ISSUE THREAD

**Issue by pikausp** [Fody/PropertyChanged#376]
When I use `Fody` in my libraries which I package and publish to a private NuGet feed all of the projects that reference my package create a transitive dependency on `Fody` and the weavers.

Is there a way around it? I wasn't able to find anything in the docs.

**Comment by ltrzesniewski** [comment]
I guess you're using the new project format. Just add a `PrivateAssets="all"` attribute to the `<PackageRefernce>` tags of Fody and its weavers.
