### ISSUE TITLE
Fody and weaving without a reference to PropertyChanged.Fody.dll issue

### ISSUE THREAD

**Issue by mahara** [Fody/PropertyChanged#38]
@SimonCropp:
Following this discussion (https://github.com/Fody/PropertyChanged/issues/14#issuecomment-19846970), I've tried it. And what I've done:
- Remove reference to PropertyChanged.Fody package
- Add PropertyChanged attributes as described in here (https://github.com/Fody/PropertyChanged/wiki/WeavingWithoutAddingAReference)
- Have FodyWeavers.xml configured as follow:

```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
</Weavers>
```

However, I encountered the following error:

Error/10/Fody: You don't seem to have configured any weavers. Try adding a Fody nuget package to your project. Have a look here http://nuget.org/packages?q=fody for the list of available packages.

- If I change FodyWeavers.xml to below:

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <PropertyChanged />
</Weavers>
```

I got the following error:

Error/12/Fody: Could not find a weaver named 'PropertyChanged'. 
If you have nuget package restore turned on you probably need to do a build to download the weavers. 
Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot to add the appropriate nuget package. 
Perhaps you need to run 'Install-Package PropertyChanged.Fody'. This url may provide more information http://nuget.org/packages/PropertyChanged.Fody/ .

It seems there's a conflicting issue. Or I might have been missing something.

So, how am I supposed to resolve this issue?

Thanks.

**Comment by mahara** [comment]
This approach doesn't seem to work anymore with latest Fody version, not sure since what version exactly.

Here's output from the Build in VS:
```
2>    Fody: Fody (version 1.29.4.0) Executing
2>      Fody/PropertyChanged:   	No reference to 'PropertyChanged' found. References not modified.
2>    Fody:   Finished Fody 918ms.
```

**Comment by mahara** [comment]
https://github.com/Fody/Fody/issues/238

**Comment by SimonCropp** [comment]
What makes u think it didnt work. That message is just saying it did not need to remove the reference

**Comment by mahara** [comment]
I checked through .NET Reflector that the properties don't get re-written.
When in fact, I accidentally decorated them with DoNotNotifyAttribute.

Closing this.

**Comment by mahara** [comment]
As a side note, I don't really understand what the log message "References not modified." means. I initially thought it means that the output assembly not being re-written.

**Comment by SimonCropp** [comment]
it removes the reference to the attribute assembly so you dont need to deploy that file

**Comment by mahara** [comment]
OK. Thanks, Simon.
