### ISSUE TITLE
override base class abstract properties doesn't emit dependent properties on the same class

### ISSUE THREAD

**Issue by vmartos** [Fody/PropertyChanged#384]
Hello,

I'm using the latest version of PropertyChanged.Fody 2.6.0, and have the following problem, given the following classes (Model, ViewModelBase<T> and ViewModel):

```
 [PropertyChanged.AddINotifyPropertyChangedInterface]
    public abstract class ViewModelBase<T>
    {
        public abstract T Model { get; set; }

        // common logic managed by ViewModelBase
    }

    [PropertyChanged.AddINotifyPropertyChangedInterface]
    public class Model
    {
        public string Prop1 { get; set; }
        public string Prop2 { get; set; }
    }

    public class TestViewModel : ViewModelBase<Model>
    {
        public override Model Model { get; set; }

        public string Prop2
        {
            get
            {
                return Model.Prop2;
            }
            set
            {
                Model.Prop2 = value;
            }
        }

        public string Prop1 { get { return Model.Prop1; } }
    }
```
produces the following code:
```
public class TestViewModel : ViewModelBase<Model>
  {
    public override Model Model
    {
      get
      {
        return this.<Model>k__BackingField;
      }
      set
      {
        if (object.Equals((object) this.<Model>k__BackingField, (object) value))
          return;
        this.<Model>k__BackingField = value;
        this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Model);
      }
    }

    public string Prop2
    {
      get
      {
        return this.Model.Prop2;
      }
      set
      {
        if (string.Equals(this.Prop2, value, StringComparison.Ordinal))
          return;
        this.Model.Prop2 = value;
        this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Prop2);
      }
    }

    public string Prop1
    {
      get
      {
        return this.Model.Prop1;
      }
    }
  }
```

And i expect that the overriden Model setter be:

```
   public override Model Model
    {
      get
      {
        return this.<Model>k__BackingField;
      }
      set
      {
        if (object.Equals((object) this.<Model>k__BackingField, (object) value))
          return;
        this.<Model>k__BackingField = value;
        this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Prop2);
        this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Prop1);
        this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Model);
      }
```

I have already seen closed (unsolved) issues about this topic of viewmodel inheritance and that child classes having dependencies with properties of the base class, and I understand why it can't emit the base class properties for the child classes. But I did not see this type of logic on those issues.
What I did, is force the child classes to implement the properties by setting it to be abstract, so I expect that Fody.PropertyChanged to emit property changes on properties with dependencies when an abstract base class property is overriden.

Note: If I add the attribute [DependsOn(nameof(Model))] it works as expected, but I need to not force this attribute because I have viewmodels with lots of "proxy" properties to the Model

Thank you,

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by vmartos** [comment]
Ok, we use the DependsOn attribute for now, if you finally decide to fix this I will update.
Thank you.

**Comment by SimonCropp** [comment]
@vmartos no one “decided not to fix” this. Tbh i didnt even bother understanding what your specific issue is. But it seems you didnt read the issue template 
https://github.com/Fody/PropertyChanged/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

If u re read that template, and follow its guidelines, this issue has a higher chance of getting some attention.
