### ISSUE TITLE
Unnecessary Rebuild Triggered with Latest Version (2.6.1) on VS2019

### ISSUE THREAD

**Issue by mahara** [Fody/PropertyChanged#397]
The combination of latest Fody (4.2.1) and PropertyChanged.Fody (2.6.1) causes unnecessary rebuild of projects with a WPF project on VS2019.
It seems to be caused by "'PropertyChanged.dll' is missing from output location", see the Output log below for details.

### Steps to reproduce
1. Open VS2019
2. Set the "MSBuild project build output verbosity" to "Diagnostics" in Options/Projects and Solutions/Build and Run
3. Create a new WPF project using .NET Framework 4.7.2
4. Install latest PropertyChanged.Fody (2.6.1) and Fody (4.2.1) NuGet packages
5. Build solution for the first time and observe the Output log as follows:
```
1>Project 'WpfApp' is not up to date. Missing output file 'C:\Development\WpfApp\WpfApp\bin\Debug\WpfApp.exe'.
...
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
6. Build the solution again, observe the Output log, and notice that unnecessary rebuild is being triggered:
```
1>Project 'WpfApp' is not up to date. CopyLocal reference 'C:\Development\WpfApp\WpfApp\bin\Debug\PropertyChanged.dll' is missing from output location.
...
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

### Expected outcome
No rebuild of projects should be triggered upon subsequent build (assuming no changes in code), with the following Output log:
```
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by SimonCropp** [comment]
Did u read the issue template?

**Comment by ltrzesniewski** [comment]
I'm pretty sure this is solved by adding `PrivateAssets="all"` to the `PackageReference` of PropertyChanged. If you're using packages.config, you may try adding `developmentDependency="true"` but I'm not sure it will work.

@SimonCropp I think the `PrivateAssets="all"` thing should be added to [the usage guidelines](https://github.com/Fody/Home/blob/master/pages/usage.md) - what do you think? It won't generalize to weavers that keep their lib references though.
Adding this info to each weaver's readme would be nice too (but it's quite a bit of work).

**Comment by mahara** [comment]
> Did u read the issue template?

I did. But this seems to affect everyone.

**Comment by SimonCropp** [comment]
this seems to only effect the old style of csproj projects. cant repro on the new sdk style. since the old style of csproj is being phased out by MS i think we dont debug further and just close this

**Comment by SimonCropp** [comment]
@mahara closing this one for now. the fix from your perspective is to update your project to the new csproj format. If you want to submit a PR that fixes this for the old project system, it will be considered as long as it does not add significant complexity. If you dont have capacity to submit a PR, but really need this fixed, feel free to purchase some support time https://opencollective.com/fody/contribute/tier/7087-3-hours-support
