### ISSUE TITLE
Visual Studio 2017 Nuget Error

### ISSUE THREAD

**Issue by grmn28985** [Fody/PropertyChanged#408]
When installing the Nuget package for this in a WPF project for .NET 4.7.2 in Visual Studio 2017 Enterprise, I get the following error when installing either Fody.PropertyChanged 3.0.0 or Fody 5.0.1:

The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  [MyPathHere]\Git Repos\TCCv2\packages\Fody.5.0.0\build\Fody.targets

This didn't happen last year in Visual Studio 2013 with older versions.

**Comment by SimonCropp** [comment]
To be raising issues [you and your employer should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SimonCropp** [comment]
can u try fody version5.0.3

**Comment by grmn28985** [comment]
Yes, that worked well.
