### ISSUE TITLE
BeforeAfter feature

### ISSUE THREAD

**Issue by OlegNadymov** [Fody/PropertyChanged#420]
It would be great to have support for below syntax:
```c#
public void OnPropertyChanged(string propertyName, object after)
```
And for ``after`` use ``value`` from setter and don't use getter of the property. It will be useful for properties with complex getter.
Example:
```c#
public class Person : INotifyPropertyChanged
{
    private string _name;

    public event PropertyChangedEventHandler PropertyChanged;

    public string Name 
    { 
        {
            get => _name ?? (_name = GetCustomValue());
            set => _name = value;
        }
   }

    public void OnPropertyChanged(string propertyName, object after)
    {
        //Perform property validation
        var propertyChanged = PropertyChanged;
        if (propertyChanged != null)
        {
            propertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    private void GetCustomValue([CallerMemberName] String propertyName = "")
    {
     // heavy calculation or
     // recursion for Id properties and their reference properties, e.g. :
     // CliendId + Client. 
    }
}
```
And the compiled code:
```c#
public class Person : INotifyPropertyChanged
{
    private string _name;

    public event PropertyChangedEventHandler PropertyChanged;

    public string Name
    {
        get => _name ?? (_name = GetCustomValue());
        set
        {
            _name = value;
            OnPropertyChanged("Name",  value);
        }
    }

    public void OnPropertyChanged(string propertyName, object after)
    {
        //Perform property validation
        var propertyChanged = PropertyChanged;
        if (propertyChanged != null)
        {
            propertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    private void GetCustomValue([CallerMemberName] String propertyName = "")
    {
     // heavy calculation or
     // recursion for Id properties and their reference properties, e.g. :
     // CliendId + Client. 
    }
}
```

In my case I have property ``Client`` and ``CliendId``. ``Client`` has getter with ``GetCustomValue`` that depends on ``ClientId``. If I write below code:
```c#
   Client = null;
```
After execution this line ``Client`` won't be ``null`` because in getter the private field ``_client`` reinitialized based on ``ClientId``. ``Client`` will be the same value as before this line. For this case I need to have after value. But this value should be take from setter's ``value``. Otherwise if ``after`` takes from getter the original property will be reinitialized.

Moreover, for properties without setter call ``OnPropertyChanged(string propertyName)`` without ``after`` argument because their getter can call complex method with recursion:
```c#
    public string Name
    {
        get => _name ?? (_name = GetCustomValue());
        set
        {
            _name = value;
            OnPropertyChanged("FullName"); // without after value
            OnPropertyChanged("Name", value); // with after value
        }
    }

    public string FullName => GetFullName();

    private string GetFullName()
    {
      //also can contain heavy calculation or recursion
       if (Name == null) 
       { 
           return "anonymous";
       }
       return  "Mr/Ms. " + Name;
    }
```
The main idea is not to use getter to get``after``.
I hope you will manage to understand my explanation.
Is it possible to make this feature?

**Comment by ltrzesniewski** [comment]
There's already a ["BeforeAfter"](https://github.com/Fody/PropertyChanged/wiki/BeforeAfter) method signature that you can use (a generic version is also available).

**Comment by OlegNadymov** [comment]
Yes. it calls getter. It is not suitable for my case

**Comment by ltrzesniewski** [comment]
I suppose this could be added to the existing BeforeAfter feature as an option. The existing solution is a better default since it provides the final property value for cases when the setter has some logic which results is something else being assigned.

This would require some design work in order to decide how to supply that option. You could for instance add an attribute on the property, or on the class to set a default, or set a default on the assembly. But this would add quite a bit of complexity and I'm not sure if that would be a good investment. Another option would be to set the option in the FodyWeavers.xml file but that would be much less useful as it would necessarily impact the whole assembly.

This would only pay off if you have a large number of properties that would require this. If you only have a few of those, you can implement the change notification yourself by adding a `[DoNotNotify]` attribute on the property.

**Comment by OlegNadymov** [comment]
@ltrzesniewski thank you for your feedback. I have a lot of these properties. I understand that my suggestion require some design work, possible. So I think I will try to change logic inside my complex methods that are used for getters.

**Comment by SimonCropp** [comment]
@OlegNadymov  To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue).

**Comment by OlegNadymov** [comment]
@SimonCropp ok, I got you.

**Comment by OlegNadymov** [comment]
I made some changes in my code and managed to do what I wanted without BeforeAfter feature. I'm closing the issue.

**Comment by SimonCropp** [comment]
@OlegNadymov note u should also be a patron if you are using Fody https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#licensingpatron-faq
