### ISSUE TITLE
Compatibility with Realm database objects

### ISSUE THREAD

**Issue by VaslD** [Fody/PropertyChanged#421]
`Realm` database models inherit from `RealmObject` which fully implements `INotifyPropertyChanged`. However this is not recognized by **PropertyChanged.Fody**. After compiling with PropertyChanged installed, these objects no longer saves to the database. No error or exception is reported, all seems working but you just get blank data when accessing the database.

When opted-out (or not opted-in) by using PropertyChanged’s attributes or filters, these models then work as expected. So it’s clear that Realm and PropertyChanged are not compatible.

[An issue is already open on their repo.](https://github.com/realm/realm-dotnet/issues/1873) I’m wondering if PropertyChanged can detect objects inherit from `RealmObject` and skip code injection.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
