### ISSUE TITLE
Weaver fails when targeting netstandard < 2.0

### ISSUE THREAD

**Issue by tom-englert** [Fody/PropertyChanged#440]
MSBUILD : error : Fody: Could not find 'System.CodeDom.Compiler.GeneratedCodeAttribute'.

probably because before netstandard2.0 this type is in System.Diagnostics.Tools, and this is not in the search path.

I can take car of this.

**Comment by SimonCropp** [comment]
can u try 3.1.1

**Comment by tom-englert** [comment]
Now it fails on another type. 
This is not time critical for me. Let me take care, I'll add the tests for this and then fix it.

**Comment by SimonCropp** [comment]
How about instead we drop net standard 1. And move to 2 as the min?

**Comment by tom-englert** [comment]
Because it will be more effort to manage the shit storm when the first user steps into this...

**Comment by SimonCropp** [comment]
How about i email all the patrons and see if everyone is ok with net standard 2

**Comment by tom-englert** [comment]
I would vote for no ;-)
I've added the test and the fix; it's so cheap, it's not even worth thinking about to remove support for other frameworks.

**Comment by SimonCropp** [comment]
Lol. Ok show me the test

**Comment by tom-englert** [comment]
https://github.com/Fody/PropertyChanged/tree/master/SmokeTest

**Comment by SimonCropp** [comment]
@tom-englert kool. thanks. i will do a new deploy
