### ISSUE TITLE
Introduce a "OnChangedMethod" attribute

### ISSUE THREAD

**Issue by tom-englert** [Fody/PropertyChanged#453]
```c#
class MyClass : INotifyPropertyChanged 
{
    [OnChangedMethod(nameof(OnMyPropertyChanged))]
    int MyProperty { get; set; }

    void OnMyPropertyChanged()
    {
    }
}
```
Since we have a `nameof` operator today, we could decorate the property with a "link" to the on changed method. 
This will avoid the problems with renaming, and omit the compiler warnings that `OnMyPropertyChanged` is never used. It also will allow direct navigation to the method from the property.

This attribute would be optional, for those who like to use it.
To be fully backward compatible, the weaver would only check that, if the attribute is present, the name of the method matches the desired pattern. 

#447 could then also give a hint to properly decorate the property.

**Comment by ltrzesniewski** [comment]
> To be fully backward compatible, the weaver would only check that, if the attribute is present, the name of the method matches the desired pattern.

I'm not sure I understand what you mean here. Since there's an attribute to specify a method name, I'd expect to be able to freely choose whatever method name I want, without requiring it to match the `On`...`Changed` pattern.

This would also allow using a single method for multiple properties.

**Comment by tom-englert** [comment]
Yeah, this was just a suggestion to simplify implementation, not a requirement for backward compatibility.
Of course we could allow any name here.

**Comment by tom-englert** [comment]
@ltrzesniewski but looking at the code just validating would be doable without changing too much, however allowing any method name would require to rewrite a lot of code...

**Comment by ltrzesniewski** [comment]
It would need a few changes but not *that* much (basically adding the method info to `PropertyData`).

Also, we could allow the user to provide multiple `OnChangedMethod` attributes, to call multiple methods when a property changes.

**Comment by tom-englert** [comment]
https://github.com/Fody/PropertyChanged/blob/a9ec0d7a2f4b782aa7897dea4932e1871076e554/PropertyChanged.Fody/PropertyWeaver.cs#L120
But the code in charge does not get a PropetyData but only a PropertyDefinition, so you have to modify the complete call chain

**Comment by RedX2501** [comment]
> omit the compiler warnings that OnMyPropertyChanged is never used

Especially this part is very useful.

**Comment by ltrzesniewski** [comment]
I think changing the whole call chain may still be worth the effort. I can take a look at it maybe next week.

**Comment by ltrzesniewski** [comment]
It wasn't that bad. I made a draft that I will need to rebase in #464.

It enables stuff like that:

https://github.com/Fody/PropertyChanged/blob/aef044d5d7487de3b776e2df8a69284b21ce9192/TestAssemblies/AssemblyToProcess/ClassWithOnChangedCustomized.cs#L10-L12
