### ISSUE TITLE
AlsoNotifyFor not working

### ISSUE THREAD

**Issue by thudugala** [Fody/PropertyChanged#475]
In Version 3.2  [AlsoNotifyFor("FullName")] does not work. 
works in 3.1.3

.Net Framework 4.7.2

**Comment by SimonCropp** [comment]
@thudugala 
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

also share a failing unit test as a PullRequest

**Comment by sa-he** [comment]
@thudugala just go back to 3.1.3 and wait until a partron finds and reports the bug - this is what I do. Other open source projects appreciate bug-reports and consider it a contribution; this one doesnt. Version 3.2 breaks more than AlsoNotifyForAttribute only. But my employer is neither a patron (and most likely won't ever be). What shouly I do? Personally becomming a patron for work purposes? I just pick a version that works and be very careful in updating to the next version. Put every nuget update of fody packages in a separate commit, so reverting is quick and easy.

**Comment by SimonCropp** [comment]
@sa-he sorry but "it is broke please fix" is not enough to count as a OSS contribution. 

The minimum you should do is:

 * share a repro
 * submit a fialing tests as a PR
 * got to at least some effort of attempting to fix the issue yourself. share info of how far you got

if you dont want to be a proper contributor, then supply some small amount of money to help cover the cost of others doing the work.

As for this issue. why should you expect me to spend my free time to fix it when you dont want to put in any of your time?

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by sa-he** [comment]
@SimonCropp Some people would do the things you mentioned. Maybe even send a PR with a fix. But the things you listed as a 'minimum' are explicitly only allowed when being a patron. (see Fody contribution FAQ) So why should a non-patron spend any time, when it is not appreciated?

**Comment by SimonCropp** [comment]
@sa-he well i guess you got the outcome you hoped for. you dont contribute, you dont pay, you criticize and the bug has been fixed.

**Comment by pikausp** [comment]
@SimonCropp I think @sa-he raised a valid point "the things you listed as a 'minimum' are explicitly only allowed when being a patron". The guidelines do forbid you from doing any of that anyways, so no matter how much time you would put in (creating PR, tests, fixes etc), it wouldn't make sense unless you are a patron. 

Not starting a debate on the patron model, just that you should pick whether contributions are welcomed from non-patrons or not.

**Comment by SimonCropp** [comment]
@pikausp 

> The guidelines do forbid you from doing any of that anyways, so no matter how much time you would put in (creating PR, tests, fixes etc), it wouldn't make sense unless you are a patron.

that is not correct https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-contribute-a-pull-request

> Pull Requests from non-Patrons, that are of significant value to the larger Fody user base, may justify the effort in reviewing and merging.
