### ISSUE TITLE
IL code seems incorrect when combining generics and inheritance

### ISSUE THREAD

**Issue by tranb3r** [Fody/PropertyChanged#477]
When using a combination of generics and inheritance, the IL code generated by Fody.PropertyChanged does not look correct.

I have 3 classes, mixing generics and inheritance : `C -> B<T> -> A`
Here is the link the repro code:
https://drive.google.com/open?id=1ib1yYj588KmSGmsFYjsSQdrx9s9ClNBY

When not using Fody (TestFody2 solution), the compiler generates the following IL code for "set_foo" in "C" class:
![WithoutFody](https://user-images.githubusercontent.com/12516566/70715049-bc47c800-1ce9-11ea-948e-818ceece06c4.PNG)
You can see that it's calling "OnPropertyChanged" from "A" class, which is ok.

However, when using Fody (TestFody solution), the generated IL code for "set_foo" in "C" class looks like that:
![WithFody](https://user-images.githubusercontent.com/12516566/70715114-e305fe80-1ce9-11ea-878c-cd4741eefaf3.PNG)
You can see that it's now calling "OnPropertyChanged" from "B(string)" class, which seems incorrect (well it kind of works, but it's not what the compiler would do, since the method is defined in "A" class).

Also, you can see that the MethodRef table has a reference to "OnPropertyChanged" method when being generated by fody.
![WithFody2](https://user-images.githubusercontent.com/12516566/70715202-134d9d00-1cea-11ea-8829-78ebd311fbe4.PNG)
I think it should not be there, because the method is defined inside the assembly (in class "A").

Even if it works, this is not how the code should be generated, and it causes me some trouble why obfuscating my assembly with Babel obfuscator.
So I think this should be fixed. What do you think ?

Thanks

**Comment by ltrzesniewski** [comment]
Interesting. I confirmed that Fody correctly generates a call to `A.<>OnPropertyChanged` when `B` is not generic.

As for that MemberRef, it's actually used as the target of the `callvirt` instruction (you can see the `0A00000B` token in the binary code displayed by dnSpy). It should go away when the call is fixed.

---

For easier access, here's the repro code from the zip, (I removed unnecessary `[AddINotifyPropertyChangedInterface]` attributes):

```C#
[AddINotifyPropertyChangedInterface]
internal abstract class A
{
    public bool FooBar { get; set; }
}

internal abstract class B<T> : A
{
    public bool Bar { get; set; }
}

internal class C : B<string>
{
    public bool Foo { get; set; }
}
```

**Comment by tranb3r** [comment]
Thank you for fixing this issue.
@SimonCropp Is the 3.2.2 nuget coming soon ?

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
