### ISSUE TITLE
Question: AddINotifyPropertyChangedInterfaceAttribute inheritance

### ISSUE THREAD

**Issue by sidhants** [Fody/PropertyChanged#503]
Very new to using this plugin with Unity3D and I had some basic questions -
1) Where do I list the Assembly/s that I want PropertyChanged to work on?

2) Also, is the 'AddINotifyPropertyChangedInterfaceAttribute' if defined on a base class, inherited automatically by all derived classes? I am seeing this behavior even though inherited = false as below. Automatic is good but how can I control  the classes PropertyChanged will work on even if derived?

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
    public class AddINotifyPropertyChangedInterfaceAttribute : Attribute
    {
    }
Any info will be very helpful.
Thanks.

**Comment by SimonCropp** [comment]
it only targets the dll produced by the project it is installed in

the attribute doesnt inherit, but the INPC interface is applied to that class, and that implementation is inherited
