### ISSUE TITLE
Specify namespace for <>PropertyChangedEventArgs

### ISSUE THREAD

**Issue by tranb3r** [Fody/PropertyChanged#507]
Today, the "<>PropertyChangedEventArgs" class is created in the root namespace of the assembly.
Could it be created within a specific namespace instead (for example the default namespace for the assembly) ?
Use-case: when merging several assemblies that have been processed by fody.propertychanged, the corresponding "<>PropertyChangedEventArgs" classes conflict in the merged assembly.

**Comment by ltrzesniewski** [comment]
I'd rather use `Fody.[assembly name]` as the namespace (that would be more reliable, and Fody does not provide the default namespace information to its addins).

But IL merging could still easily fail for other reasons, for instance if you activate nullable reference types (the compiler will synthesize attributes). So I'm not sure making IL merging easier is a good idea anyway.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by tranb3r** [comment]
@SimonCropp 
Thanks for the quick fix !
Would it be possible to the same kind of change for the "ProcessedByFody" type ? (in Fody repo, not in PropertyChanged repo)

**Comment by SimonCropp** [comment]
now that i think about it doesn ILMerge handle conflicts for non public types automatically?

**Comment by SimonCropp** [comment]
>For private types, this is not a problem since no outside client can see it anyway, so ILMerge just does the renaming by default. 

https://github.com/dotnet/ILMerge/blob/master/ilmerge-manual.md

**Comment by tranb3r** [comment]
Actually, I'm not using ILMerge, but Babel Obfuscator, which has its own algorithm for merging assemblies.
The conflict is handled properly by Babel, but it raises a warning (found duplicate type in merged assembly). I can ignore it, but I'd rather not hide it, because for sure if this happens in my own code, I'd like to know about it.
Anyway, I still think it would be better to group inside their own unique namesapce the classes generated by fody.

**Comment by SimonCropp** [comment]
fair enough. i will look at fody marker type tomorrow.

**Comment by SimonCropp** [comment]
new version of Fody pushed
