### ISSUE TITLE
System.MethodAccessException when using ReactiveU.ReactiveObject

### ISSUE THREAD

**Issue by distantcam** [Fody/PropertyChanged#508]
PropetyChanged v3.2.3
ReactiveUI v11.1.6

```
System.MethodAccessException
  HResult=0x80131510
  Message=Attempt by method 'App.MainViewModel.set_Property(System.String)' to access method 'ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(System.ComponentModel.PropertyChangedEventArgs)' failed.
```

It looks like the IL for the `RaisePropertyChanged` callvirt is wrong. 

Fody:

`callvirt instance void [ReactiveUI]ReactiveUI.ReactiveObject::ReactiveUI.IReactiveObject.RaisePropertyChanged(class [System.ObjectModel]System.ComponentModel.PropertyChangedEventArgs)`

Manual:

`callvirt instance void [ReactiveUI]ReactiveUI.IReactiveObject::RaisePropertyChanged(class [System.ObjectModel]System.ComponentModel.PropertyChangedEventArgs)`

**Comment by BrunoJuchli** [comment]
If someones wondering, the difference lies in the **I** before ReactiveObject:
> [ReactiveUI]ReactiveUI.ReactiveObject
> [ReactiveUI]ReactiveUI.**I**ReactiveObject

**Comment by SimonCropp** [comment]
anyone want to submit a PR that fixes this?

**Comment by distantcam** [comment]
Yep might give this a go this weekend.

**Comment by bergi9** [comment]
ReactiveUI's Fody using `[Reactive]` uses `this.RaiseAndSetIfChanged`.
If I use the `[Reactive]` attribute, the PropertyChanged.Fody also weaves it and I have double calls.

**Comment by ltrzesniewski** [comment]
You probably shouldn't use both weavers, they're trying to do the same thing in a different manner.

**Comment by bergi9** [comment]
Yeah, I noticed that and suppressing the PropertyChanged.Fody weaving on every ReactiveObject with [DoNotNotify] on class till this issue get solved.
