### ISSUE TITLE
BadImageFormatException with abstract base class and two levels of derived classes with generic type parameter

### ISSUE THREAD

**Issue by e-tobi** [Fody/PropertyChanged#516]
This happens since 3.2.2  up to  3.2.4. In 3.2.1 it's working fine (using Fody 6.0.8).
The exception is raised when setting derivedB.Something in the code below. The issue does not happen when doing any of these:
- removing the generic type parameter
- removing the "middle" class DerivedA

The breaking change is commit 9a5d794d4c62ac607a62b4e0fde187bfb5ac1463.

I'll dig deeper into this, but just in case this does "ring a bell" to someone...

Here's the failing code, tested with .Net 4.7.2 and .Net Core 3.1:

```C#
using System.ComponentModel;

namespace FodyTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var derivedB = new DerivedB();
            derivedB.Something = "Bar";
        }
    }

    public class DerivedB : DerivedA<string>
    {
        public string Something { get; set; }
    }

    public class DerivedA<T> : Base<T> { }

    public class Base<T> : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    }
}
```

**Comment by ltrzesniewski** [comment]
Damn, sorry about that. I won't be able to look into it until next week though.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by e-tobi** [comment]
Thank you very much! Works fine!

**Comment by SimonCropp** [comment]
@e-tobi btw to be using Fody you should be a Patron on OpenCollective or have a Tidelift subscription https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#licensingpatron-faq
