### ISSUE TITLE
Fody Property Changed in Winforms using BindingSource

### ISSUE THREAD

**Issue by JanBrandenburger** [Fody/PropertyChanged#519]
Dear colleagues,
i use this framework in conjunction with Windows Forms and a BindingSource.
I load the object with Entity Framework from the database and bind it to a BindingSource.
The controls are coupled to the BindingSource so that the DataSourceRefresh mode does not trigger "OnValidation" but "OnPropertyChanged".

Now I have the effect that when I enter text in a text box, the application hangs after each letter.
If you look at the profiling module in Visual Studio, 89 percent of the arithmetic operations are performed by the ProptertyChanged.

If I remove Fody as reference it works smoothly.
I also tried to disable the Equalize mode.
This does not bring any improvement.

Is the behaviour as expected and normal or is there a user error or implementation error by me?

Thanks for any help and advice.

Yours sincerely

Jan Brandenburger

**Comment by SimonCropp** [comment]
@JanBrandenburger just checking, did you read the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md  ?

**Comment by JanBrandenburger** [comment]
Sorry.
