### ISSUE TITLE
Updating to the newest version is now causing SuppressPropertyChangedWarnings in an existing codebase

### ISSUE THREAD

**Issue by distantcam** [Fody/PropertyChanged#539]
I upgraded a project from version `3.0.1` to `3.2.6` and suddenly I'm getting a lot of this new error.

```
warning : Fody/PropertyChanged: Type Test does not contain a [NAME] property with an injected change notification, and therefore the On[NAME]Changed method will not be called. You can suppress this warning with [SuppressPropertyChangedWarnings].
```

There's a lot of places where we use a `OnXXXChanged` name without it refering to a specific property.

It would be nice to be able to turn this off at an assembly level, or in a config, rather than having to apply the attribute to every class.

**Comment by ltrzesniewski** [comment]
FWIW, if you don't use this feature at all, you can turn it off and the warnings will go away as well. But I agree an additional setting for this would be nice.

**Comment by distantcam** [comment]
The problem with turning it off completely is I don't know if we are using it or not, so turning it off may break things.

**Comment by ltrzesniewski** [comment]
Yes, I understand that, maybe we should add a log message which tells if this feature is being used as well.
I won't be able to implement any of that this week though.

**Comment by SimonCropp** [comment]
@distantcam happy to accept a pr that suppresses the warnings via the xml config

**Comment by distantcam** [comment]
Turns out there's an undocumented `SuppressWarnings` config that can turn off the error. I've updated the config schema as part of the PR.
