### ISSUE TITLE
Bad codegen when an indexer uses a weaved property

### ISSUE THREAD

**Issue by klachoo** [Fody/PropertyChanged#544]
It appears I am experiencing a similar problem as [here](https://github.com/Fody/PropertyChanged/issues/72) and can reproduce it at will.
A bit background info on my configuration:
WPF desktop app targeting .Net Framework 4.8 developed using VS 2019 on Windows 10.
Using Fody.6.1.1 and PropertyChanged.Fody.3.2.6
It appears that the exception 
"System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'" comes as long as the following method is present:
```
        public void OnPropertyChanged(string propertyName, object before, object after)
        {
            //Perform property validation
            var propertyChanged = PropertyChanged;
            if (propertyChanged != null)
            {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
```
As soon as I remove it, the application works fine, no exception is thrown. However I would like to have it to be able see the Before/After values as shown [here](https://github.com/Fody/PropertyChanged/wiki/BeforeAfter).
I am attaching my sample project for reproduction.
[INotifyPropertyChangedDemos.zip](https://github.com/Fody/PropertyChanged/files/4348848/INotifyPropertyChangedDemos.zip)
Any feedback would be highly appreciated. Thanks in advance.

**Comment by ltrzesniewski** [comment]
Thanks, I'll take a look.

**Comment by ltrzesniewski** [comment]
The codegen is bad when there's an indexer which depends on weaved properties:

```
    IL_001e: ldarg.0      // this
    IL_001f: callvirt     instance string Data.PersonFody::get_Item(string)
    IL_0024: box          [mscorlib]System.String
    IL_0029: stloc.2      // V_2
```

I'll fix that.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
