### ISSUE TITLE
Package .nuspec is missing the <developmentDependency> flag

### ISSUE THREAD

**Issue by tom-englert** [Fody/PropertyChanged#567]
Just realized that after installing the `PrivateAssets="all"` is missing in the `PackageReference` node.

I have added `PrivateAssets="all"` manually for all weavers where this was missing, and it always worked fine, so looks like #362 is outdated and only relates to use of `package.config`, which IMO can be considered as obsolete.

There should be a property `<DevelopmentDependency>true</DevelopmentDependency>`  in the project, like in [Fody](https://github.com/Fody/Fody/blob/1f16576292ec6254ef0dc2d716aead9c436e084e/Fody/Fody.csproj#L7)

@SimonCropp I did not check other weavers yet, but I guess this is missing in others, too.
Maybe this should be added as a default to the [FodyPackaging.props](https://github.com/Fody/Fody/blob/master/FodyPackaging/build/FodyPackaging.props)?

**Comment by ltrzesniewski** [comment]
The problem is that setting `DevelopmentDependency` to `true` will add:

```XML
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
<PrivateAssets>all</PrivateAssets>
```

`PrivateAssets="all"` will work fine as long as the weaver removes the reference to its library, but that `IncludeAssets` value is a problem, since it does not contain the `compile` item, which means the weaver library won't get referenced for the compilation.

That makes setting `DevelopmentDependency` to true impossible. We'd need another setting which would only set `PrivateAssets="all"`, but that does not exist AFAIK. And even then, you wouldn't be able to set it on all weavers, since some of them need to keep their library after weaving.

**Comment by tom-englert** [comment]
I see, I think I intuitively always removed any `IncludeAssets` immedeately, and never had a weaver that requires a runtime reference.

So we are in the dilemma to either have to always manually add the `PrivateAssets` or remove `IncludeAssets` after installing a new weaver.

**Comment by ltrzesniewski** [comment]
Yeah, unfortunately. It's not a big dilemna though:

 - If a user forgets to add `PrivateAssets="all"` his build will still work.
 - If he forgets to remove `IncludeAssets` the weaver would be unusable.

We're pretty much forced to keep this as-is, or to submit a feature request to NuGet.

**Comment by tom-englert** [comment]
Unfortunately if just one project in the chain of dependencies forgets to add the `PrivateAssets="all"`, the final output will have the weavers attribute-assembly marked as a deployment dependency 😞

**Comment by tom-englert** [comment]
One idea would be to check if the project file contains a ` <PackageReference Include="WeaverName.Fody" `, and, if it exists, check it for valid `PrivateAssets` and `IncludeAssets`.

a) every weaver could do this on his own
b) Fody could implement this and check it for all weavers that opt in via e.g. a new boolean property in the base weaver (like the `ShouldCleanReference`)

**Comment by ltrzesniewski** [comment]
I think I'd prefer b) as the code would be in a single place, so it would be much easier to maintain.

I also suppose we should reuse `ShouldCleanReference` for this instead of adding a new property, I think it always correlates.

**Comment by tom-englert** [comment]
Yes, agree, I will try to do something next weekend.

**Comment by CleanCodeX** [comment]
I still get the message "the package reference for ConfigureAwait.Fody does not contain PrivateAssets='All'"
The problem is. it does not work. What's wrong with it?

<PackageReference Include="Fody" Version="6.2.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

**Comment by ltrzesniewski** [comment]
_"it does not work"_ is not very clear... Maybe you have an `IncludeAssets` value that you need to remove?

**Comment by CleanCodeX** [comment]
Interesting, I copied the whole part of Fody's PackageReference into the post, but there is only "all runtime; build; native; contentfiles; analyzers; buildtransitive" left.
I have had that IncludeAssets part included. Did not change anything.

**Comment by ltrzesniewski** [comment]
We were just saying that if we set `developmentDependency` to true in the NuGet, it would add `IncludeAssets` values on install that would *not* be correct.
