### ISSUE TITLE
PropertyChanged.Fody causes unexpected behavior

### ISSUE THREAD

**Issue by deAtog** [Fody/PropertyChanged#614]
The current documentation states that PropertyChanged.Fody performs the transforms:

```C#
public class Person : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
    
    public string GivenNames { get; set; }
    public string FamilyName { get; set; }
    public string FullName => $"{GivenNames} {FamilyName}";
}
```

Into:
```C#
public class Person : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    string givenNames;
    public string GivenNames
    {
        get => givenNames;
        set
        {
            if (value != givenNames)
            {
                givenNames = value;
                OnPropertyChanged(InternalEventArgsCache.GivenNames);
                OnPropertyChanged(InternalEventArgsCache.FullName);
            }
        }
    }

    string familyName;
    public string FamilyName
    {
        get => familyName;
        set 
        {
            if (value != familyName)
            {
                familyName = value;
                OnPropertyChanged(InternalEventArgsCache.FamilyName);
                OnPropertyChanged(InternalEventArgsCache.FullName);
            }
        }
    }

    public string FullName => $"{GivenNames} {FamilyName}";

    protected void OnPropertyChanged(PropertyChangedEventArgs eventArgs)
    {
        PropertyChanged?.Invoke(this, eventArgs);
    }
}

internal static class InternalEventArgsCache
{
    internal static PropertyChangedEventArgs FamilyName = new PropertyChangedEventArgs("FamilyName");
    internal static PropertyChangedEventArgs FullName = new PropertyChangedEventArgs("FullName");
    internal static PropertyChangedEventArgs GivenNames = new PropertyChangedEventArgs("GivenNames");
}
```

This is in fact misleading as the auto-generated setter for properties does not compare the new value against the backing field, but instead compares it to the value retrieved from the property getter function as follows:

```C#
public class Person : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    string givenNames;
    public string GivenNames
    {
        get => givenNames;
        set
        {
            // Comparison uses the property getter
            if (value != GivenNames)
            {
                givenNames = value;
                OnPropertyChanged(InternalEventArgsCache.GivenNames);
                OnPropertyChanged(InternalEventArgsCache.FullName);
            }
        }
    }

    string familyName;
    public string FamilyName
    {
        get => familyName;
        set 
        {
            // Comparison uses the property getter
            if (value != FamilyName)
            {
                familyName = value;
                OnPropertyChanged(InternalEventArgsCache.FamilyName);
                OnPropertyChanged(InternalEventArgsCache.FullName);
            }
        }
    }

    public string FullName => $"{GivenNames} {FamilyName}";

    protected void OnPropertyChanged(PropertyChangedEventArgs eventArgs)
    {
        PropertyChanged?.Invoke(this, eventArgs);
    }
}

internal static class InternalEventArgsCache
{
    internal static PropertyChangedEventArgs FamilyName = new PropertyChangedEventArgs("FamilyName");
    internal static PropertyChangedEventArgs FullName = new PropertyChangedEventArgs("FullName");
    internal static PropertyChangedEventArgs GivenNames = new PropertyChangedEventArgs("GivenNames");
}
```

When used in conjunction with NHibernate or Entity Framework this causes a number of unintended consequences. E.g. when the property getter is a proxy, it may cause the proxy to be initialized from the database prior to being set. For collection based properties, this can cause a huge performance impact.

If possible, PropertyChanged.Fody should be modified to retrieve the value from the auto-generated backing field as currently documented to avoid the function call overhead and prevent unanticipated behavior when used in conjunction with ORM's like NHibernate and Entity Framework. Using the DoNotNotify attribute may work in some instances, but not others. The DoNotCheckForEquality attribute can be used to skip the equality check, but it may also cause other performance issues.

Given the popularity of these ORM's I would consider this a major improvement for the benefit of all who use this library.

**Comment by ltrzesniewski** [comment]
The documentation is not *exactly* wrong: when injecting the equality check, PropertyChanged.Fody tries to use the underlying field when it can identify one, otherwise it will use the property getter. The field needs to satisfy some constraints in order to be used instead of the property. I believe that changing this logic could cause lots of breaking changes in existing applications.
Maybe it would be better to disable the equality check in your case?

**Comment by deAtog** [comment]
Disabling the equality check does appear to fix the issue, which makes me wonder if the generated proxies should implement Equals to avoid this performance hit. I initially thought it was the use of the property getter that resulted in the issue, when it is in fact the use of `object.Equals` to perform the equality check.

**Comment by ltrzesniewski** [comment]
Well, NHibernate wasn't designed with these use cases in mind. And since it does its own codegen, I suppose it would be best to plug into its own generator to add support of `INotifyPropertyChanged`. Something [like this](https://ayende.com/blog/4106/NHibernate-INotifyPropertyChanged) maybe?

**Comment by deAtog** [comment]
Yeah, something like that might have worked as well, but would cause quite a bit of code churn at this point. We were already using Fody.Virtuosity to ensure all properties were declared virtual and others recommended using Fody.PropertyChanged to simplify the work needed for WinForms and WPF. A sprinkling of the `DoNotCheckForEquality` attribute may suffice for now.

**Comment by SimonCropp** [comment]
@deAtog why are you databinding directly to ORM models? does your app have direct access to the DB?

Also can you confirm all devs on your team are members of the Fody Open Collective https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

**Comment by deAtog** [comment]
@SimonCropp it's a WinForms application that uses local database files for application storage.  

The examples in the documentation state that the comparison is done using the `==` operator when that does not appear to be the case.

MSDN states that for predefined value types, the equality operator (==) returns true if the values of its operands are equal, false otherwise. For reference types other than string, it returns true if its two operands refer to the same object unless the `==` operator has been overloaded. For the string type, it compares the values of the strings using an ordinal comparison.

PropertyChanged.Fody does the following by default:
1. For value types, it uses the == operator.
2. For string types it uses String.Equals using an ordinal comparison.
3. For user defined reference types it uses Object.Equals.

The code generated in number 2, could simply use the `==` operator as String overrides the `==` operator.
The behavior exhibited in number 3 above is unexpected from the examples provided. In my personal opinion, users should have to opt-in for the equality check vs opting-out of it. I.E. users should have to decorate reference types with a `CheckForEquality` attribute to have PropertyChanged.Fody generate code that uses Object.Equals. This would make PropertyChanged.Fody consistent with the behavior of the `==` operator.

**Comment by SimonCropp** [comment]
thanks for you input. unfortunately that would be a large breaking change. I suggest you stop using this library. sorry for the inconvenience

**Comment by ltrzesniewski** [comment]
Note that you can [https://github.com/Fody/PropertyChanged/wiki/Options#checkforequality](disable equality checks globally), but then there's no way to enable them back with an attribute.

**Comment by deAtog** [comment]
@ltrzesniewski yes, I found that option after my last comment.
@SimonCropp I understand a change like this would be a breaking change. In lieu of that the documentation could be updated to reflect the actual behavior. Adding the ability to set the `CheckForEquality` option to false in the FodyWeavers.xml and use an attribute to opt-in when needed would be an improvement. You could even make everything cohesive and use a parameterized attribute, i.e. `CheckForEquality(bool checkEquality)`, to avoid having to check for multiple attributes and always honor the attribute over the global option.

**Comment by tom-englert** [comment]
Wouldn't that be too much effort  just to reanimate a feature in EF Microsoft has abandoned years ago because it was considered a design flaw?
