### ISSUE TITLE
PropertyChanged in sub class

### ISSUE THREAD

**Issue by DenZuck** [Fody/PropertyChanged#645]
How can I add PropertyChanged to derived class ?

```
public class Person : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
    
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

```
public class DerivedPerson : Person
{
    public int Age { get; set; }
}
```

PropertyChanged event is not fired when Age is changed from code behind.

I have also tried the following code but does not work.

```
public class DerivedPerson : Person, INotifyPropertyChanged
{
    public int Age { get; set; }
}
```

Any solution ?

**Comment by SimonCropp** [comment]
i realize this is one of your first issue, but it would be appreciated if you read and followed the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
