### ISSUE TITLE
Supporting PropertyChanged with Add/Remove Handlers

### ISSUE THREAD

**Issue by mysteryx93** [Fody/PropertyChanged#664]
Attaching Fody.PropertyChanged to a class defined like this is not currently supported. Could it be supported? It could be used to get change notifications of sub-properties.

    public class CartViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged
        {
            add
            {
                Order.PropertyChanged += value;
            }
            remove
            {
                Order.PropertyChanged -= value;
            }
        }

        public CartOrder Order { get; set; } = new CartOrder();
    }

**Comment by mysteryx93** [comment]
On that note, [I found a working approach to listen to sub-properties here](https://stackoverflow.com/a/4218764/3960200)

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
