### ISSUE TITLE
Release 4.0 breaks build of all projects targeting min-version <4.72

### ISSUE THREAD

**Issue by tom-englert** [Fody/PropertyChanged#668]
This was a totally useless change, it has no effect except annoying our patrons.

It does not improve anything, it has absolutely no effect on the weavers and their dependencies, because they run in the context of Visual Studio/MSBuild (which btw. only guarantees .net46, see excerpt of `MSBuild.exe.config`)

```xml
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
  </startup>
```

The target version only specifies the minimum version this code is compatible with, it does not enforce anything.

**Comment by tom-englert** [comment]
@SimonCropp @ltrzesniewski I would recommend reverting the latest changes and unlist 4.0 from nuget.

**Comment by SimonCropp** [comment]
yep i was a bit hasty on this on. i am afk atm, so can u unlist 4 for now.  when i am back at computer i will add some more context 

sorry for the hassle

**Comment by SimonCropp** [comment]
just realised u r not a nuget owner. i will unlist in a few hours. and make u both nuget owners

**Comment by ltrzesniewski** [comment]
Actually, we're already owners, as we're in the [Fody organization](https://www.nuget.org/profiles/Fody).

I unlisted v4.0.0.

**Comment by crutkas** [comment]
@tom-englert the reason why this was actually was requested was this: https://github.com/dotnet/runtime/issues/28674

**Comment by tom-englert** [comment]
@crutkas I can't see any relation to the latest changes

**Comment by crutkas** [comment]
what i requested was bumping the NETCore.app

![image](https://user-images.githubusercontent.com/1462282/98020881-70e25080-1db8-11eb-9038-277b76eaa0f1.png)
As you can see, it is grey'ed out.

So then i saw the NETStandard was not consolidated and went there

**Comment by crutkas** [comment]
what i requested was bumping the NETCore.app

![image](https://user-images.githubusercontent.com/1462282/98020881-70e25080-1db8-11eb-9038-277b76eaa0f1.png)
As you can see, it is grey'ed out.

So then i saw the NETStandard was not consolidated and went there
![image](https://user-images.githubusercontent.com/1462282/98020968-8c4d5b80-1db8-11eb-9167-46f5dabce1cd.png)

And that is blocked.

**Comment by crutkas** [comment]
From there, i reached out to @SimonCropp as there had to be a reason why the main lib was on 1.6.1 that i wasn't aware of.

**Comment by ltrzesniewski** [comment]
Ok, that's because the PropertyChanged project targeted `net40;netstandard1.0` before the change. I guess we should add `netstandard2.0` to that list - adding v2.0 is encouraged even if a previous version is already targeted.

**Comment by tom-englert** [comment]
I see, then let's extend the framework list  of PropertyChanged

**Comment by crutkas** [comment]
This work has to also happen with Fody. You / your community knows your projects the best and audience usage patterns.  I'm flagging the CVE
