### ISSUE TITLE
Overridden properties no longer notified in 3.2.10

### ISSUE THREAD

**Issue by brinkdinges** [Fody/PropertyChanged#670]
I just updated a solution from Fody 2.6.1 and noticed different behavior in overridden properties. I checked a bunch of different versions and it starts happening when I upgrade from 3.2.9 to 3.2.10. That version made some changes regarding overridden properties.

PropertyChanged is the only weaver I'm using, the solution uses MSBuild 16, but the projects target .NET 4.7.2.

I don't know what's going wrong, so let me explain what I'm doing. I have a base, a folder, file and configuration. A folder contains multiple files as children, a file contains multiple configurations as children. Changes in children bubble up to their parent. That's possibly not relevant, but I've added it to the repro at the bottom.

The base. (BaseViewModel only implements INotifyPropertyChanged)
```c#
internal class BaseFastenerViewModel : BaseViewModel
{
  public virtual Enums.FastenerType FastenerType { get; set; }
}
```
Folder:
```c#
internal class FolderViewModel : BaseFastenerViewModel
{
  private Enums.FastenerType _fastenerType;
  public override Enums.FastenerType FastenerType
  {
	get => _fastenerType;
	set
	{
	  _fastenerType = value;
	  if (value == Enums.FastenerType.Multiple || _skipUpdatingFastenerTypeOnChildren) return;
	  foreach (var child in Children) child.FastenerType = value;
	}
  }
  public ObservableCollection<BaseFastenerViewModel> Children { get; }
}
```

File
```c#
internal class FileViewModel : BaseFastenerViewModel
{
  private Enums.FastenerType _fastenerType;
  public override Enums.FastenerType FastenerType
  {
    get => _fastenerType;
    set
    {
      _fastenerType = value;
      if (value == Enums.FastenerType.Multiple || _skipUpdatingFastenerTypeOnChildren) return;
      foreach (var child in Children) child.FastenerType = value;
    }
  }
  public ObservableCollection<ConfigurationViewModel> Children { get; private set; } = new ObservableCollection<ConfigurationViewModel>();
}
```

The relevant section of the resulting code for **FileViewModel** in 2.6.1 up to 3.2.9 according to .NET Reflector:
![File fody old](https://user-images.githubusercontent.com/15387410/98117840-96e81d80-1eaa-11eb-92f1-2b080e32ef71.png)

And in 3.2.10:
![File fody 3 2 10](https://user-images.githubusercontent.com/15387410/98117866-9bacd180-1eaa-11eb-9294-8983bc4e11cd.png)

I created a small project where I can reproduce it:
https://github.com/brinkdinges/fody-propertychanged-repro/tree/master/PropertyChanged

Regarding being a Patron; I just made my company CAD Booster one.

**Comment by ltrzesniewski** [comment]
IIRC the weaver now assumes that a virtual property will call the base property, and the base property sends the notification.

You should be able to fix this in two ways, choose the one you prefer:

- Make `BaseFastenerViewModel.FastenerType` `abstract` instead of `virtual`. I think this should insert the change notifications since there's no base implementation to call.

- Or make use of the base property instead of defining `_fastenerType`: remove the field and replace all references to it with `base.FastenerType`.

I guess this change should have shipped in a minor version update instead of a patch one.

**Comment by brinkdinges** [comment]
Thank you, Lucas. Both methods seem to work. The first one indeed adds the notification again, whereas the second does not. I don't understand it yet, but I'll read up on it.

What is the best way to share these changes when people release a new version, for example on NuGet? Is there a standardized way of telling developers what behavior has changed and what they may need to do to get it working again?

**Comment by tom-englert** [comment]
I think this sample should work out of the box - we had added a check if the setter calls the base class setter, and, if not, it should notify.

I'll have a look next weekend, to see what's going wrong here.

**Comment by tom-englert** [comment]
We did the check in the setter, but only if (any).set_Property() is called, so it interpreted child.set_Property as a call to base.set_Property, thus omitting the change notification.

**Comment by brinkdinges** [comment]
Awesome. Thanks for fixing it.
