### ISSUE TITLE
ClickOnce Error In .NET 5.0,

### ISSUE THREAD

**Issue by wf-soft** [Fody/PropertyChanged#678]
@SimonCropp Hi!
PropertyChanged cannot find a dependency in. Net 5's ClickOnce, which makes the program unable to run. Is there a solution.

`Description: A .NET application failed.
Application: QMbackClient.exe
Path: C:\Users\wf-so\AppData\Local\Apps\2.0\6R77A09D.QHE\XYJVD45Q.HEG\qmba..tion_0000000000000000_0001.0000_b8a995e444f4a1ee\QMbackClient.exe
Message: Error:
  An assembly specified in the application dependencies manifest (QMbackClient.deps.json) was not found:
    package: 'PropertyChanged.Fody', version: '3.3.1'
    path: 'lib/netstandard2.0/PropertyChanged.dll'`

**Comment by wf-soft** [comment]
The new ClickOnce seems to need to PropertyChanged.dll Copy to the user app installation directory to run normally

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
