### ISSUE TITLE
Common Language Runtime detected an invalid program.

### ISSUE THREAD

**Issue by julesx** [Fody/PropertyChanged#72]
I am using VS 2013, .Net 4.

Once I install PropertyChanged my program throws this error as soon as I try to set a property.  I have not yet implemented any Fody code, only installed the package. Once I uninstall the package the error goes away.

A first chance exception of type 'System.InvalidProgramException' occurred in My.exe

Additional information: Common Language Runtime detected an invalid program.

The stack trace reveals nothing useful.

Is there anything I can provide to track down this issue?  Would love to use this addon.

Thanks

**Comment by klachoo** [comment]
Hi Simon
It appears I am experiencing the exact same problem and can reproduce it at will.
A bit background info on my configuration:
WPF desktop app targeting .Net Framework 4.8 developed using VS 2019
Using Fody.6.1.1 and PropertyChanged.Fody.3.2.6
It appears that the exception 
"System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'" comes as long as the following method is present:
        public void OnPropertyChanged(string propertyName, object before, object after)
        {
            //Perform property validation
            var propertyChanged = PropertyChanged;
            if (propertyChanged != null)
            {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
As soon as I removed it it works fine. However I would like to have it to be able see the Before/After values.
I am attaching my sample project for reproduction.
[INotifyPropertyChangedDemos.zip](https://github.com/Fody/PropertyChanged/files/4348848/INotifyPropertyChangedDemos.zip)
Your feedback would be highly appreciated. Thanks in advance.

**Comment by ltrzesniewski** [comment]
@klachoo you shouldn't post in years-old issues, this is probably a very different bug by now. Please open a new issue for this.

**Comment by klachoo** [comment]
@ltrzesniewski OK. Will do. Was not sure whether to create a new issue or reuse this existing one.
