### ISSUE TITLE
Ignore Types/Classes with names

### ISSUE THREAD

**Issue by MarioGK** [Fody/PropertyChanged#760]
#### Guidance

I would love to make a PR for this, if anyone could give me any tips where to read or start, or if the feature would even get accepted before i begin working on this.

I did a little work here https://github.com/MarioGK/PropertyChanged/commit/76b93e0e34091594144fca21e0ba89967a62248e
i think this would be enough to fix the issue, i dont know if it is working because i didnt manage to test it locally.

#### Is the proposal related to a problem

I am using Avalonia without ReactiveUI and its own Fody package, and Avalonia has custom made NotifyProperty changed methods which are private so the solution is to add [DoNoNotify] to every view class, with this feature it would remove the need to add this attribute to every single view.

#### Describe the solution

A config in FodyWeavers.xml that accepts multiple strings, if the class name contains any string it would get ignored.

**Comment by SmRiley** [comment]
Has this been merged into the main branch?
