### ISSUE TITLE
Issue on set property on parent class

### ISSUE THREAD

**Issue by liors619** [Fody/PropertyChanged#772]
consider the following scenario:

```
public class BaseClass
{
    protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)
    {
        //do some logic
        storage = value;
    }
}

public class ViewModel: BaseClass{
        //some property which depends on HasError property.

        private bool hasError = false;
        public bool HasError
        {
            get => hasError;
            set => SetProperty(ref hasError, value);
        }
}
```

I wrote something like that in an app I work on and I found out that PropertyChanged event was raised only for the property that depends on "HasError" and wasn't raised for the property "HasError" itself,

looks like an unexpected behavior.

**Comment by SimonCropp** [comment]
did you read the issue template?

**Comment by liors619** [comment]
> did you read the issue template?

No, couldn't find one, please supply a link and I'll edit the issue,
Thanks.

**Comment by SimonCropp** [comment]
https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by liors619** [comment]
Description:
assume we using prism Bindable Base and override the method "Set Property" and not Raise property changed event on that method, the event will be raised only on properties the depends on the property that actually changed and not on the property itself.

git repo with a unit test:
https://github.com/liors619/FodyIssue

I don't know how to fix the issue, I opened it just to let you know about this.

**Comment by tom-englert** [comment]
PropertyChanged.Fody knows that SetProperty on BindingBase will already raise the property changed event, so it does nothing on such properties.
If you override SetProperty with something different, you will get something different - no surprise here.

If you call SetProperty in the setter of the property, you don't need PropertyChanged.Fody. 
If you want PropertyChanged.Fody to handle the events, just use a simple property.
