### ISSUE TITLE
Weaving not applied during Live Unit Testing

### ISSUE THREAD

**Issue by richardhauer** [Fody/PropertyChanged#776]
Bit new to Fody so pls go easy. There are a few moving parts to this that I've tried as a result of reading various posts/articles.
I'm unsure if this is an issue with `PropertyChanged.Fody` or if `Fody` in its entirety is not being executed under LUT scenarios. Happy to post to another location if that's appropriate but thought I'd start at the highest level of specificity.

### Environment

I have a basic soln structure as follows:
 * VS 2022 (17.0.0 Preview 5) 
 * C# Library project (sdk=`Microsoft.Net.Sdk`) targeting `net6.0`
 * MSTest v2 library targeting same
 * Library project has a base (abstract) class with `INotifyPropertyChanged` and `protected virtual void OnPropertyChanged( string propertyName )`
 * Test library has a class that inherits from the base and implements a basic string property (auto-implemented)
 * All projects have `FodyWeavers.xml` in the root with the `<PropertyChanged />` element added
 * There are no other weavers present
 * All projects have references as follows:

```
<PackageReference Include="Fody" Version="6.5.3">
	<PrivateAssets>all</PrivateAssets>
</PackageReference>
<PackageReference Include="PropertyChanged.Fody" Version="4.0.0">
	<PrivateAssets>all</PrivateAssets>
</PackageReference>
```
### Problem

**Nothing** I can do will make `OnPropertyChanged()` fire in the context of Live Unit Testing.
I _can_ get it to work when running through Test Explorer and via `dotnet test` so this isn't an issue with the normal operation of the library per se.

I have been unable to identify a discrepancy between the build process used in LUT/roslyn and the normal `dotnet build`/`msbuild` so I can't imagine why it wouldn't work, hoping someone with experience in this area can direct me to whatever changes might be necessary to get LUT going.

**Observation**:  `Fody` & `PropertyChanged.Fody` packages need to be applied to both the library project AND the MSTest project in order for it to work through Test Explorer - I would not have expected this to be the case, but may be a clue.  Presumably these references are only required on the project that actually uses the weaving?

Anyone have any suggestions or thoughts?

**Comment by ltrzesniewski** [comment]
> As you're developing an application, Live Unit Testing automatically runs any impacted unit tests in the background and presents the results and code coverage in real time.

I'm not really surprised it doesn't work, since VS needs to do coverage analysis...

We could try to hook Fody on `$(TargetsTriggeredByCompilation)` to see if it works better that way (currently it is being hooked with `AfterTargets="AfterCompile"`).

> Fody & PropertyChanged.Fody packages need to be applied to both the library project AND the MSTest project in order for it to work through Test Explorer

That's strange... these packages shouldn't be needed in the test project. I just tested the Test Explorer on a project of mine that uses Fody and it works (I usually use Rider instead of the Test Explorer).

**Comment by tom-englert** [comment]
@richardhauer 

> * Test library has a class that inherits from the base and implements a basic string property (auto-implemented)

I think this could be the root cause, the class you are testing is in the test library! At least that is the reason why you need `PropertyChanged.Fody` in the test project!

**Comment by richardhauer** [comment]
@tom-englert  yes that's the conclusion that I came to - the transient reference to the `PropertyChanged.Fody` library is not sufficient.

Coupled with the msbuild minor adjustment and I have the LUT setup working a treat now.
I have just removed all my `[TestCategory("SkipWhenLiveUnitTesting")]` flags and all the tests are running properly with coverage showing.

**Comment by tom-englert** [comment]
@richardhauer would be interesting to know if that modifications is still needed if the class you are testing is NOT in the test project but in the library project.

**Comment by richardhauer** [comment]
Cross-reference:
https://github.com/Fody/Fody/issues/1034
