### ISSUE TITLE
Support signed assemblies

### ISSUE THREAD

**Issue by kzu** [Fody/PropertyChanged#79]
There is no reason why ViewModels, app assemblies, etc. can't be signed. 

This, however, breaks Fody.PropertyChanged since it's not signed, and for whatever reason, even if I'm not using its attributes (or need a reference to it at all), the C# compiler still fails because of the lack of the signed Fody assembly.

Total showstopper :(

**Comment by Haacked** [comment]
Strong name is pretty much required for building Visual Studio extensions.

**Comment by kzu** [comment]
Not only that: SN'ed assemblies can be loaded side-by-side in the same AppDomain. This is key when developing VS extensions that leverage common libraries where multiple versions might be installed at the same time.

**Comment by SimonCropp** [comment]
@Haacked  confused. it has been SNed since May

**Comment by Haacked** [comment]
SimonCropp: whoops, I thought I was commenting on Fody.NullGuard. Any chance we could SN that?

**Comment by themightylc** [comment]
I'm sorry to hijack this issue thread - I can't figure out where else to write/ask stuff.
If i understand this correctly, version 1.50+ is strong-named now. However I cannot include 1.50+ in my .net 3.5 application - it seems to be compiled for 4.0. Is this intentional?

**Comment by SimonCropp** [comment]
@themightylc yeah. It was decided the effort of maintianing and testing on a 8 year old runtime was not worth it

**Comment by themightylc** [comment]
Agreed. I just could not find any information on this and was a little
surprised. Thank you for your response!

2015-07-11 16:50 GMT+02:00 Simon Cropp <notifications@github.com>:

> @themightylc <https://github.com/themightylc> yeah. It was decided the
> effort of maintianing and testing on a 8 year old runtime was not worth it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fody/PropertyChanged/issues/79#issuecomment-120626935>
> .
>



-- 

Mit freundlichen Grüßen

Christoph Grün -Entwicklung und Design

--

Firma: Dresen und Grün GbR
Geschäftsführende Gesellschafter:
Markus Dresen, Christoph Grün

Anschrift: Weilandstr. 1A, 66359 Bous
Telefon: 06898 / 39 04 998
Steuernummer:010/152/00703
