### ISSUE TITLE
Wiki OnChangedMethod reference typo

### ISSUE THREAD

**Issue by nll** [Fody/PropertyChanged#792]
Hi, sorry if this is not the right way, but I didn't find another way or how to do it.

In the wiki pages 

- [On_PropertyName_Changed](../wiki/On_PropertyName_Changed)
- [Attributes](../wiki/Attributes)

Where we see `OnChangeMethod`/`OnChangeMethodAttribute` we should have `OnChangedMethod`/`OnChangedMethodAttribute`

**Comment by ltrzesniewski** [comment]
Thanks! Fixed.
