### ISSUE TITLE
Maui support

### ISSUE THREAD

**Issue by softlion** [Fody/PropertyChanged#826]
Hello :)  
I'm a big fan of fody.

But I have been unable to make Fody.PropertyChanged work in an Maui project.

It does compile fine, but propertychanged events are not triggered.

So it would be a nice to have.

**Comment by ltrzesniewski** [comment]
Hi, I don't know Maui, but using it shoudn't change the behavior of this addin (it is framework-agnostic), unless Maui has some custom build pipeline.

Could you:
 - post a binlog of a sample project (`dotnet build --no-incremental -bl` then upload the msbuild.binlog file). Make sure to compile a sample so no sensitive info leaks out, also make sure you don't have anything sensitive in your environment variables.
 - decompile an auto-property setter that is supposed to raise property change notifications and show what it looks like

**Comment by softlion** [comment]
Injection not working (code decompiled)

![image](https://user-images.githubusercontent.com/190756/157974542-155d09df-597e-465c-8340-5e8bc6f04d7b.png)

I'm trying to get the project to compile using the command line, but it's not building yet. I'm getting an Invalid framework identifier error.

**Comment by SimonCropp** [comment]
@softlion happy to accept a pull request that fixes this issue

**Comment by ltrzesniewski** [comment]
That screenshot shows the source code, _not_ the decompiled code. 🙂 

I may take a look at the issue later, when I have some time.

**Comment by softlion** [comment]
@ltrzesniewski No it's the decompiled code using 

![image](https://user-images.githubusercontent.com/190756/158018371-aaa6272a-0316-4904-91c1-32b69df055ff.png)

**Comment by softlion** [comment]
@ltrzesniewski you are right

![image](https://user-images.githubusercontent.com/190756/158018417-7aea880d-18dd-4ea5-bfbf-e74f00d23cee.png)

**Comment by ltrzesniewski** [comment]
Ah, nice, thanks! But that screenshot shows that PropertyChanged.Fody is working correctly... 😕

**Comment by softlion** [comment]
You are right. It's an issue with maui. Closing.
