### ISSUE TITLE
Cannot edit source code and continue when Fody is in solution

### ISSUE THREAD

**Issue by Astyan** [Fody/PropertyChanged#84]
With fody installed with nuget, i cant edit source and continue without having Visual studio wanting me to fix compilation error. But Visual studio does not display any compilaiton error in Error list tab and the change i make is correct and should not cause compilation error.

Please download this solution (12Ko) http://s000.tinyupload.com/index.php?file_id=84597648432947743572

Just run it in debug mode and when you reach the Debugger.Break, follow the comment to reproduce the bug.

**Comment by joelong01** [comment]
this problem happens on WinUI3 apps.  I couldn't make it work, so I have to stop using Fody.

**Comment by SimonCropp** [comment]
@joelong01 yep. that is the correct approach to take
