### ISSUE TITLE
Problems with MVVM Toolkit

### ISSUE THREAD

**Issue by RedX2501** [Fody/PropertyChanged#846]
Fody: 6.5.1
PropertyChanged.Fody: 3.4.0

## Describe the issue

The following code

```csharp
    [ObservableObject]
    public partial class AnyViewModel
    {
        [ObservableProperty]
        private string someField = "hey";
    }
```

Generates the following code:

```csharp
[GeneratedCode("Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "7.1.0.0")]
[DebuggerNonUserCode]
[ExcludeFromCodeCoverage]
public string SomeField
{
	get
	{
		return someField;
	}
	set
	{
		if (!EqualityComparer<string>.Default.Equals(someField, value))
		{
			OnPropertyChanging(__KnownINotifyPropertyChangedOrChangingArgs.SomeFieldPropertyChangingEventArgs);
			someField = value;
			OnPropertyChanged(<>PropertyChangedEventArgs.SomeField);
			OnPropertyChanged(__KnownINotifyPropertyChangedOrChangingArgs.SomeFieldPropertyChangedEventArgs);
		}
	}
}
```

1. Any assignment of different values to `someField` will generate a duplicate `PropertyChanged` event.

Settings `[PropertyChanged.DoNotNotify]` on the field has no effects (obviously).

# Minimal Repro

1. Copy paste the example above in any WPF project using Microsoft.MVVM.Toolkit.
3. Compile.
4. Look at the IL.

# Make an effort to fix the bug

Maybe the generator should see that a (oddly) placed call to the `OnPropertyChanged` already exists and therefore not emit one?

Or should `[PropertyChanged.DoNotNotify]` be extended to also work on fields? For some reason the flags already indicate that it can be set on fields but it has no effect.

**Comment by RedX2501** [comment]
Because MVVM Toolkit does not automatically do the `PropertyChanged` call for properties. Only for fields and only when you annotate them with `ObservableProperty`.

Then should maybe the `DoNotNotify` attribute have it's `AttributeTargets.Field` flag removed to avoid confusion?

**Comment by ltrzesniewski** [comment]
> Then should maybe the `DoNotNotify` attribute have it's `AttributeTargets.Field` flag removed to avoid confusion? What feature of `PropertyChanged.Fody` is used on fields that could use this flag?

Yup, it's inconsistent. I opened #847 to fix this.

**Comment by tom-englert** [comment]
Deployed.
