### ISSUE TITLE
Feature proposal: Add INotifyPropertyChaning

### ISSUE THREAD

**Issue by ShadyHarbinger** [Fody/PropertyChanged#865]
It would complete this great package. People usually forget how useful the INotifyPropertyChaning can be.
E.g. I created an helper class that provides cancel, undo, save and related functions for a model so the model can be used as a great ViewModel. INotifyPropertyChaning is needed for backing up the initial property value. Could You please implement this feature sometime?

**Comment by tom-englert** [comment]
https://github.com/Fody/PropertyChanging
