### ISSUE TITLE
PropertyChanged.Fody 4.0.0 exists!

### ISSUE THREAD

**Issue by ricaun** [Fody/PropertyChanged#867]
I was trying to use the last version of the `PropertyChanged.Fody` and usually, in my `csproj` I use something like this, with the `*` on the version.
```xml
<PackageReference Include="PropertyChanged.Fody" Version="*"/>
```
Works fine until I noticed the version is `4.0.0`, and the last release is `3.4.1`...

By looking on the `nuget.org` there is an unlisted version with the last updated 11/3/2020. 
Here is the link: https://www.nuget.org/packages/PropertyChanged.Fody/4.0.0

I'm using the last version of Visual Studio 2022, and looks like is doing what's supposed to do, selecting the higher version.

Maybe in the `nuget manager`, the version `4.0.0` is only unlisted and not set like Deprecation or Legacy, I suppose that's the reason my project is fiding this version.

Not sure if this is the case, but could be the solution.

**Comment by ltrzesniewski** [comment]
Yes, v4 was unlisted, see #668 (you can't delete a release from NuGet once it has been published).

That said, it seems *very* wrong for NuGet to automatically select an unlisted version. I would recommend opening an issue in the NuGet repo (I'm currently AFK so I'd rather not do it myself).

**Comment by ricaun** [comment]
Maybe if version `4.0.0` is set to Deprecate the NuGet does not consider the latest version:

- https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

> That said, it seems _very_ wrong for NuGet to automatically select an unlisted version. I would recommend opening an issue in the NuGet repo (I'm currently AFK so I'd rather not do it myself).

Gonna open an issue in the NuGet repo if the Deprecate does not work.

**Comment by ltrzesniewski** [comment]
Ok, I just marked v4.0.0 as deprecated. But even though, NuGet is not supposed to auto-discover an unlisted version.

BTW, be aware that you're exposing yourself to breaking changes by specifying `Version="*"`, I'd rather recommend `Version="3.*"`.

**Comment by ltrzesniewski** [comment]
Closing this, see https://github.com/NuGet/Home/issues/11989 for details.

There's not much we can do until we release v4.0.1 or anything > v4.0.0.

**Comment by ltrzesniewski** [comment]
Oh yes, sorry, I should have mentioned it here.
