### ISSUE TITLE
Using In Interface

### ISSUE THREAD

**Issue by Hamcker** [Fody/PropertyChanged#88]
Hi there,
Can we use PropertyChanged.ImplementPropertyChanged Attribute on interfaces and see the result on implemented classes?

**Comment by tofutim** [comment]
Why should it not be a support scenario? If I have an interface that I want to have INotifyPropertyChanged it cannot currently be done using PropertyChanged.Fody. Normally I would just roll with it, but I'm trying to support some existing code that uses a lot of interfaces.
