### ISSUE TITLE
Documentation of IsChanged flag

### ISSUE THREAD

**Issue by michaelFeilhofer** [Fody/PropertyChanged#968]
Hello,

The documentation of PropertyChanged.Fody says that property in compiled code looks like this

```
public string GivenNames
{
    get => givenNames;
    set
    {
        if (value != givenNames)
        {
            givenNames = value;
            OnPropertyChanged(InternalEventArgsCache.GivenNames);
            OnPropertyChanged(InternalEventArgsCache.FullName);
        }
    }
}
```

in 'Implementing An IsChanged Flag' the documentation says that compiled code looks like this

```
public string Name
  {
    get { return name; }
    set
    {
      name = value;
      IsChanged = true;
      OnPropertyChanged("Name");
    }
  }
```

Why is there no check for equality?
Is the 

` if (value != name )...`

missing in the documentation?

**Comment by ltrzesniewski** [comment]
Thanks for noticing this. I'm pretty sure the `if` is there but missing in the documentation. I'll check this and add it to the doc.

**Comment by ltrzesniewski** [comment]
I can confirm the check is added. I've updated the [wiki page](https://github.com/Fody/PropertyChanged/wiki/Implementing-An-IsChanged-Flag).

The following code from the unit tests:

```csharp
using System.ComponentModel;

public class ClassWithIsChanged :
    INotifyPropertyChanged
{
    public string Property1 { get; set; }
    public bool IsChanged { get; set; }

    public event PropertyChangedEventHandler PropertyChanged;
}
```

Gets processed like this:

![image](https://github.com/Fody/PropertyChanged/assets/7913492/1d9c0666-1dc3-41e4-895f-1c472c8d66b3)

The docs page doesn't show all the real internal details, but it should give a good overall idea of what happens.

**Comment by michaelFeilhofer** [comment]
Thank you for clarification!
