### ISSUE TITLE
Issue when assigning null value to nullable properties

### ISSUE THREAD

**Issue by Luigi6821** [Fody/PropertyChanged#992]
I am trying to create a base class that store all the properties that has been changed since its own instantiation.
The base class is the following:

` [AddINotifyPropertyChangedInterface]
 public abstract class PropertyChangedData 
 {
     private readonly HashSet<string> _memberChanged = new(StringComparer.OrdinalIgnoreCase);

     protected void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
     {
         _memberChanged.Add(e.PropertyName);
     }

     public bool IsChanged(string memberName)
     {
         return _memberChanged.Contains(memberName);
     }
 }`

The class defines method IsChanged for getting a boolean if property has been chaged or not.
So far so good.
A possible derived class is the following:

`  class InsertableFunctionItem : PropertyChangedData
    {
        public decimal FunctionId { get; set; }
        public decimal DeptId { get; set; }
        public decimal? ParentFunctionId { get; set; };
        public decimal? CriticalityId { get; set; };
        public decimal? LocationId { get; set; } ;
        public string FuncNo { get; set; } ;
        public string FuncDescr { get; set; } ;
        public string FuncRef { get; set; } ;
        public string UserDefText { get; set; } ;
        public string UserDefText2 { get; set; } ;
        public string UserDefText3 { get; set; } ;
        public string UserDefText4 { get; set; } ;
        public string UserDefText5 { get; set; } ;
        public string UserDefText6 { get; set; } ;
        public string Notes { get; set; };
        public DateTime? LastUpdated { get; internal set; } ;
    }`

In case I assign a null value to a nullable property the OnPropertyChanged is not raised because I guess is raised only when assigned value is != from existing one.
For certain scenario I need to understand if any value (even if is the current one) has been assigned to a specific property.
This information gives me the possibility to generate an appropriate UPDATE/INSERT statement basing on properties to which a value has been assigned (even if is null or current one) but only when there is a specific assignment after CTOR.

Example1:
class Example : PropertyChangedData 
{
   public decimal ID { get; set; }
   public string ColumnA  { get; set; }
   public  DateTime? ColumnB { get; set; }
}

var instance = new Example();
instance.ID = 1;
instance.ColumnA = null;

instance.IsChanged("ID") = true
instance.IsChanged("ColumnA") = true
instance.IsChanged("ColumnB") = false
UPDATE result statement should be : UPDATE Table1 set ID = 1, ColumnA = null;

Example2:
class Example : PropertyChangedData 
{
   public decimal ID { get; set; }
   public string ColumnA  { get; set; }
   public  DateTime? ColumnB { get; set; }
}

var instance = new Example();
instance.ID = 1;
instance.ColumnB = null;

instance.IsChanged("ID") = true
instance.IsChanged("ColumnA") = false
instance.IsChanged("ColumnB") = true

UPDATE result statement should be : UPDATE Table1 set ID = 1, ColumnB = null;

How I can achieve it?
Thanks in advance
Best regards
Luigi

**PS: I found the attribute DoNotCheckEqualityAttribute that solve the issue**

**Comment by ltrzesniewski** [comment]
I'm closing this since you found the solution.

PS: You can use 3 backticks (```) to start and end a multiline block of code.
