### ISSUE TITLE
OnChangedMethodAttribute cannot rise the exception

### ISSUE THREAD

**Issue by ali50m** [Fody/PropertyChanged#993]
If run the code without debugging, the exception cannot raise.

repo: 
https://github.com/ali50m/FodyOnChangedMethodIssue

VM Code:
```csharp
[AddINotifyPropertyChangedInterface]
internal class MainViewModel
{
    [OnChangedMethod(nameof(When_Input_Changed))]
    public int Input { get; set; }

    public string Output { get; private set; } = "0";

    private void When_Input_Changed()
    {
        if (Random.Shared.Next(10) > 5)
        {
            throw new InvalidOperationException();
        }

        Output = $"{Input}";
    }
}
```

View code:
```xml
    <Window.DataContext>
        <fodyOnChangedMethodIssue:MainViewModel />
    </Window.DataContext>
    <StackPanel>
        <TextBox Text="{Binding Input, UpdateSourceTrigger=PropertyChanged}" />
        <TextBlock Text="{Binding Output}" />
    </StackPanel>
```
![screenshots](https://github.com/ali50m/FodyOnChangedMethodIssue/assets/9393831/fb6db190-ccb7-492e-9cde-51f79e131b56)

**Comment by tom-englert** [comment]
I'm not sure what you expect here. 
Binding by default will swallow any exception, so in the sample code of course you will see no effect.

**Comment by tom-englert** [comment]
And in the video you can see on 5 and 7 that it got stuck because of the exception

**Comment by tom-englert** [comment]
So looks like this is not an issue
