### ISSUE TITLE
The setter method is not called if the new value is equal to old one

### ISSUE THREAD

**Issue by ZhibingGe** [Fody/PropertyChanged#996]
When the Index value was set to 0, The print method was expected to be called, but it was never called because the old value is 0. 
When Add [DoNotCheckEquality] attribute to class or property, the print  method was called.

The setter method should be called always, and the DoNotCheckEquality should be only used to judge whether the propertychanged event is triggerred. 

```
public class Demo : INotifyPropertyChanged
{
    private int _index;

    public int Index
    {
        get
        {
            return _index;
        }
        set
        {
            _index = value;
            Print();
        }
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    public void Print()
    {
        Console.WriteLine("Settor method of index has been called");
    }
}
```

**Comment by SimonCropp** [comment]
can you submit a failing unit test as a pull request

**Comment by ltrzesniewski** [comment]
I'd say this is the expected behavior, and changing it at this point would break a lot of user projects.
